In [58]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [59]:
df=pd.read_csv("flats_outlier_treatment.csv")

In [60]:
df.shape

(3034, 27)

In [61]:
df.head()

,Unnamed: 0,society,bedrooms,baths,link,floors_in_building,price,area,area_sqft,servant_quarters,kitchens,store_rooms,price_per_sqft,drawing_room,dining_room,lounge_or_sitting_room,laundry_room,study_room,prayer_room,powder_room,gym,steam_room,other_rooms,luxury_score,furnishing_score,floor,agePossession
0,0,Askari,4.0,4.0,https://www.zameen.com/Property/askari_askari_...,9.0,4.55,12.0,3264.0,1.0,1.0,1.0,13939.950980,1,1,1,1,1,1,1,0,0,0,135.0,37,3,New Property
1,1,Askari,4.0,5.0,https://www.zameen.com/Property/askari_10_aska...,10.0,4.50,12.2,3318.4,1.0,1.0,NaN,13560.752170,1,1,0,0,1,1,0,0,0,1,150.0,31,3,New Property
2,2,Askari,3.0,4.0,https://www.zameen.com/Property/askari_11_aska...,NaN,3.55,10.0,2720.0,1.0,1.0,1.0,13051.470588,1,1,1,1,1,1,1,1,1,1,156.0,49,NaN,New Property
3,3,Askari,4.0,4.0,https://www.zameen.com/Property/askari_askari_...,NaN,4.45,7.6,2067.2,1.0,2.0,1.0,21526.702786,1,1,0,0,1,0,0,0,0,1,125.0,18,NaN,New Property
4,4,Askari,4.0,5.0,https://www.zameen.com/Property/askari_10_aska...,10.0,4.65,12.2,3318.4,1.0,1.0,1.0,14012.777242,1,1,0,0,1,1,0,0,0,1,100.0,18,3,New Property

In [62]:
df.isnull().sum()

Unnamed: 0                   0
society                      0
bedrooms                    94
baths                       30
link                         0
floors_in_building        1409
price                        0
area                         0
area_sqft                    0
servant_quarters          1354
kitchens                   738
store_rooms               1322
price_per_sqft               0
drawing_room                 0
dining_room                  0
lounge_or_sitting_room       0
laundry_room                 0
study_room                   0
prayer_room                  0
powder_room                  0
gym                          0
steam_room                   0
other_rooms                  0
luxury_score                 0
furnishing_score             0
floor                     1108
agePossession                0
dtype: int64

In [63]:
df = df.drop(columns=["Unnamed: 0"], errors="ignore")

In [64]:
df[df['bedrooms'].isnull()].iloc[1]['link']

'https://www.zameen.com/Property/bahria_town_sector_f_bahria_town_-_tauheed_block_studio_apartment_320_sq_ft_bahria_town_lahore-53887512-11864-1.html'

In [65]:
text = df["link"].fillna("").str.lower()
missing = df["bedrooms"].isna()

is_studio = text.str.contains(r"\bstudio\b|studio_apartment|studio-apartment", regex=True)
is_1bed = text.str.contains(r"\b1[-_\s]?(?:bed|bedroom|beds)\b", regex=True)

df.loc[missing & is_studio, "bedrooms"] = 0
df.loc[missing & is_1bed, "bedrooms"] = 1

In [66]:
is_studio.sum()

np.int64(122)

In [67]:
df[df['bedrooms'].isnull()]['link'].value_counts()

link
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_e_studio_ready_to_move_apartment_available_for_sale_in_sector_e_bahria_town_lahore-53931097-1802-1.html                                                                                                      1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_b_prime_location_apartment_available_for_sale_in_bahria_town_lahore-53781563-1772-1.html                                                                                                                     1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_c_4_star_serviced_apartment_managed_by_falettis_hotels_bahria_town-53909154-1784-1.html                                                                                                                      1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_b_prime_location_apartments_in_madina_heights_5_bahria_town_lahore_available_on_easy_installments-53781570-1772-1.html                                                                                       1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_f_studio_semi_furnished_apartment_available_for_sale_in_sector_f_bahria_town_lahore-53897169-3097-1.html                                                                                                     1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_e_book_one_bed_luxury_apartment_on_easy_instalment_plan_in_bahria_town_lahore-51806954-1802-1.html                                                                                                           1
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_e_zameen_jade_lahore_premium_living_with_assured_15_cashback-53229470-1802-1.html                                                                                                                            1
https://www.zameen.com/Property/bahria_town_sector_e_bahria_town_-_nishtar_block_food_court_bahria_town_lahore-53760506-1806-1.html                                                                                                                                           1
https://www.zameen.com/Property/bahria_town_midway_commercial_studio_1_2_bed_apartments_available_on_easy_plan_possession_within_1_year_bahria_town_lahore-53718490-21559-1.html                                                                                              1
https://www.zameen.com/Property/gulberg_gulberg_3_pay_zero_down_payment_star_luxury_hotel_apartment_only_in_ramadan-53913154-3824-1.html                                                                                                                                      1
https://www.zameen.com/Property/gulberg_mm_alam_road_furnished_serviced_apartment_available_with_hybrid_model-52986074-3850-1.html                                                                                                                                            1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_apartments_on_hybrid_model_with_actual_rental_return-52833921-19464-1.html                                                                                                                                    1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_investor_quota_hotel_apartments_for_good_rental_income-52947353-19464-1.html                                                                                                                                  1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_hotel_apartment_for_passive_income-53211712-19464-1.html                                                                                                                                                      1
https://www.zameen.com/Property/gulberg_mm_alam_road_fully_furnished_service_apartment_for_sale_in_pearl_one_residences_mm_alam_road_ready_for_possession-53657612-3850-1.html                                                                                                1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_invest_82_lac_in_swiss_mall_earn_82_000_pkr_monthly-52738636-19464-1.html                                                                                                                                     1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_1-bed_furnished_apartment_for_sale_cbd_lahore-52901360-21580-1.html                                                                                                                                  1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_furnished_service_apartment_for_sale_cbd_lahore-53239661-21580-1.html                                                                                                                                1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_1-bed_furnished_apartment_for_sale_cbd_lahore-53238662-21580-1.html                                                                                                                                  1
https://www.zameen.com/Property/mian_mehmood_ali_kasoori_road_madison_square_mall_15_guaranteed_rental_apartment_for_sale_in_gulberg_iii-52369098-20338-1.html                                                                                                                1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_beautiful_residential_apartment_on_main_mm_alam_road_swiss_mall-53884121-19464-1.html                                                                                                                         1
https://www.zameen.com/Property/gulberg_gulberg_3_luxury_furnished_apartment_for_sale-53453887-3824-1.html                                                                                                                                                                    1
https://www.zameen.com/Property/gulberg_gulberg_3_book_your_apartment_with_39_lac_and_get_15_rental_in_gulberg_3-50631787-3824-1.html                                                                                                                                         1
https://www.zameen.com/Property/gulberg_3_gulberg_3_-_block_l_440_square_feet_flats_for_buy_in_indigo_heights_lahore-47478404-3842-1.html                                                                                                                                     1
https://www.zameen.com/Property/gulberg_mm_alam_road_annual_rental_12_in_gulberg_limited_opportunity-52978451-3850-1.html                                                                                                                                                     1
https://www.zameen.com/Property/mm_alam_road_swiss_mall_gulberg_12_annual_cash_back_on_hotel_apartments-_swiss_mall_-_mm_alam_road_residential_apartments_also_available-53145440-19464-1.html                                                                                1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_12_cash_back_guaranteed_cbd_zameen_eon_redefining_luxury_living_in_lahore-53150087-21580-1.html                                                                                                      1
https://www.zameen.com/Property/gulberg_main_boulevard_gulberg_corporate_offices_service_residential_apartments_available_at_tallest_building_of_punjab_in_cbd_gulberg_zameen_arx-53153794-3852-1.html                                                                        1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_tallest_building_of_punjab_in_cbd_gulberg_zameen_arx_near_kalma_chowk-53153561-21580-1.html                                                                                                          1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_zameen_arx_tallest_building_in_cbd_gulberg_corporate_office_service_apartment_penthouse_available_with_infinity_pool_on_30th_floor-53153675-21580-1.html                                             1
https://www.zameen.com/Property/raiwind_road_amanah_residential_towers_highly-coveted_538_square_feet_flat_is_available_in_amanah_residential_towers_for_sale-53965659-22312-1.html                                                                                           1
https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_476_square_feet_flat_in_al-kabir_town_-_phase_2_best_option-53583277-11704-1.html                                                                                                                       1
https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_book_your_apartment_on_the_prime_location_of_lahore_main_raiwind_road_1_min_away_ring_road-53291921-11704-1.html                                                                                        1
https://www.zameen.com/Property/etihad_town_etihad_town_phase_1_looking_for_a_flat_in_lahore-53396079-16882-1.html                                                                                                                                                            1
https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_downtown_luxury_apartment_available-53735444-21978-1.html                                                                                                                                                       1
https://www.zameen.com/Property/etihad_town_etihad_town_phase_1_1_bed_studio_haram_smart_tower_available_for_sale_on_easy_installment_etihad_town_lahore_phase_1-52428994-16882-1.html                                                                                        1
https://www.zameen.com/Property/dha_phase_4_goldcrest_mall_residency_tallest_building_in_punjab_service_residential_apartments_available_with_15_guaranteed_cash_back_for_3_years-53153962-9966-1.html                                                                        1
https://www.zameen.com/Property/dha_defence_defence_raya_splendid_1-bed_apartment_with_12_annual_cashback_returns_near_defence_raya_dha_lahore-53301644-8172-1.html                                                                                                           1
https://www.zameen.com/Property/bahria_orchard_bahria_orchard_phase_1_smart_studio_living_in_prime_bahria_orchard_location_low_entry_cost_with_easy_payment_plan_madina_mall_residency_lahore-53739406-8235-1.html                                                            1
https://www.zameen.com/Property/main_canal_bank_road_the_spring_apartment_homes_apartment_is_for_sale_facing_central_courtyard_on_6th_floor-52488445-10099-1.html                                                                                                             1
https://www.zameen.com/Property/lahore_main_canal_bank_road_865_square_feet_modern_2_bed_apartment_available_in_izmir_executives_prime_location_izmir_town-53926781-431-1.html                                                                                                1
https://www.zameen.com/Property/lahore_main_canal_bank_road_395_sq_ft_apartment_for_sale_in_izmir_executives_izmir_town_lahore-53926777-431-1.html                                                                                                                            1
https://www.zameen.com/Property/lahore_main_canal_bank_road_ideal_family_apartment_for_sale_500_sq_ft_apartment_in_izmir_executives_lahore-53926779-431-1.html                                                                                                                1
https://www.zameen.com/Property/johar_town_johar_town_phase_2_377_sqft_brand_new_luxury_flat_available_for_installment_in_johar_town_near_emporium_mall_trade_center_lhr-53795390-3961-1.html                                                                                 1
https://www.zameen.com/Property/model_town_model_town_link_road_become_owner_of_your_flat_today_which_is_centrally_located_in_model_town_link_road_in_lahore-53803646-3086-1.html                                                                                             1
https://www.zameen.com/Property/lahore_model_town_apartment_for_sale_on_main_model_town_link_rd-53963102-8-1.html                                                                                                                                                             1
https://www.zameen.com/Property/lahore_model_town_book_your_loft_apartment_in_amanah_mall_with_50_down_payment-53493089-8-1.html                                                                                                                                              1
https://www.zameen.com/Property/model_town_model_town_link_road_premium_718_square_feet_flat_is_available_for_sale_in_lahore-53802586-3086-1.html                                                                                                                             1
https://www.zameen.com/Property/lahore_bahria_nasheman_studio_appartment_for_sale_at_the_hot_location_of_bahria_nasheman_lahore-53925661-4510-1.html                                                                                                                          1
https://www.zameen.com/Property/lahore_bahria_nasheman_2bed_apartments_available_for_sale_at_the_hot_location_of_bahria_nasheman_lahore-53925728-4510-1.html                                                                                                                  1
https://www.zameen.com/Property/lahore_izmir_town_395_sq_ft_apartment_for_sale_in_izmir_executives_izmir_town_lahore-53919646-483-1.html                                                                                                                                      1
https://www.zameen.com/Property/lahore_izmir_town_studio_available_at_a_good_price_hot_location-53804310-483-1.html                                                                                                                                                           1
https://www.zameen.com/Property/paragon_city_paragon_city_-_orchard_block_spacious_flat_is_available_in_paragon_city_-_orchard_block_for_sale-53919961-4113-1.html                                                                                                            1
https://www.zameen.com/Property/garden_town_garden_town_-_sher_shah_block_luxury_apartment_serviced_residential_luxury_on_installments_ideal_for_overseas_pakistanis_easy_installments_best_investment_opportunity_apartment_for_sale_on_installments-52830734-1537-1.html    1
https://www.zameen.com/Property/lahore_cooper_road_hotel_apartment_ramada_for_sale-53325431-12238-1.html                                                                                                                                                                      1
https://www.zameen.com/Property/jubilee_town_jubilee_town_-_block_a_canal_view_residencia_apartment_building-50953386-3985-1.html                                                                                                                                             1
https://www.zameen.com/Property/punjab_university_employees_society_punjab_university_society_phase_2_union_town_lahore_1000_sq_ft_family_townhouse_on_flexible_2_5_years_installments-53947999-12804-1.html                                                                  1
https://www.zameen.com/Property/lahore_maulana_shaukat_ali_road_double_balcony_flat_available_for_sale_in_madina_heights_maulana_shoukat_ali_road-53151154-9866-1.html                                                                                                        1
https://www.zameen.com/Property/lahore_maulana_shaukat_ali_road_apartment_available_for_sale_in_madina_heights_maulana_shoukat_ali_road-53633226-9866-1.html                                                                                                                  1
Name: count, dtype: int64

In [68]:
import re
import numpy as np

def bedrooms_from_link(s):
    if pd.isna(s):
        return np.nan
    s = s.lower()
    if "studio" in s:
        return 0
    # skip ranges like 1_2_bed
    if re.search(r"\b\d+[_-]\d+\s*bed", s):
        return np.nan
    m = re.search(r"\b(\d+)\s*[-_ ]?(?:bed|bedroom|beds)\b", s)
    return int(m.group(1)) if m else np.nan

missing = df["bedrooms"].isna()
df.loc[missing, "bedrooms"] = df.loc[missing, "link"].apply(bedrooms_from_link)

df["bedrooms"].isna().sum()

np.int64(52)

In [69]:
df["bedrooms"].isna().sum()

np.int64(52)

In [70]:
df.shape

(3034, 26)

In [77]:
df[df['bedrooms'].isnull()]['link'].value_counts()

link
https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_b_prime_location_apartment_available_for_sale_in_bahria_town_lahore-53781563-1772-1.html                         1
https://www.zameen.com/Property/bahria_town_sector_e_bahria_town_-_nishtar_block_food_court_bahria_town_lahore-53760506-1806-1.html                                               1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_1-bed_furnished_apartment_for_sale_cbd_lahore-52901360-21580-1.html                                      1
https://www.zameen.com/Property/main_boulevard_gulberg_cbd_punjab_pcbdda_1-bed_furnished_apartment_for_sale_cbd_lahore-53238662-21580-1.html                                      1
https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_476_square_feet_flat_in_al-kabir_town_-_phase_2_best_option-53583277-11704-1.html                           1
https://www.zameen.com/Property/lahore_main_canal_bank_road_865_square_feet_modern_2_bed_apartment_available_in_izmir_executives_prime_location_izmir_town-53926781-431-1.html    1
https://www.zameen.com/Property/lahore_main_canal_bank_road_395_sq_ft_apartment_for_sale_in_izmir_executives_izmir_town_lahore-53926777-431-1.html                                1
https://www.zameen.com/Property/lahore_main_canal_bank_road_ideal_family_apartment_for_sale_500_sq_ft_apartment_in_izmir_executives_lahore-53926779-431-1.html                    1
https://www.zameen.com/Property/lahore_model_town_book_your_loft_apartment_in_amanah_mall_with_50_down_payment-53493089-8-1.html                                                  1
https://www.zameen.com/Property/lahore_bahria_nasheman_2bed_apartments_available_for_sale_at_the_hot_location_of_bahria_nasheman_lahore-53925728-4510-1.html                      1
https://www.zameen.com/Property/paragon_city_paragon_city_-_orchard_block_spacious_flat_is_available_in_paragon_city_-_orchard_block_for_sale-53919961-4113-1.html                1
Name: count, dtype: int64

In [72]:
df["bedrooms"] = df["bedrooms"].fillna(df["baths"])

In [ ]:
df.isn

,society,bedrooms,baths,link,floors_in_building,price,area,area_sqft,servant_quarters,kitchens,store_rooms,price_per_sqft,drawing_room,dining_room,lounge_or_sitting_room,laundry_room,study_room,prayer_room,powder_room,gym,steam_room,other_rooms,luxury_score,furnishing_score,floor,agePossession
0,Askari,4.0,4.0,https://www.zameen.com/Property/askari_askari_...,9.0,4.55,12.0,3264.0,1.0,1.0,1.0,13939.950980,1,1,1,1,1,1,1,0,0,0,135.0,37,3,New Property
1,Askari,4.0,5.0,https://www.zameen.com/Property/askari_10_aska...,10.0,4.50,12.2,3318.4,1.0,1.0,NaN,13560.752170,1,1,0,0,1,1,0,0,0,1,150.0,31,3,New Property
2,Askari,3.0,4.0,https://www.zameen.com/Property/askari_11_aska...,NaN,3.55,10.0,2720.0,1.0,1.0,1.0,13051.470588,1,1,1,1,1,1,1,1,1,1,156.0,49,NaN,New Property
3,Askari,4.0,4.0,https://www.zameen.com/Property/askari_askari_...,NaN,4.45,7.6,2067.2,1.0,2.0,1.0,21526.702786,1,1,0,0,1,0,0,0,0,1,125.0,18,NaN,New Property
4,Askari,4.0,5.0,https://www.zameen.com/Property/askari_10_aska...,10.0,4.65,12.2,3318.4,1.0,1.0,1.0,14012.777242,1,1,0,0,1,1,0,0,0,1,100.0,18,3,New Property
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3029,New Samanabad,2.0,1.0,https://www.zameen.com/Property/lahore_new_sam...,10.0,0.40,2.0,544.0,NaN,NaN,NaN,7352.941176,0,1,0,0,0,0,0,0,0,1,132.0,31,3,New Property
3030,Multan Road,2.0,2.0,https://www.zameen.com/Property/multan_road_ya...,NaN,0.45,2.5,680.0,NaN,NaN,NaN,6617.647059,0,0,0,0,0,0,0,0,0,0,2.0,0,NaN,Undefined
3031,Cantt,3.0,4.0,https://www.zameen.com/Property/aziz_bhatti_ro...,5.0,4.30,11.6,3155.2,NaN,NaN,NaN,13628.296146,1,1,1,1,1,1,1,1,1,1,177.0,49,8,Relatively New
3032,Revenue Society,2.0,2.0,https://www.zameen.com/Property/revenue_societ...,5.0,1.05,2.9,788.8,NaN,NaN,NaN,13311.359026,1,1,1,1,0,1,1,1,1,1,151.0,39,3,Relatively New
3033,Mason Road,2.0,2.0,https://www.zameen.com/Property/lahore_mason_r...,NaN,1.60,4.4,1196.8,NaN,NaN,NaN,13368.983957,1,1,1,1,1,1,1,1,1,1,147.0,49,1,Relatively New

In [78]:
df['bedrooms'].describe()

count    3023.000000
mean        2.092292
std         1.072064
min         0.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         9.000000
Name: bedrooms, dtype: float64

In [85]:
mean_bed = df["bedrooms"].mean()
df["bedrooms"] = df["bedrooms"].fillna(mean_bed)

In [86]:
df.isnull().sum()

society                      0
bedrooms                     0
baths                       29
link                         0
floors_in_building        1409
price                        0
area                         0
area_sqft                    0
servant_quarters          1354
kitchens                   738
store_rooms               1322
price_per_sqft               0
drawing_room                 0
dining_room                  0
lounge_or_sitting_room       0
laundry_room                 0
study_room                   0
prayer_room                  0
powder_room                  0
gym                          0
steam_room                   0
other_rooms                  0
luxury_score                 0
furnishing_score             0
floor                     1108
agePossession                0
dtype: int64

In [ ]:
df['baths'].describe()

count    3005.000000
mean        2.303827
std         1.344913
min         1.000000
25%         1.000000
50%         2.000000
75%         3.000000
max         7.000000
Name: baths, dtype: float64

In [89]:
df["baths"] = df["baths"].fillna(df["baths"].median())

In [91]:
df.isnull().sum()

society                      0
bedrooms                     0
baths                        0
link                         0
floors_in_building        1409
price                        0
area                         0
area_sqft                    0
servant_quarters          1354
kitchens                   738
store_rooms               1322
price_per_sqft               0
drawing_room                 0
dining_room                  0
lounge_or_sitting_room       0
laundry_room                 0
study_room                   0
prayer_room                  0
powder_room                  0
gym                          0
steam_room                   0
other_rooms                  0
luxury_score                 0
furnishing_score             0
floor                     1108
agePossession                0
dtype: int64

In [92]:
df['floors_in_building'].describe()

count    1625.000000
mean       11.858462
std        86.578353
min         1.000000
25%         4.000000
50%         8.000000
75%        10.000000
max      2021.000000
Name: floors_in_building, dtype: float64

In [93]:
df["floors_in_building"] = pd.to_numeric(df["floors_in_building"], errors="coerce")
df.loc[df["floors_in_building"] > 60, "floors_in_building"] = np.nan  # cap obvious errors
df["floors_in_building"] = df["floors_in_building"].fillna(df["floors_in_building"].median())

In [94]:
df.isnull().sum()

society                      0
bedrooms                     0
baths                        0
link                         0
floors_in_building           0
price                        0
area                         0
area_sqft                    0
servant_quarters          1354
kitchens                   738
store_rooms               1322
price_per_sqft               0
drawing_room                 0
dining_room                  0
lounge_or_sitting_room       0
laundry_room                 0
study_room                   0
prayer_room                  0
powder_room                  0
gym                          0
steam_room                   0
other_rooms                  0
luxury_score                 0
furnishing_score             0
floor                     1108
agePossession                0
dtype: int64

In [98]:
df['floor'].describe()

count    1361.000000
mean        6.164585
std        54.781633
min         0.000000
25%         2.000000
50%         3.000000
75%         6.000000
max      2018.000000
Name: floor, dtype: float64

In [97]:
df["floor"] = (
    df["floor"]
    .replace("TRUE", np.nan)
    .astype(str)
    .str.extract(r"(\d+)")
    .astype(float)
)

In [99]:
df["floor"] = pd.to_numeric(df["floor"], errors="coerce")
df.loc[(df["floor"] < 0) | (df["floor"] > 60), "floor"] = np.nan  # adjust 60 if you want
# df["floor"] = df["floor"].fillna(df["floor"].median())

In [100]:
df['floor'].describe()

count    1360.000000
mean        4.685294
std         4.771397
min         0.000000
25%         2.000000
50%         3.000000
75%         6.000000
max        37.000000
Name: floor, dtype: float64

In [101]:
df["floor"] = df["floor"].fillna(df["floor"].median())

In [102]:
df.isnull().sum()

society                      0
bedrooms                     0
baths                        0
link                         0
floors_in_building           0
price                        0
area                         0
area_sqft                    0
servant_quarters          1354
kitchens                   738
store_rooms               1322
price_per_sqft               0
drawing_room                 0
dining_room                  0
lounge_or_sitting_room       0
laundry_room                 0
study_room                   0
prayer_room                  0
powder_room                  0
gym                          0
steam_room                   0
other_rooms                  0
luxury_score                 0
furnishing_score             0
floor                        0
agePossession                0
dtype: int64

In [103]:
for c in ["servant_quarters", "kitchens", "store_rooms"]:
    df[c] = pd.to_numeric(df[c], errors="coerce")

df["servant_quarters"] = df["servant_quarters"].fillna(0)
df["store_rooms"] = df["store_rooms"].fillna(0)
df["kitchens"] = df["kitchens"].fillna(1)  # or df["kitchens"].median()

In [104]:
df.shape

(3034, 26)

In [105]:
df.isnull().sum()

society                   0
bedrooms                  0
baths                     0
link                      0
floors_in_building        0
price                     0
area                      0
area_sqft                 0
servant_quarters          0
kitchens                  0
store_rooms               0
price_per_sqft            0
drawing_room              0
dining_room               0
lounge_or_sitting_room    0
laundry_room              0
study_room                0
prayer_room               0
powder_room               0
gym                       0
steam_room                0
other_rooms               0
luxury_score              0
furnishing_score          0
floor                     0
agePossession             0
dtype: int64

In [106]:
df.to_csv("flats_missing_val.csv",index=False)