In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [51]:
import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)

In [2]:
df=pd.read_csv("lahore_houses_final.csv")

In [3]:
df.shape

(21220, 67)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21220 entries, 0 to 21219
Data columns (total 67 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Property ID                                      21220 non-null  int64
 1   Society                                          21220 non-null  object
 2   Society Link                                     21220 non-null  object
 3   Name                                             21220 non-null  object
 4   Page Title                                       21220 non-null  object
 5   Price                                            21219 non-null  object
 6   Area                                             21219 non-null  object
 7   Bedrooms                                         20889 non-null  float64
 8   Baths                                            20755 non-null  float64
 9   Floor Number                                     0 non-null      float64
 10  Total Floors                                     0 non-null      float64
 11  Built Year                                       16470 non-null  object
 12  Address                                          21220 non-null  object
 13  Description                                      21219 non-null  object
 14  Features                                         20499 non-null  object
 15  Nearby Locations and Other Facilities            19233 non-null  object
 16  Rooms                                            21220 non-null  object
 17  Other Rooms                                      19037 non-null  object
 18  Link                                             21220 non-null  object
 19  Built in year                                    16470 non-null  object
 20  Parking Spaces                                   18218 non-null  object
 21  Double Glazed Windows                            17311 non-null  object
 22  Central Air Conditioning                         16230 non-null  object
 23  Central Heating                                  15933 non-null  object
 24  Flooring                                         18505 non-null  object
 25  Electricity Backup                               17529 non-null  object
 26  Waste Disposal                                   16507 non-null  object
 27  Floors                                           15946 non-null  object
 28  Other Main Features                              15580 non-null  object
 29  Furnished                                        11690 non-null  object
 30  Broadband Internet Access                        17464 non-null  object
 31  Satellite or Cable TV Ready                      16949 non-null  object
 32  Intercom                                         15600 non-null  object
 33  Other Business and Communication Facilities      13368 non-null  object
 34  Community Lawn or Garden                         16975 non-null  object
 35  Community Swimming Pool                          15227 non-null  object
 36  Community Gym                                    16324 non-null  object
 37  First Aid or Medical Centre                      16695 non-null  object
 38  Day Care Centre                                  16465 non-null  object
 39  Kids Play Area                                   17069 non-null  object
 40  Barbeque Area                                    16661 non-null  object
 41  Mosque                                           17345 non-null  object
 42  Community Centre                                 16432 non-null  object
 43  Other Community Facilities                       13087 non-null  object
 44  Lawn or Garden                                   14418 non-null  object
 45  Swimming Pool                                    10357 non-null  object
 46  Sauna                                            13255 non-null  object
 47  Jacuzzi                                          13734 non-null  object
 48  Other Healthcare and Recreation Facilities       12435 non-null  object
 49  Nearby Schools                                   19143 non-null  object
 50  Nearby Hospitals                                 19138 non-null  object
 51  Nearby Shopping Malls                            19102 non-null  object
 52  Nearby Restaurants                               19076 non-null  object
 53  Distance From Airport (kms)                      17916 non-null  object
 54  Nearby Public Transport Service                  18618 non-null  object
 55  Other Nearby Places                              17967 non-null  object
 56  Maintenance Staff                                14283 non-null  object
 57  Security Staff                                   17313 non-null  object
 58  Facilities for Disabled                          12509 non-null  object
 59  Other Facilities                                 14728 non-null  object
 60  Section - Main Features                          19398 non-null  object
 61  Section - Rooms                                  19186 non-null  object
 62  Section - Business and Communication             17669 non-null  object
 63  Section - Community Features                     17615 non-null  object
 64  Section - Healthcare Recreational                16376 non-null  object
 65  Section - Nearby Locations and Other Facilities  19233 non-null  object
 66  Section - Other Facilities                       17382 non-null  object
dtypes: float64(4), int64(1), object(62)
memory usage: 10.8+ MB

In [5]:
# always drop unnamed columns
unnamed = [c for c in df.columns if c.startswith("Unnamed")]
df = df.drop(columns=unnamed)

# drop columns with >50% missing
thresh = len(df) * 0.50
drop_50 = df.columns[df.isna().sum() > thresh]
df = df.drop(columns=drop_50)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21220 entries, 0 to 21219
Data columns (total 64 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Property ID                                      21220 non-null  int64
 1   Society                                          21220 non-null  object
 2   Society Link                                     21220 non-null  object
 3   Name                                             21220 non-null  object
 4   Page Title                                       21220 non-null  object
 5   Price                                            21219 non-null  object
 6   Area                                             21219 non-null  object
 7   Bedrooms                                         20889 non-null  float64
 8   Baths                                            20755 non-null  float64
 9   Built Year                                       16470 non-null  object
 10  Address                                          21220 non-null  object
 11  Description                                      21219 non-null  object
 12  Features                                         20499 non-null  object
 13  Nearby Locations and Other Facilities            19233 non-null  object
 14  Rooms                                            21220 non-null  object
 15  Other Rooms                                      19037 non-null  object
 16  Link                                             21220 non-null  object
 17  Built in year                                    16470 non-null  object
 18  Parking Spaces                                   18218 non-null  object
 19  Double Glazed Windows                            17311 non-null  object
 20  Central Air Conditioning                         16230 non-null  object
 21  Central Heating                                  15933 non-null  object
 22  Flooring                                         18505 non-null  object
 23  Electricity Backup                               17529 non-null  object
 24  Waste Disposal                                   16507 non-null  object
 25  Floors                                           15946 non-null  object
 26  Other Main Features                              15580 non-null  object
 27  Furnished                                        11690 non-null  object
 28  Broadband Internet Access                        17464 non-null  object
 29  Satellite or Cable TV Ready                      16949 non-null  object
 30  Intercom                                         15600 non-null  object
 31  Other Business and Communication Facilities      13368 non-null  object
 32  Community Lawn or Garden                         16975 non-null  object
 33  Community Swimming Pool                          15227 non-null  object
 34  Community Gym                                    16324 non-null  object
 35  First Aid or Medical Centre                      16695 non-null  object
 36  Day Care Centre                                  16465 non-null  object
 37  Kids Play Area                                   17069 non-null  object
 38  Barbeque Area                                    16661 non-null  object
 39  Mosque                                           17345 non-null  object
 40  Community Centre                                 16432 non-null  object
 41  Other Community Facilities                       13087 non-null  object
 42  Lawn or Garden                                   14418 non-null  object
 43  Sauna                                            13255 non-null  object
 44  Jacuzzi                                          13734 non-null  object
 45  Other Healthcare and Recreation Facilities       12435 non-null  object
 46  Nearby Schools                                   19143 non-null  object
 47  Nearby Hospitals                                 19138 non-null  object
 48  Nearby Shopping Malls                            19102 non-null  object
 49  Nearby Restaurants                               19076 non-null  object
 50  Distance From Airport (kms)                      17916 non-null  object
 51  Nearby Public Transport Service                  18618 non-null  object
 52  Other Nearby Places                              17967 non-null  object
 53  Maintenance Staff                                14283 non-null  object
 54  Security Staff                                   17313 non-null  object
 55  Facilities for Disabled                          12509 non-null  object
 56  Other Facilities                                 14728 non-null  object
 57  Section - Main Features                          19398 non-null  object
 58  Section - Rooms                                  19186 non-null  object
 59  Section - Business and Communication             17669 non-null  object
 60  Section - Community Features                     17615 non-null  object
 61  Section - Healthcare Recreational                16376 non-null  object
 62  Section - Nearby Locations and Other Facilities  19233 non-null  object
 63  Section - Other Facilities                       17382 non-null  object
dtypes: float64(2), int64(1), object(61)
memory usage: 10.4+ MB

In [15]:
dict(df['Features'].value_counts())

{'Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff | Other Facilities': np.int64(464),
 'Built in year : 2025 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(388),
 'Built in year : 2025 | Parking Spaces : 1 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(370),
 'Built in year : 2025 | Parking Spaces : 4 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(334),
 'Built in year : 2025 | Parking Spaces : 2 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(304),
 'Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished': np.int64(289),
 'Built in year : 2026 | Parking Spaces : 4 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(217),
 'Built in year : 2024 | Parking Spaces : 4 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(176),
 'Built in year : 2024 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(152),
 'Built in year : 2026 | Parking Spaces : 1 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(151),
 'Built in year : 2024 | Parking Spaces : 2 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(125),
 'Built in year : 2026 | Parking Spaces : 2 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(119),
 'Built in year : 2025 | Parking Spaces : 5 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(111),
 'Built in year : 2024 | Parking Spaces : 1 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(111),
 'Built in year : 2026 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(104),
 'Built in year : 2025 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 3 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(103),
 'Built in year | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(101),
 'Built in year | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(97),
 'Built in year : 2025 | Parking Spaces : 3 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(96),
 'Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Sauna | Jacuzzi | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled': np.int64(92),
 'Built in year : 2025 | Parking Spaces : 4 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 3 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(87),
 'Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff': np.int64(76),
 'Built in year : 2025 | Parking Spaces : 1 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(74),
 'Built in year : 2023 | Parking Spaces : 4 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(74),
 'Built in year : 2023 | Parking Spaces : 2 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities': np.int64(69),
 'Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants': np.int64(60),

In [25]:
df['Features'].dropna().sample(5).tolist()

['Built in year : 2025 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Lawn or Garden | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff',
 'Built in year : 2013 | Parking Spaces : 2 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities',
 'Built in year | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities',
 'Double Glazed Windows | Broadband Internet Access | Satellite or Cable TV Ready | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff | Other Facilities',
 'Built in year : 2022 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff | Other Facilities']

In [26]:
import re
import numpy as np
import pandas as pd

def extract_floor_info(s):
    if pd.isna(s):
        return pd.Series([np.nan, np.nan])
    
    s = str(s).lower()

    # --- Floor Number (houses case) ---
    floor_match = re.search(r'floors?\s*:\s*(\d+)', s)
    floor_number = float(floor_match.group(1)) if floor_match else np.nan

    # --- Total Floors (not present in your sample → keep NaN) ---
    total_match = re.search(r'out of\s*(\d+)', s)
    total_floors = float(total_match.group(1)) if total_match else np.nan

    return pd.Series([floor_number, total_floors])


df[['floor_number_feat', 'total_floors_feat']] = df['Features'].apply(extract_floor_info)

In [27]:
[c for c in df.columns if 'floor' in c.lower()]

['Flooring', 'Floors', 'floor_number_feat', 'total_floors_feat']

In [28]:
df['Flooring'].value_counts()

Flooring
True    18505
Name: count, dtype: int64

In [29]:
df['Floors'].value_counts()

Floors
2       11421
3        2024
True     1659
1         556
02         84
4          73
2.5        40
1.5        12
01          9
03          9
5           7
2025        5
2026        5
12          4
6           4
1.25        3
23          3
9           2
28          2
2.          2
2024        2
14          2
7           2
123         1
33          1
41          1
0           1
32          1
27          1
19          1
18          1
2010        1
2015        1
2014        1
2018        1
2009        1
26          1
10          1
2023        1
Name: count, dtype: int64

In [30]:
df['floor_number_feat'].value_counts()

floor_number_feat
2.0       11547
3.0        2033
1.0         580
4.0          73
5.0           7
2025.0        5
2026.0        5
6.0           4
12.0          4
23.0          3
28.0          2
7.0           2
2024.0        2
14.0          2
9.0           2
123.0         1
33.0          1
41.0          1
0.0           1
32.0          1
27.0          1
19.0          1
18.0          1
2010.0        1
2015.0        1
2014.0        1
2018.0        1
2009.0        1
26.0          1
10.0          1
2023.0        1
Name: count, dtype: int64

In [31]:
df['total_floors_feat'].value_counts()

Series([], Name: count, dtype: int64)

In [33]:
df['Floors'].isna().sum()

np.int64(5274)

In [35]:
df['Floors'] = df['Floors'].fillna(df['floor_number_feat'])

In [36]:
df['Floors'].isna().sum()

np.int64(5274)

In [37]:
df.drop(columns=['floor_number_feat', 'total_floors_feat'], inplace=True)

In [38]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Area', 'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description',
       'Features', 'Nearby Locations and Other Facilities', 'Rooms',
       'Other Rooms', 'Link', 'Built in year', 'Parking Spaces',
       'Double Glazed Windows', 'Central Air Conditioning', 'Central Heating',
       'Flooring', 'Electricity Backup', 'Waste Disposal', 'Floors',
       'Other Main Features', 'Furnished', 'Broadband Internet Access',
       'Satellite or Cable TV Ready', 'Intercom',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities'],
      dtype='object')

In [44]:
df['Price'].isnull().sum()

np.int64(1)

In [45]:
df.shape

(21220, 64)

In [48]:
df.dropna(subset=['Price'], inplace=True)

In [49]:
df.shape

(21219, 64)

In [52]:
df['Price'].value_counts()

Price
PKR 2.1 Crore      392
PKR 3.5 Crore      343
PKR 2.25 Crore     326
PKR 2.3 Crore      326
PKR 6.5 Crore      314
PKR 2.5 Crore      305
PKR 2.4 Crore      281
PKR 2.2 Crore      277
PKR 2 Crore        254
PKR 1.65 Crore     250
PKR 4.5 Crore      250
PKR 1.35 Crore     248
PKR 3 Crore        228
PKR 2.35 Crore     223
PKR 1.9 Crore      216
PKR 2.6 Crore      213
PKR 2.15 Crore     213
PKR 8.5 Crore      213
PKR 5.5 Crore      210
PKR 7.5 Crore      209
PKR 4 Crore        207
PKR 1.8 Crore      205
PKR 1.75 Crore     204
PKR 1.85 Crore     203
PKR 9.5 Crore      192
PKR 1.5 Crore      190
PKR 1.6 Crore      189
PKR 1.7 Crore      183
PKR 1.25 Crore     182
PKR 1.3 Crore      180
PKR 2.45 Crore     176
PKR 4.25 Crore     176
PKR 3.25 Crore     174
PKR 1.95 Crore     170
PKR 3.1 Crore      168
PKR 2.7 Crore      167
PKR 2.75 Crore     160
PKR 1.55 Crore     152
PKR 2.8 Crore      151
PKR 1.4 Crore      151
PKR 2.9 Crore      143
PKR 6 Crore        143
PKR 5 Crore        138
PKR 8 Crore        137
PKR 2.65 Crore     135
PKR 8.75 Crore     134
PKR 3.8 Crore      133
PKR 10 Crore       133
PKR 7 Crore        132
PKR 11 Crore       132
PKR 9 Crore        129
PKR 10.5 Crore     128
PKR 3.9 Crore      127
PKR 4.1 Crore      121
PKR 3.15 Crore     121
PKR 3.2 Crore      117
PKR 2.85 Crore     114
PKR 1.2 Crore      114
PKR 5.25 Crore     112
PKR 4.75 Crore     111
PKR 8.25 Crore     111
PKR 3.3 Crore      111
PKR 6.75 Crore     109
PKR 6.25 Crore     107
PKR 3.75 Crore     106
PKR 7.25 Crore     104
PKR 3.6 Crore      102
PKR 9.25 Crore      98
PKR 12 Crore        94
PKR 1.15 Crore      93
PKR 1.45 Crore      92
PKR 3.7 Crore       90
PKR 2.55 Crore      90
PKR 11.5 Crore      90
PKR 1.1 Crore       88
PKR 2.05 Crore      88
PKR 15 Crore        87
PKR 3.35 Crore      85
PKR 7.75 Crore      85
PKR 14 Crore        85
PKR 2.95 Crore      85
PKR 3.95 Crore      77
PKR 16 Crore        77
PKR 12.5 Crore      76
PKR 3.85 Crore      75
PKR 4.9 Crore       73
PKR 4.15 Crore      73
PKR 9.75 Crore      72
PKR 3.4 Crore       72
PKR 13 Crore        71
PKR 4.3 Crore       70
PKR 5.75 Crore      69
PKR 4.8 Crore       68
PKR 4.7 Crore       68
PKR 4.2 Crore       66
PKR 13.5 Crore      66
PKR 18 Crore        64
PKR 4.6 Crore       62
PKR 95 Lakh         62
PKR 14.5 Crore      62
PKR 3.45 Crore      62
PKR 4.95 Crore      61
PKR 90 Lakh         61
PKR 25 Crore        60
PKR 4.4 Crore       60
PKR 10.25 Crore     57
PKR 5.9 Crore       57
PKR 3.65 Crore      56
PKR 4.35 Crore      55
PKR 5.1 Crore       54
PKR 85 Lakh         53
PKR 5.6 Crore       53
PKR 5.7 Crore       49
PKR 1.05 Crore      48
PKR 5.2 Crore       43
PKR 20 Crore        43
PKR 4.65 Crore      43
PKR 5.8 Crore       43
PKR 5.95 Crore      42
PKR 22 Crore        42
PKR 75 Lakh         41
PKR 8.99 Crore      41
PKR 8.9 Crore       41
PKR 11.75 Crore     40
PKR 8.95 Crore      40
PKR 6.2 Crore       40
PKR 7.1 Crore       39
PKR 6.7 Crore       38
PKR 80 Lakh         38
PKR 18.5 Crore      38
PKR 7.95 Crore      38
PKR 6.95 Crore      37
PKR 17 Crore        37
PKR 6.45 Crore      37
PKR 5.3 Crore       37
PKR 15.5 Crore      37
PKR 11.25 Crore     36
PKR 7.99 Crore      36
PKR 5.4 Crore       35
PKR 6.9 Crore       35
PKR 6.6 Crore       35
PKR 65 Lakh         35
PKR 6.99 Crore      35
PKR 4.85 Crore      33
PKR 6.8 Crore       33
PKR 19 Crore        33
PKR 7.15 Crore      32
PKR 5.35 Crore      32
PKR 14.75 Crore     32
PKR 3.55 Crore      32
PKR 5.15 Crore      31
PKR 9.9 Crore       31
PKR 6.3 Crore       30
PKR 5.45 Crore      30
PKR 4.45 Crore      30
PKR 7.35 Crore      30
PKR 8.35 Crore      29
PKR 32 Crore        28
PKR 12.75 Crore     28
PKR 24 Crore        28
PKR 30 Crore        28
PKR 5.85 Crore      28
PKR 9.6 Crore       28
PKR 6.85 Crore      27
PKR 10.75 Crore     27
PKR 19.5 Crore      27
PKR 16.5 Crore      27
PKR 7.65 Crore      27
PKR 6.15 Crore      26
PKR 6.1 Crore       25
PKR 6.35 Crore      25
PKR 8.15 Crore      25
PKR 11.9 Crore      25
PKR 1 Crore         25
PKR 7.9 Crore       25
PKR 7.45 Crore      24
PKR 9.1 Crore       24
PKR 8.7 Crore       23
PKR 35 Crore        23
PKR 13.75 Crore     23
PKR 3.05 Crore      23
PKR 4.55 Crore      23
PKR 17.5 Crore      22
PKR 28 Crore        22
PKR 12.25 Crore     22
PKR 8.65 Crore      22
PKR 2.99 Crore      22
PKR 23 Crore        22
PKR 6.4 Crore       22
PKR 24.5 Crore      21
PKR 8.85 Crore      21
PKR 1.28 Crore      21
PKR 27 Crore        21
PKR 9.15 Crore      21
PKR 8.2 Crore       21
PKR 9.8 Crore       21
PKR 26 Crore        21
PKR 8.8 Crore       21
PKR 5.65 Crore      20
PKR 40 Crore        20
PKR 45 Crore        20
PKR 1.18 Crore      20
PKR 5.55 Crore      20
PKR 6.65 Crore      20
PKR 7.8 Crore       20
PKR 65 Crore        19
PKR 70 Lakh         19
PKR 2.12 Crore      19
PKR 7.85 Crore      18
PKR 21 Crore        18
PKR 9.95 Crore      18
PKR 55 Crore        18
PKR 88 Lakh         18
PKR 10.9 Crore      18
PKR 9.99 Crore      18
PKR 4.99 Crore      17
PKR 11.99 Crore     17
PKR 38 Crore        17
PKR 8.1 Crore       17
PKR 7.05 Crore      17
PKR 25.5 Crore      17
PKR 1.78 Crore      17
PKR 8.45 Crore      17
PKR 55 Lakh         17
PKR 7.55 Crore      16
PKR 8.4 Crore       16
PKR 2.18 Crore      16
PKR 13.25 Crore     16
PKR 2.28 Crore      15
PKR 7.3 Crore       15
PKR 6.55 Crore      15
PKR 48 Crore        15
PKR 10.2 Crore      15
PKR 1.99 Crore      14
PKR 62 Lakh         14
PKR 5.05 Crore      14
PKR 12.99 Crore     14
PKR 1.68 Crore      14
PKR 4.05 Crore      14
PKR 12.9 Crore      13
PKR 1.22 Crore      13
PKR 1.38 Crore      13
PKR 36 Crore        13
PKR 1.58 Crore      13
PKR 33 Crore        13
PKR 27.5 Crore      13
PKR 82 Lakh         13
PKR 15.75 Crore     13
PKR 9.45 Crore      13
PKR 8.49 Crore      13
PKR 34 Crore        13
PKR 9.65 Crore      13
PKR 42 Crore        12
PKR 1.48 Crore      12
PKR 9.7 Crore       12
PKR 10.99 Crore     12
PKR 2.38 Crore      12
PKR 7.6 Crore       12
PKR 99 Lakh         12
PKR 7.2 Crore       12
PKR 8.6 Crore       12
PKR 1.12 Crore      12
PKR 7.49 Crore      12
PKR 16.25 Crore     11
PKR 32.5 Crore      11
PKR 3.99 Crore      11
PKR 1.52 Crore      11
PKR 9.35 Crore      11
PKR 18.75 Crore     11
PKR 1.59 Crore      11
PKR 5.99 Crore      11
PKR 2.49 Crore      11
PKR 39 Crore        11
PKR 21.5 Crore      11
PKR 1.82 Crore      10
PKR 98 Lakh         10
PKR 2.29 Crore      10
PKR 1.98 Crore      10
PKR 1.42 Crore      10
PKR 50 Crore        10
PKR 2.11 Crore      10
PKR 60 Lakh         10
PKR 19.75 Crore     10
PKR 28.5 Crore      10
PKR 8.32 Crore      10
PKR 1.72 Crore      10
PKR 37 Crore        10
PKR 7.4 Crore       10
PKR 1.32 Crore       9
PKR 97 Lakh          9
PKR 22.5 Crore       9
PKR 2.79 Crore       9
PKR 15.99 Crore      9
PKR 12.49 Crore      9
PKR 1.89 Crore       9
PKR 25.75 Crore      9
PKR 9.55 Crore       9
PKR 23.5 Crore       9
PKR 9.85 Crore       9
PKR 1.08 Crore       9
PKR 2.48 Crore       9
PKR 63 Lakh          8
PKR 63.5 Lakh        8
PKR 26.5 Crore       8
PKR 36.5 Crore       8
PKR 1.88 Crore       8
PKR 10.95 Crore      8
PKR 2.08 Crore       8
PKR 7.12 Crore       8
PKR 1.39 Crore       8
PKR 75 Crore         8
PKR 1.64 Crore       8
PKR 14.9 Crore       8
PKR 24.75 Crore      8
PKR 9.49 Crore       8
PKR 29 Crore         8
PKR 59 Crore         8
PKR 1.84 Crore       8
PKR 15.9 Crore       8
PKR 14.25 Crore      8
PKR 2.88 Crore       7
PKR 7.7 Crore        7
PKR 44 Crore         7
PKR 14.99 Crore      7
PKR 2.78 Crore       7
PKR 1.54 Crore       7
PKR 12.45 Crore      7
PKR 60 Crore         7
PKR 22.75 Crore      7
PKR 70 Crore         7
PKR 1.62 Crore       7
PKR 1.13 Crore       7
PKR 13.95 Crore      7
PKR 92 Lakh          7
PKR 4.49 Crore       7
PKR 9.2 Crore        7
PKR 23.75 Crore      7
PKR 45 Lakh          7
PKR 1.29 Crore       7
PKR 9.05 Crore       7
PKR 64 Lakh          7
PKR 1.53 Crore       7
PKR 7.19 Crore       6
PKR 9.3 Crore        6
PKR 2.22 Crore       6
PKR 15.25 Crore      6
PKR 11.95 Crore      6
PKR 2.27 Crore       6
PKR 1.51 Crore       6
PKR 2.19 Crore       6
PKR 29.5 Crore       6
PKR 16.99 Crore      6
PKR 3.79 Crore       6
PKR 2.39 Crore       6
PKR 1.69 Crore       6
PKR 50 Lakh          6
PKR 7.11 Crore       6
PKR 7.86 Crore       6
PKR 2.23 Crore       6
PKR 1.79 Crore       6
PKR 17.99 Crore      5
PKR 10.15 Crore      5
PKR 21.99 Crore      5
PKR 8.55 Crore       5
PKR 39.5 Crore       5
PKR 16.9 Crore       5
PKR 9.4 Crore        5
PKR 77 Lakh          5
PKR 1.96 Crore       5
PKR 2.17 Crore       5
PKR 10.65 Crore      5
PKR 93 Lakh          5
PKR 43 Crore         5
PKR 4.79 Crore       5
PKR 47 Crore         5
PKR 67 Lakh          5
PKR 8.3 Crore        5
PKR 78 Lakh          5
PKR 16.75 Crore      5
PKR 1.34 Crore       5
PKR 17.25 Crore      5
PKR 10.49 Crore      5
PKR 72 Lakh          5
PKR 10.35 Crore      5
PKR 48 Lakh          5
PKR 1.49 Crore       5
PKR 4.18 Crore       5
PKR 1.23 Crore       5
PKR 1.17 Crore       5
PKR 13.99 Crore      5
PKR 21.75 Crore      5
PKR 68 Lakh          5
PKR 4.11 Crore       5
PKR 85 Crore         5
PKR 15.95 Crore      5
PKR 3.68 Crore       5
PKR 7.32 Crore       5
PKR 7.22 Crore       5
PKR 3.29 Crore       5
PKR 1.73 Crore       5
PKR 2.34 Crore       5
PKR 11.65 Crore      5
PKR 2.42 Crore       5
PKR 1.47 Crore       5
PKR 2.32 Crore       5
PKR 6.49 Crore       5
PKR 2.36 Crore       5
PKR 2.44 Crore       5
PKR 11.15 Crore      4
PKR 8.72 Crore       4
PKR 7.29 Crore       4
PKR 6.05 Crore       4
PKR 13.65 Crore      4
PKR 1.71 Crore       4
PKR 7.38 Crore       4
PKR 22.95 Crore      4
PKR 25.99 Crore      4
PKR 12.95 Crore      4
PKR 59 Lakh          4
PKR 53 Crore         4
PKR 11.45 Crore      4
PKR 24.9 Crore       4
PKR 1.91 Crore       4
PKR 2.24 Crore       4
PKR 1.57 Crore       4
PKR 6.12 Crore       4
PKR 2.98 Crore       4
PKR 29.99 Crore      4
PKR 58 Lakh          4
PKR 6.98 Crore       4
PKR 1.06 Crore       4
PKR 10.85 Crore      4
PKR 12.35 Crore      4
PKR 1.02 Crore       4
PKR 1.07 Crore       4
PKR 1.86 Crore       4
PKR 57 Crore         4
PKR 40 Lakh          4
PKR 1.1 Arab         4
PKR 1.43 Crore       4
PKR 72.5 Lakh        4
PKR 17.75 Crore      4
PKR 52 Lakh          4
PKR 9.11 Crore       4
PKR 2.09 Crore       4
PKR 1.76 Crore       4
PKR 1.27 Crore       4
PKR 41.5 Crore       4
PKR 1.33 Crore       4
PKR 1.74 Crore       4
PKR 2.16 Crore       4
PKR 2.07 Crore       4
PKR 4.21 Crore       4
PKR 9.58 Crore       4
PKR 17.95 Crore      4
PKR 1.37 Crore       4
PKR 23.9 Crore       4
PKR 12.65 Crore      4
PKR 2.68 Crore       4
PKR 67.5 Lakh        4
PKR 10.55 Crore      4
PKR 4.98 Crore       4
PKR 6.89 Crore       4
PKR 52 Crore         4
PKR 10.8 Crore       4
PKR 2.13 Crore       4
PKR 3.49 Crore       4
PKR 9.12 Crore       4
PKR 73.5 Lakh        4
PKR 73 Lakh          4
PKR 6.78 Crore       4
PKR 9.98 Crore       3
PKR 8.79 Crore       3
PKR 51 Crore         3
PKR 8.05 Crore       3
PKR 7.78 Crore       3
PKR 1.97 Crore       3
PKR 11.2 Crore       3
PKR 2.52 Crore       3
PKR 8.12 Crore       3
PKR 23.25 Crore      3
PKR 23.99 Crore      3
PKR 16.95 Crore      3
PKR 49.5 Lakh        3
PKR 6.88 Crore       3
PKR 5.18 Crore       3
PKR 4.33 Crore       3
PKR 1.44 Crore       3
PKR 1.24 Crore       3
PKR 14.4 Crore       3
PKR 11.7 Crore       3
PKR 4.09 Crore       3
PKR 6.39 Crore       3
PKR 28.75 Crore      3
PKR 58 Crore         3
PKR 20.99 Crore      3
PKR 5.16 Crore       3
PKR 7.72 Crore       3
PKR 14.7 Crore       3
PKR 9.53 Crore       3
PKR 42.5 Crore       3
PKR 7.79 Crore       3
PKR 39.9 Crore       3
PKR 1.54 Arab        3
PKR 7.47 Crore       3
PKR 2.92 Crore       3
PKR 5.22 Crore       3
PKR 1.92 Crore       3
PKR 3.38 Crore       3
PKR 8.19 Crore       3
PKR 8.89 Crore       3
PKR 2.47 Crore       3
PKR 8.22 Crore       3
PKR 5.98 Crore       3
PKR 24.25 Crore      3
PKR 2.69 Crore       3
PKR 7.18 Crore       3
PKR 3.18 Crore       3
PKR 11.4 Crore       3
PKR 10.45 Crore      3
PKR 1.67 Crore       3
PKR 26.75 Crore      3
PKR 11.49 Crore      3
PKR 12.7 Crore       3
PKR 2.59 Crore       3
PKR 2.89 Crore       3
PKR 4.29 Crore       3
PKR 87 Lakh          3
PKR 14.95 Crore      3
PKR 34.99 Crore      3
PKR 1.19 Crore       3
PKR 13.9 Crore       3
PKR 18.9 Crore       3
PKR 7.98 Crore       3
PKR 8.38 Crore       3
PKR 83 Lakh          3
PKR 2.58 Crore       3
PKR 1.31 Crore       3
PKR 5.49 Crore       3
PKR 4.38 Crore       3
PKR 1.21 Crore       3
PKR 1.16 Crore       3
PKR 4.53 Crore       3
PKR 34.5 Crore       3
PKR 7.24 Crore       3
PKR 13.85 Crore      3
PKR 3.74 Crore       3
PKR 20.75 Crore      3
PKR 86 Lakh          3
PKR 4.19 Crore       3
PKR 48.5 Lakh        3
PKR 62.5 Lakh        3
PKR 3.98 Crore       3
PKR 26.9 Crore       3
PKR 27.65 Crore      3
PKR 69 Lakh          2
PKR 8.87 Crore       2
PKR 6.38 Crore       2
PKR 12.55 Crore      2
PKR 68.5 Lakh        2
PKR 6.22 Crore       2
PKR 4.17 Crore       2
PKR 2.41 Crore       2
PKR 53 Lakh          2
PKR 46 Lakh          2
PKR 35 Lakh          2
PKR 1.14 Crore       2
PKR 42 Lakh          2
PKR 36 Lakh          2
PKR 6.18 Crore       2
PKR 3.89 Crore       2
PKR 1.36 Crore       2
PKR 31 Crore         2
PKR 8.11 Crore       2
PKR 19.9 Crore       2
PKR 1.09 Crore       2
PKR 5.69 Crore       2
PKR 6.17 Crore       2
PKR 7.48 Crore       2
PKR 3.12 Crore       2
PKR 4.24 Crore       2
PKR 89 Lakh          2
PKR 14.14 Crore      2
PKR 46 Crore         2
PKR 97.5 Lakh        2
PKR 1.03 Crore       2
PKR 76 Lakh          2
PKR 6.69 Crore       2
PKR 1.81 Crore       2
PKR 4.08 Crore       2
PKR 5.23 Crore       2
PKR 2.67 Crore       2
PKR 9.21 Crore       2
PKR 15.45 Crore      2
PKR 5.42 Crore       2
PKR 6.74 Crore       2
PKR 6.41 Crore       2
PKR 5.78 Crore       2
PKR 1.66 Crore       2
PKR 41 Crore         2
PKR 12.8 Crore       2
PKR 24.65 Crore      2
PKR 2.94 Crore       2
PKR 8.27 Crore       2
PKR 6.28 Crore       2
PKR 8.39 Crore       2
PKR 18.99 Crore      2
PKR 26.4 Crore       2
PKR 3.48 Crore       2
PKR 1.41 Crore       2
PKR 48.5 Crore       2
PKR 24.95 Crore      2
PKR 2.74 Crore       2
PKR 7.08 Crore       2
PKR 19.25 Crore      2
PKR 26.95 Crore      2
PKR 8.86 Crore       2
PKR 13.3 Crore       2
PKR 17.86 Crore      2
PKR 8.42 Crore       2
PKR 1.46 Crore       2
PKR 4.56 Crore       2
PKR 2.62 Crore       2
PKR 1.83 Crore       2
PKR 3.82 Crore       2
PKR 1.63 Crore       2
PKR 11.85 Crore      2
PKR 4.22 Crore       2
PKR 9.18 Crore       2
PKR 7.13 Crore       2
PKR 9.24 Crore       2
PKR 6.58 Crore       2
PKR 2.37 Crore       2
PKR 3.62 Crore       2
PKR 3.78 Crore       2
PKR 3.22 Crore       2
PKR 3.42 Crore       2
PKR 9.19 Crore       2
PKR 11.6 Crore       2
PKR 7.28 Crore       2
PKR 6.31 Crore       2
PKR 4.92 Crore       2
PKR 23.65 Crore      2
PKR 2.46 Crore       2
PKR 17.8 Crore       2
PKR 29.9 Crore       2
PKR 27.99 Crore      2
PKR 6.19 Crore       2
PKR 16.35 Crore      2
PKR 4.89 Crore       2
PKR 11.8 Crore       2
PKR 2.51 Crore       2
PKR 4.82 Crore       2
PKR 11.55 Crore      2
PKR 20.5 Crore       2
PKR 4.46 Crore       2
PKR 10.18 Crore      2
PKR 10.13 Crore      2
PKR 10.1 Crore       2
PKR 4.88 Crore       2
PKR 30.5 Crore       2
PKR 90 Crore         2
PKR 80 Crore         2
PKR 32 Lakh          2
PKR 32.75 Crore      2
PKR 7.33 Crore       2
PKR 11.35 Crore      2
PKR 3.28 Crore       2
PKR 13.45 Crore      2
PKR 17.35 Crore      2
PKR 6.79 Crore       2
PKR 7.89 Crore       2
PKR 7.42 Crore       2
PKR 12.85 Crore      2
PKR 33.99 Crore      2
PKR 14.35 Crore      2
PKR 13.7 Crore       2
PKR 4.28 Crore       2
PKR 19.8 Crore       2
PKR 1.2 Arab         2
PKR 2 Arab           2
PKR 1.35 Arab        2
PKR 39.99 Crore      2
PKR 69 Crore         2
PKR 64.5 Lakh        2
PKR 7.09 Crore       2
PKR 7.21 Crore       2
PKR 5.48 Crore       2
PKR 2.03 Crore       1
PKR 26 Lakh          1
PKR 7.53 Crore       1
PKR 22.86 Crore      1
PKR 83.5 Lakh        1
PKR 58.5 Lakh        1
PKR 62.7 Lakh        1
PKR 3.96 Crore       1
PKR 71 Lakh          1
PKR 49 Lakh          1
PKR 49.8 Lakh        1
PKR 49.95 Lakh       1
PKR 39.5 Lakh        1
PKR 79.5 Lakh        1
PKR 69.48 Lakh       1
PKR 59.5 Lakh        1
PKR 24.4 Crore       1
PKR 12.1 Crore       1
PKR 18.49 Crore      1
PKR 15.2 Crore       1
PKR 8.23 Crore       1
PKR 7.57 Crore       1
PKR 2.21 Crore       1
PKR 5.41 Crore       1
PKR 4.97 Crore       1
PKR 14.05 Crore      1
PKR 11.05 Crore      1
PKR 8.08 Crore       1
PKR 7.17 Crore       1
PKR 6.33 Crore       1
PKR 26.99 Crore      1
PKR 7.56 Crore       1
PKR 81 Lakh          1
PKR 61 Lakh          1
PKR 15.65 Crore      1
PKR 8.46 Crore       1
PKR 7.71 Crore       1
PKR 20.25 Crore      1
PKR 7.16 Crore       1
PKR 8.41 Crore       1
PKR 7.68 Crore       1
PKR 12.05 Crore      1
PKR 7.62 Crore       1
PKR 4.13 Crore       1
PKR 8.76 Crore       1
PKR 7.39 Crore       1
PKR 2.02 Crore       1
PKR 19.15 Crore      1
PKR 8.62 Crore       1
PKR 9.79 Crore       1
PKR 14.85 Crore      1
PKR 10.79 Crore      1
PKR 16.2 Crore       1
PKR 40.99 Crore      1
PKR 2.14 Crore       1
PKR 3.41 Crore       1
PKR 3.54 Crore       1
PKR 7.84 Crore       1
PKR 4.32 Crore       1
PKR 10.6 Crore       1
PKR 22.25 Crore      1
PKR 38.5 Crore       1
PKR 5.94 Crore       1
PKR 8.73 Crore       1
PKR 21.65 Crore      1
PKR 7.02 Crore       1
PKR 8.69 Crore       1
PKR 7.81 Crore       1
PKR 15.8 Crore       1
PKR 4.26 Crore       1
PKR 7.67 Crore       1
PKR 13.55 Crore      1
PKR 31.75 Crore      1
PKR 2.96 Crore       1
PKR 3.43 Crore       1
PKR 44.5 Crore       1
PKR 54 Crore         1
PKR 11.11 Crore      1
PKR 38.95 Crore      1
PKR 14.55 Crore      1
PKR 6.64 Crore       1
PKR 56 Crore         1
PKR 6.42 Crore       1
PKR 4.31 Crore       1
PKR 26.25 Crore      1
PKR 35.99 Crore      1
PKR 14.58 Crore      1
PKR 23.35 Crore      1
PKR 13.35 Crore      1
PKR 10.58 Crore      1
PKR 3.94 Crore       1
PKR 4.12 Crore       1
PKR 3.21 Crore       1
PKR 47.9 Crore       1
PKR 8.92 Crore       1
PKR 5.39 Crore       1
PKR 16.1 Crore       1
PKR 6.77 Crore       1
PKR 14.33 Crore      1
PKR 5.57 Crore       1
PKR 18.35 Crore      1
PKR 27.95 Crore      1
PKR 14.86 Crore      1
PKR 6.06 Crore       1
PKR 6.21 Crore       1
PKR 15.86 Crore      1
PKR 14.49 Crore      1
PKR 5.27 Crore       1
PKR 4.72 Crore       1
PKR 29.75 Crore      1
PKR 1.56 Crore       1
PKR 8.88 Crore       1
PKR 11.33 Crore      1
PKR 6.62 Crore       1
PKR 5.12 Crore       1
PKR 6.66 Crore       1
PKR 23.95 Crore      1
PKR 19.65 Crore      1
PKR 22.65 Crore      1
PKR 31.99 Crore      1
PKR 36.99 Crore      1
PKR 36.75 Crore      1
PKR 12.59 Crore      1
PKR 2.72 Crore       1
PKR 3.03 Crore       1
PKR 6.68 Crore       1
PKR 2.04 Crore       1
PKR 9.13 Crore       1
PKR 6.81 Crore       1
PKR 33.25 Crore      1
PKR 9.22 Crore       1
PKR 7.41 Crore       1
PKR 33.5 Crore       1
PKR 27.86 Crore      1
PKR 18.15 Crore      1
PKR 18.95 Crore      1
PKR 51.9 Crore       1
PKR 17.9 Crore       1
PKR 18.25 Crore      1
PKR 8.34 Crore       1
PKR 7.36 Crore       1
PKR 7.27 Crore       1
PKR 11.98 Crore      1
PKR 15.4 Crore       1
PKR 24.99 Crore      1
PKR 24.24 Crore      1
PKR 35.95 Crore      1
PKR 8.77 Crore       1
PKR 8.21 Crore       1
PKR 3.67 Crore       1
PKR 54.99 Crore      1
PKR 7.34 Crore       1
PKR 1.11 Crore       1
PKR 5.79 Crore       1
PKR 3.09 Crore       1
PKR 1.77 Crore       1
PKR 91.7 Lakh        1
PKR 78.92 Lakh       1
PKR 55 Thousand      1
PKR 8.96 Crore       1
PKR 41.99 Crore      1
PKR 21.95 Crore      1
PKR 21.9 Crore       1
PKR 9.23 Crore       1
PKR 7.59 Crore       1
PKR 7.97 Crore       1
PKR 7.93 Crore       1
PKR 4.71 Crore       1
PKR 37.99 Crore      1
PKR 37.75 Crore      1
PKR 2.61 Crore       1
PKR 51 Lakh          1
PKR 1.04 Crore       1
PKR 13.88 Crore      1
PKR 19.35 Crore      1
PKR 9.66 Crore       1
PKR 47.5 Crore       1
PKR 9.71 Crore       1
PKR 6.11 Crore       1
PKR 15.7 Crore       1
PKR 4.41 Crore       1

In [53]:
import re
import numpy as np
import pandas as pd

def price_to_crore(x):
    if pd.isna(x):
        return np.nan
    
    s = str(x).lower().replace(",", "").replace("pkr", "").strip()

    # match number + unit
    m = re.search(r"(\d+(?:\.\d+)?)\s*(crore|lakh|arab|thousand)", s)
    
    if not m:
        return np.nan
    
    val = float(m.group(1))
    unit = m.group(2)

    if unit == "crore":
        return val
    elif unit == "lakh":
        return val / 100
    elif unit == "arab":   # 1 arab = 100 crore
        return val * 100
    elif unit == "thousand":
        return val / 100000  # 1 crore = 100,000 thousand

    return np.nan


df["price_crore"] = df["Price"].apply(price_to_crore)

In [110]:
df.sample(10)[['price_crore','Price']]

       price_crore           Price
1309         4.900   PKR 4.9 Crore
4639        22.000    PKR 22 Crore
4920         6.750  PKR 6.75 Crore
19192        4.900   PKR 4.9 Crore
20649        0.675   PKR 67.5 Lakh
6456         2.100   PKR 2.1 Crore
15509       14.000    PKR 14 Crore
4670        10.000    PKR 10 Crore
13800        2.200   PKR 2.2 Crore
19552        1.500   PKR 1.5 Crore

In [111]:
df['price_crore'].isnull().sum()

np.int64(0)

In [112]:
df.drop(columns=['Price'], inplace=True)
df.rename(columns={'price_crore': 'Price'}, inplace=True)

In [114]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Area',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Furnished', 'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Intercom', 'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price'],
      dtype='object')

In [115]:
df['Area'].value_counts()

Area
5 Marla       6071
1 Kanal       5272
10 Marla      4168
3 Marla       1295
2 Kanal       1082
8 Marla        392
4 Marla        358
12 Marla       268
7 Marla        242
6 Marla        182
1.1 Kanal      145
3.5 Marla      140
2 Marla        128
2.5 Marla      128
1.2 Kanal      123
11 Marla        89
14 Marla        79
9 Marla         67
4 Kanal         64
3 Kanal         64
15 Marla        63
17 Marla        41
18 Marla        33
7.5 Marla       32
1.5 Kanal       30
4.5 Marla       30
16 Marla        27
13 Marla        27
5.5 Marla       26
1.6 Kanal       26
1.3 Kanal       25
3.2 Marla       23
2.1 Kanal       18
1.7 Kanal       18
2.4 Marla       17
10.7 Marla      17
1.5 Marla       17
6 Kanal         13
6.1 Marla       13
5.3 Marla       13
2.5 Kanal       12
5 Kanal         12
2.3 Kanal       11
2.2 Marla       11
8 Kanal         10
1.8 Marla       10
10.5 Marla      10
7.2 Marla        9
9.5 Marla        9
19 Marla         9
1.4 Kanal        8
2.2 Kanal        8
1.8 Kanal        8
3.3 Marla        7
7 Kanal          7
3.7 Marla        7
12.5 Marla       7
6.5 Marla        7
4.2 Marla        7
2.7 Marla        6
4.4 Marla        6
8.5 Marla        5
5.7 Marla        5
1.6 Marla        5
2.4 Kanal        5
3.8 Marla        5
3.1 Marla        5
11.5 Marla       4
4.1 Marla        4
10.2 Marla       4
2.8 Marla        4
4.3 Marla        4
4.8 Marla        4
10.1 Marla       4
6.2 Marla        3
2.6 Marla        3
2.8 Kanal        3
5.6 Marla        3
6.8 Marla        3
10.9 Marla       3
2.7 Kanal        3
5.2 Marla        3
4.7 Marla        3
12.2 Marla       3
3.4 Marla        3
3.2 Kanal        3
19.5 Marla       2
1.2 Marla        2
4.1 Kanal        2
7.6 Marla        2
6.3 Marla        2
2.3 Marla        2
9.3 Marla        2
10.6 Marla       2
14.5 Marla       2
18.4 Marla       2
7.4 Marla        2
6.7 Marla        2
11.1 Marla       2
3.6 Marla        2
9.6 Marla        2
10.8 Marla       2
8.1 Kanal        2
1.7 Marla        2
1 Marla          2
0 Marla          1
18.5 Marla       1
12.9 Marla       1
2.9 Kanal        1
3.5 Kanal        1
5.3 Kanal        1
2.6 Kanal        1
5.9 Marla        1
39.3 Kanal       1
9.1 Marla        1
5.1 Kanal        1
19.1 Marla       1
17.3 Marla       1
3.7 Kanal        1
12.4 Marla       1
5.8 Marla        1
5.4 Marla        1
11.7 Marla       1
7.8 Marla        1
8.2 Marla        1
6.4 Marla        1
16.1 Marla       1
7.8 Kanal        1
0.5 Marla        1
7.3 Marla        1
10.4 Marla       1
3.9 Kanal        1
8.5 Kanal        1
3.1 Kanal        1
16.5 Marla       1
1.3 Marla        1
11.6 Marla       1
14 Kanal         1
8.7 Marla        1
9.4 Marla        1
10 Kanal         1
3.9 Marla        1
5.1 Marla        1
15.5 Marla       1
8.4 Marla        1
Name: count, dtype: int64

In [116]:
df['Area'].isnull().sum()

np.int64(0)

In [125]:
import re
import numpy as np
import pandas as pd

def area_to_marla(x):
    if pd.isna(x):
        return np.nan
    
    s = str(x).lower().strip()

    # extract number + unit
    m = re.search(r"(\d+(?:\.\d+)?)\s*(marla|kanal)", s)
    
    if not m:
        return np.nan
    
    val = float(m.group(1))
    unit = m.group(2)

    # convert to marla
    if unit == "kanal":
        val = val * 20  # 1 kanal = 20 marla

    # handle invalid / zero values
    if val == 0:
        print(val)
        return np.nan

    return val


df["area_marla"] = df["Area"].apply(area_to_marla)

0.0

In [126]:
df['area_marla'].isnull().sum()

np.int64(1)

In [127]:
df[df['area_marla'].isna()]['Link']

207    https://www.zameen.com/Property/dha_phase_7_dha_phase_7_-_block_y_10_marla_spanish_luxrey_bunglow_for_sale_dha_phase_7_y_block-54022687-1632-1.html
Name: Link, dtype: object

In [128]:
df['area_marla'].value_counts()

area_marla
5.0      6071
20.0     5272
10.0     4168
3.0      1295
40.0     1082
8.0       392
4.0       358
12.0      268
7.0       242
6.0       182
22.0      145
3.5       140
2.0       128
2.5       128
24.0      123
11.0       89
14.0       79
9.0        67
80.0       64
60.0       64
15.0       63
17.0       41
18.0       33
7.5        32
4.5        30
30.0       30
13.0       27
16.0       27
32.0       26
5.5        26
26.0       25
3.2        23
42.0       18
34.0       18
10.7       17
1.5        17
2.4        17
6.1        13
120.0      13
5.3        13
50.0       12
100.0      12
46.0       11
2.2        11
1.8        10
160.0      10
10.5       10
7.2         9
19.0        9
9.5         9
44.0        8
36.0        8
28.0        8
3.3         7
3.7         7
12.5        7
6.5         7
140.0       7
4.2         7
2.7         6
4.4         6
8.5         5
1.6         5
48.0        5
3.8         5
5.7         5
3.1         5
11.5        4
10.2        4
2.8         4
4.3         4
4.8         4
10.1        4
4.1         4
2.6         3
56.0        3
5.6         3
6.8         3
10.9        3
54.0        3
5.2         3
6.2         3
12.2        3
3.4         3
64.0        3
4.7         3
1.2         2
82.0        2
7.6         2
6.3         2
2.3         2
9.3         2
10.6        2
14.5        2
18.4        2
7.4         2
6.7         2
19.5        2
3.6         2
9.6         2
10.8        2
162.0       2
1.7         2
1.0         2
11.1        2
18.5        1
12.9        1
58.0        1
70.0        1
106.0       1
52.0        1
5.9         1
786.0       1
9.1         1
102.0       1
19.1        1
17.3        1
74.0        1
12.4        1
5.8         1
5.4         1
11.7        1
7.8         1
8.2         1
6.4         1
16.1        1
156.0       1
0.5         1
7.3         1
10.4        1
78.0        1
170.0       1
62.0        1
16.5        1
1.3         1
11.6        1
280.0       1
8.7         1
9.4         1
200.0       1
3.9         1
5.1         1
15.5        1
8.4         1
Name: count, dtype: int64

In [129]:
df.loc[df['area_marla'].isna(), 'area_marla'] = 10.0

In [130]:
df.sample(10)[['Area','area_marla']]

            Area  area_marla
9815     5 Marla         5.0
2810     1 Kanal        20.0
13606   10 Marla        10.0
15738    5 Marla         5.0
13792    5 Marla         5.0
20086  1.1 Kanal        22.0
13736    5 Marla         5.0
8504     5 Marla         5.0
19833    5 Marla         5.0
5573     5 Marla         5.0

In [ ]:
df.drop(columns=["Area"])

In [135]:
df = df.rename(columns={"area_marla": "Area"})

In [136]:
df['Area'].value_counts()

Area
5.0      6071
20.0     5272
10.0     4169
3.0      1295
40.0     1082
8.0       392
4.0       358
12.0      268
7.0       242
6.0       182
22.0      145
3.5       140
2.0       128
2.5       128
24.0      123
11.0       89
14.0       79
9.0        67
80.0       64
60.0       64
15.0       63
17.0       41
18.0       33
7.5        32
4.5        30
30.0       30
13.0       27
16.0       27
32.0       26
5.5        26
26.0       25
3.2        23
42.0       18
34.0       18
10.7       17
1.5        17
2.4        17
6.1        13
120.0      13
5.3        13
50.0       12
100.0      12
46.0       11
2.2        11
1.8        10
160.0      10
10.5       10
7.2         9
19.0        9
9.5         9
44.0        8
36.0        8
28.0        8
3.3         7
3.7         7
12.5        7
6.5         7
140.0       7
4.2         7
2.7         6
4.4         6
8.5         5
1.6         5
48.0        5
3.8         5
5.7         5
3.1         5
11.5        4
10.2        4
2.8         4
4.3         4
4.8         4
10.1        4
4.1         4
2.6         3
56.0        3
5.6         3
6.8         3
10.9        3
54.0        3
5.2         3
6.2         3
12.2        3
3.4         3
64.0        3
4.7         3
1.2         2
82.0        2
7.6         2
6.3         2
2.3         2
9.3         2
10.6        2
14.5        2
18.4        2
7.4         2
6.7         2
19.5        2
3.6         2
9.6         2
10.8        2
162.0       2
1.7         2
1.0         2
11.1        2
18.5        1
12.9        1
58.0        1
70.0        1
106.0       1
52.0        1
5.9         1
786.0       1
9.1         1
102.0       1
19.1        1
17.3        1
74.0        1
12.4        1
5.8         1
5.4         1
11.7        1
7.8         1
8.2         1
6.4         1
16.1        1
156.0       1
0.5         1
7.3         1
10.4        1
78.0        1
170.0       1
62.0        1
16.5        1
1.3         1
11.6        1
280.0       1
8.7         1
9.4         1
200.0       1
3.9         1
5.1         1
15.5        1
8.4         1
Name: count, dtype: int64

In [138]:
df['Area'].isnull().sum()

np.int64(0)

In [166]:
df["area_sqft"] = df["Area"] * 272.251

In [140]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Furnished', 'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Intercom', 'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft'],
      dtype='object')

In [141]:
df['Bedrooms'].isnull().sum()

np.int64(330)

In [142]:
df['Rooms'].value_counts()

Rooms
{}                                                                                                               2592
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                1352
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 814
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 744
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                 596
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '2'}                                                              411
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                 403
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 394
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '2'}                                                              379
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 376
{'Bedrooms': '5', 'Bathrooms': '5', 'Kitchens': '2'}                                                              364
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '2'}                                                              340
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '2', 'Store Rooms': '1'}                                          320
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '2'}                 318
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 315
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '2'}                                                              289
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '2'}                                                              286
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '2', 'Store Rooms': '1'}                                          280
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 251
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 241
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                 226
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 225
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2'}                                     216
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                 209
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '1'}                 204
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '2', 'Store Rooms': '1'}                                          189
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 182
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 176
{'Bedrooms': '5', 'Bathrooms': '5', 'Kitchens': '2', 'Store Rooms': '1'}                                          164
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2'}                                     135
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 133
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '2', 'Store Rooms': '1'}                                          128
{'Bedrooms': '5', 'Bathrooms': '6'}                                                                               123
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 121
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '2'}                 120
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                 120
{'Bedrooms': '3', 'Bathrooms': '4'}                                                                               119
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                 117
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '1', 'Store Rooms': '1'}                                          111
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                 109
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '2', 'Store Rooms': '1'}                                          105
{'Bedrooms': '2', 'Bathrooms': '2', 'Kitchens': '1'}                                                              101
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  99
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '1', 'Store Rooms': '1'}                                           94
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '1'}                                                               92
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  89
{'Bedrooms': '3', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  88
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  87
{'Bedrooms': '6', 'Bathrooms': '6', 'Kitchens': '2'}                                                               84
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  81
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  81
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  79
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2'}                                      73
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '1'}                                                               71
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2'}                                      64
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '1'}                  62
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  60
{'Bedrooms': '6', 'Bathrooms': '7', 'Kitchens': '2'}                                                               58
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  56
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2'}                                      55
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  55
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '2'}                  53
{'Bedrooms': '4', 'Bathrooms': '5'}                                                                                52
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '1'}                  51
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  51
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2'}                                      50
{'Bedrooms': '3', 'Bathrooms': '3'}                                                                                49
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  48
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  48
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1'}                                                               48
{'Bedrooms': '6', 'Bathrooms': '6', 'Kitchens': '2', 'Store Rooms': '1'}                                           45
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  45
{'Bedrooms': '2', 'Bathrooms': '2', 'Kitchens': '1', 'Store Rooms': '1'}                                           44
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '2'}                                      44
{'Servant Quarters': '1'}                                                                                          42
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  41
{'Bedrooms': '7', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  41
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  39
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  39
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '3', 'Kitchens': '3', 'Store Rooms': '2'}                  39
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  39
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  39
{'Bedrooms': '2', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  36
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  36
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  36
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '1'}                  35
{'Bedrooms': '3', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2'}                                      34
{'Bedrooms': '7', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  33
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1'}                                      33
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '3', 'Kitchens': '3', 'Store Rooms': '2'}                  33
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  33
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '1'}                  33
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  32
{'Bedrooms': '7', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  32
{'Bedrooms': '3', 'Bathrooms': '5', 'Kitchens': '2'}                                                               31
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '2', 'Store Rooms': '2'}                                           30
{'Bedrooms': '2', 'Bathrooms': '2'}                                                                                29
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2'}                                      29
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  28
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '1', 'Store Rooms': '1'}                                           28
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1'}                                      27
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2'}                                                       27
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '3', 'Kitchens': '3', 'Store Rooms': '3'}                  26
{'Bedrooms': '7', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  26
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  25
{'Bedrooms': '4', 'Bathrooms': '4'}                                                                                24
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2'}                                      24
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '5', 'Kitchens': '2'}                                      24
{'Kitchens': '2'}                                                                                                  22
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '3', 'Kitchens': '2', 'Store Rooms': '2'}                  22
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  22
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '3'}                                                               22
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '1'}                                                               21
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '1', 'Store Rooms': '1'}                                           20
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  20
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '3', 'Kitchens': '2', 'Store Rooms': '2'}                  20
{'Bedrooms': '5', 'Bathrooms': '5'}                                                                                20
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '2'}                  20
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  19
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  19
{'Bedrooms': '6', 'Bathrooms': '7'}                                                                                19
{'Bedrooms': '5', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  19
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  19
{'Bedrooms': '6', 'Bathrooms': '7', 'Kitchens': '2', 'Store Rooms': '1'}                                           19
{'Bedrooms': '2', 'Bathrooms': '3', 'Kitchens': '1', 'Store Rooms': '1'}                                           19
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '2'}                  19
{'Bedrooms': '7', 'Bathrooms': '7', 'Kitchens': '2'}                                                               18
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  18
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2'}                                      18
{'Bedrooms': '1', 'Bathrooms': '1'}                                                                                18
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  18
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1'}                                                       18
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1'}                                      18
{'Bedrooms': '7', 'Bathrooms': '10', 'Servant Quarters': '3', 'Kitchens': '4', 'Store Rooms': '3'}                 17
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '1'}                  17
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '2'}                  17
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '1'}                                                               17
{'Bedrooms': '7', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '2'}                  16
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2'}                                      16
{'Kitchens': '1'}                                                                                                  16
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '2'}                  16
{'Bedrooms': '4', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  16
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  16
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1', 'Store Rooms': '1'}                                           16
{'Bedrooms': '7', 'Bathrooms': '7', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  15
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  15
{'Bedrooms': '2', 'Bathrooms': '3', 'Kitchens': '1'}                                                               15
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '2'}                  15
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Store Rooms': '1'}                                   15
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '2'}                  15
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  14
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}                  14
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  14
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1'}                                      14
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}                  14
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2'}                                      14
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1'}                                      14
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '3', 'Kitchens': '2', 'Store Rooms': '2'}                  14
{'Bedrooms': '1', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}                  14
{'Bedrooms': '6', 'Bathrooms': '6'}                                                                                13
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '2', 'Store Rooms': '2'}                                           13
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Store Rooms': '1'}                                   13
{'Bedrooms': '7', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}                  13
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  13
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1'}                                                       13
{'Bedrooms': '7', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}                  13
{'Bedrooms': '2', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                  13
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '1', 'Store Rooms': '1'}                                           13
{'Bedrooms': '5', 'Bathrooms': '5', 'Kitchens': '1'}                                                               13

In [143]:
import ast
import re
import pandas as pd
import numpy as np

def to_dict(x):
    if pd.isna(x):
        return {}
    if isinstance(x, dict):
        return x
    s = str(x).strip()
    if s in ("", "{}"):
        return {}
    try:
        return ast.literal_eval(s)
    except Exception:
        return {}

rooms_dicts = df["Rooms"].apply(to_dict)

rooms_df = pd.json_normalize(rooms_dicts)

# lowercase + underscore
rooms_df.columns = [
    re.sub(r"[^a-z0-9]+", "_", c.strip().lower()).strip("_")
    for c in rooms_df.columns
]

# numeric values
for c in rooms_df.columns:
    rooms_df[c] = pd.to_numeric(rooms_df[c], errors="coerce")

# add to df
for c in rooms_df.columns:
    df[c] = rooms_df[c]

In [144]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Furnished', 'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Intercom', 'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft', 'bedrooms',
       'bathrooms', 'servant_quarters', 'kitchens', 'store_rooms'],
      dtype='object')

In [145]:
df['Bedrooms'].isnull().sum()

np.int64(330)

In [146]:
df['bedrooms'].isnull().sum()

np.int64(2791)

In [147]:
df["Bedrooms"] = df["Bedrooms"].fillna(df["bedrooms"])

In [ ]:
df['Bedrooms'].isnull().sum()

np.int64(93)

In [149]:
df['Baths'].isnull().sum()

np.int64(464)

In [150]:
df['bathrooms'].isnull().sum()

np.int64(2810)

In [151]:
df["Baths"] = df["Baths"].fillna(df["bathrooms"])

In [152]:
df['Baths'].isnull().sum()

np.int64(102)

In [153]:
df = df.drop(columns=["bedrooms", "bathrooms"], errors="ignore")

In [154]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Furnished', 'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Intercom', 'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft',
       'servant_quarters', 'kitchens', 'store_rooms'],
      dtype='object')

In [155]:
df.isna().sum().sort_values(ascending=False)

Furnished                                          9529
Other Healthcare and Recreation Facilities         8784
Facilities for Disabled                            8710
servant_quarters                                   8161
Other Community Facilities                         8132
Sauna                                              7964
Other Business and Communication Facilities        7851
store_rooms                                        7517
Jacuzzi                                            7485
Maintenance Staff                                  6936
Lawn or Garden                                     6801
Other Facilities                                   6491
Community Swimming Pool                            5992
Other Main Features                                5639
Intercom                                           5619
Central Heating                                    5286
Floors                                             5273
Central Air Conditioning                           4989
Community Gym                                      4895
Section - Healthcare Recreational                  4843
Community Centre                                   4787
Day Care Centre                                    4754
Built Year                                         4749
Built in year                                      4749
Waste Disposal                                     4712
Barbeque Area                                      4558
First Aid or Medical Centre                        4524
Satellite or Cable TV Ready                        4270
Community Lawn or Garden                           4244
Kids Play Area                                     4150
Double Glazed Windows                              3908
Security Staff                                     3906
Mosque                                             3874
Section - Other Facilities                         3837
Broadband Internet Access                          3755
Electricity Backup                                 3690
Section - Community Features                       3604
Section - Business and Communication               3550
kitchens                                           3505
Distance From Airport (kms)                        3303
Other Nearby Places                                3252
Parking Spaces                                     3001
Flooring                                           2714
Nearby Public Transport Service                    2601
Other Rooms                                        2182
Nearby Restaurants                                 2143
Nearby Shopping Malls                              2117
Nearby Hospitals                                   2081
Nearby Schools                                     2076
Section - Rooms                                    2033
Nearby Locations and Other Facilities              1986
Section - Nearby Locations and Other Facilities    1986
Section - Main Features                            1821
Features                                            720
Baths                                               102
Bedrooms                                             93
Name                                                  0
Society Link                                          0
Society                                               0
Property ID                                           0
Address                                               0
Description                                           0
Link                                                  0
Page Title                                            0
Rooms                                                 0
Price                                                 0
Area                                                  0
area_sqft                                             0
dtype: int64

In [157]:
df.shape

(21219, 68)

In [158]:
df['Price'].iloc[900]

np.float64(14.25)

In [159]:
df['total_rooms'] = (
    df.get('bedrooms', 0)
    + df.get('bathrooms', 0)
    + df.get('kitchens', 0)
    + df.get('store_rooms', 0)
)

In [161]:
df['total_rooms'].isna().sum()

np.int64(7681)

In [162]:
df["price_per_sqft"] = np.where(
    (df["area_sqft"] > 0) & df["Price"].notna(),
    (df["Price"] * 1e7) / df["area_sqft"],
    np.nan
)

In [163]:
df['price_per_sqft'].isna().sum()

np.int64(0)

In [168]:
df.sample(10)[['price_per_sqft','Area','Price']]

       price_per_sqft  Area   Price
7321     12867.647059   8.0   2.800
20113    18382.352941   4.8   2.400
1140     47334.558824  20.0  25.750
3056     14246.323529  20.0   7.750
3853     25551.470588  20.0  13.900
17724    11887.254902   1.5   0.485
14101    20588.235294   5.0   2.800
8718     11029.411765   5.0   1.500
3315     17849.264706  20.0   9.710
12909     9650.735294   8.0   2.100

In [169]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Furnished', 'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Intercom', 'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft',
       'servant_quarters', 'kitchens', 'store_rooms', 'total_rooms',
       'price_per_sqft'],
      dtype='object')

In [186]:
df['Built Year'] = pd.to_numeric(df['Built Year'].replace(True, np.nan), errors='coerce')

In [187]:
df['Built Year'].isnull().sum()

np.int64(5768)

In [188]:
df['Features'].iloc[0]

'Built in year : 2025 | Parking Spaces : 5 | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors : 2 | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Lawn or Garden | Swimming Pool | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities'

In [189]:
import re
import numpy as np

df["builtyear"] = (
    df["Features"]
      .str.extract(r"Built in year\s*:\s*([0-9]+(?:\.[0-9]+)?)", expand=False)
      .astype(float)
)

In [190]:
df['builtyear'].isnull().sum()

np.int64(5768)

In [191]:
print(df['builtyear'].iloc[0])
df['Built Year'].iloc[0]

2025.0

np.float64(2025.0)

In [192]:
df["Built Year"] = df["Built Year"].fillna(df["builtyear"])

In [193]:
df["Built Year"].isnull().sum()

np.int64(5768)

In [194]:
df = df.drop(columns=["builtyear"], errors="ignore")

In [179]:
print(df['Built Year'].iloc[800])
print(df['Built in year'].iloc[800])

2026
2026

In [180]:
df = df.drop(columns=["Built in year"], errors="ignore")

In [196]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Double Glazed Windows', 'Central Air Conditioning',
       'Central Heating', 'Flooring', 'Electricity Backup', 'Waste Disposal',
       'Floors', 'Other Main Features', 'Furnished',
       'Broadband Internet Access', 'Satellite or Cable TV Ready', 'Intercom',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft',
       'servant_quarters', 'kitchens', 'store_rooms', 'total_rooms',
       'price_per_sqft'],
      dtype='object')

In [287]:
df['Built Year'].value_counts()

Built Year
2025.0    5720
2026.0    3321
2024.0    1948
2023.0     847
2020.0     595
2022.0     542
2015.0     386
2018.0     316
2021.0     262
2010.0     196
2019.0     178
2000.0     145
2016.0     117
2017.0     116
2012.0     116
2014.0     112
2005.0      76
2013.0      62
2011.0      48
2008.0      40
2027.0      34
2028.0      31
2007.0      31
1990.0      26
2004.0      21
2029.0      21
1995.0      19
2001.0      17
2002.0      16
2009.0      16
2006.0      14
1999.0      12
1980.0      10
2003.0       8
1998.0       7
1985.0       6
1970.0       4
1986.0       4
1997.0       2
1960.0       2
1988.0       2
1992.0       2
1994.0       1
1996.0       1
Name: count, dtype: int64

In [286]:
df.loc[df["Built Year"] ==202.0  , "Built Year"] =2020

In [285]:
df.loc[df["Built Year"] == 202.0               , "Link"]

6588                                                          https://www.zameen.com/Property/dha_phase_7_dha_phase_7_-_block_y_10_marla_brand_new_modern_designer_owner_built_house_-for_sale-53524657-1632-1.html
9302                                 https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_3_marla_brand_new_house_for_sale_in_al_kabir_town_phase_2_main_raiwind_road_lahore-54026228-11704-1.html
9303                                 https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_3_marla_brand_new_house_for_sale_in_al_kabir_town_phase_2_main_raiwind_road_lahore-54026226-11704-1.html
9705                                 https://www.zameen.com/Property/al_kabir_town_al-kabir_town_-_phase_2_3_marla_brand_new_house_for_sale_in_al_kabir_town_phase_2_main_raiwind_road_lahore-54026227-11704-1.html
10338                                                https://www.zameen.com/Property/lahore_johar_town_johar_town_10_marla_size_35_65_hot_location_owner_belt_house_for_sale_near_allah_hu_chauk-53388242-93-1.html
11154    https://www.zameen.com/Property/lahore_central_park_housing_scheme_central_park_3_marla_house_available_for_sale_prime_location_near_to_park_and_masjid_all_facilities_available_here-53957957-1013-1.html
11175    https://www.zameen.com/Property/lahore_central_park_housing_scheme_central_park_3_marla_house_available_for_sale_prime_location_near_to_park_and_masjid_all_facilities_available_here-53957991-1013-1.html
15086                                                                       https://www.zameen.com/Property/jubilee_town_jubilee_town_-_block_c_prime_located_3_marla_brand_new_house_for_sale-53743502-3987-1.html
Name: Link, dtype: object

In [283]:
df.loc[5359, 'Built Year'] = 2015

In [288]:
df['Built Year'].isnull().sum()

np.int64(5769)

In [290]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Double Glazed Windows', 'Central Air Conditioning',
       'Central Heating', 'Flooring', 'Electricity Backup', 'Waste Disposal',
       'Floors', 'Other Main Features', 'Furnished',
       'Broadband Internet Access', 'Satellite or Cable TV Ready', 'Intercom',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Price', 'Area', 'area_sqft',
       'servant_quarters', 'kitchens', 'store_rooms', 'total_rooms',
       'price_per_sqft'],
      dtype='object')

In [295]:
df['Parking Spaces'].isnull().sum()

np.int64(3001)

In [294]:
df['Parking Spaces'].value_counts()

Parking Spaces
True    5948
1       3737
4       3035
2       2910
3       1250
5        539
6        357
10        95
8         82
02        48
01        34
03        21
7         20
12        19
20        19
15        14
50        10
30        10
25        10
04         9
100        9
9          6
40         4
16         4
180        3
250        2
00         2
14         2
200        2
06         1
35         1
0          1
3000       1
500        1
633        1
-1         1
05         1
274        1
18         1
002        1
80         1
88         1
60         1
1010       1
150        1
700        1
Name: count, dtype: int64

In [298]:
cols_to_drop = [
    'Parking Spaces',
    'Lobby in Building',
    'Double Glazed Windows',
    'Central Air Conditioning',
    'Central Heating',
    'Flooring',
    'Electricity Backup',
    'Waste Disposal',
    'Elevators',
    'Service Elevators in Building',
    'Broadband Internet Access',
    'Satellite or Cable TV Ready',
    'Business Center or Media Room in Building',
    'Conference Room in Building',
    'Intercom',
    'ATM Machines',
    'Community Lawn or Garden',
    'Community Swimming Pool',
    'Community Gym',
    'First Aid or Medical Centre',
    'Day Care Centre',
    'Kids Play Area',
    'Barbeque Area',
    'Mosque',
    'Community Centre',
    'Sauna',
    'Jacuzzi',
    'Maintenance Staff',
    'Security Staff',
    'Facilities for Disabled',
    'Laundry or Dry Cleaning Facility',
    'Nearby Schools',
    'Nearby Hospitals',
    'Nearby Shopping Malls',
    'Nearby Restaurants',
    'Nearby Public Transport Service',
    'Distance From Airport (kms)',
    'Other Nearby Places',
    'Other Facilities',
    'Other Main Features',
    'Section - Main Features',
    'Section - Rooms',
    'Section - Business and Communication',
    'Section - Community Features',
    'Section - Healthcare Recreational',
    'Section - Nearby Locations and Other Facilities',
    'Section - Other Facilities',
]

df.drop(columns=[c for c in cols_to_drop if c in df.columns], inplace=True)

In [299]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Floors', 'Furnished', 'Other Business and Communication Facilities',
       'Other Community Facilities', 'Lawn or Garden',
       'Other Healthcare and Recreation Facilities', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft'],
      dtype='object')

In [300]:
df['Other Rooms'].value_counts()

Other Rooms
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                  7847
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room                                                                               1260
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                    730
Drawing Room, Dining Room, Powder Room, Lounge or Sitting Room, Laundry Room                                                                                                                          555
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                        532
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                      449
Drawing Room, Dining Room                                                                                                                                                                             441
Drawing Room, Dining Room, Lounge or Sitting Room                                                                                                                                                     404
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                 318
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room                                                                                     252
Drawing Room, Dining Room, Powder Room, Lounge or Sitting Room                                                                                                                                        251
Drawing Room, Dining Room, Study Room, Prayer Room, Other Rooms                                                                                                                                       236
Drawing Room, Dining Room, Powder Room                                                                                                                                                                227
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Lounge or Sitting Room, Laundry Room                                                                                                 206
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                    204
Study Room                                                                                                                                                                                            170
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                          160
Other Rooms                                                                                                                                                                                           153
Bedrooms, Bathrooms, Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms     129
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Lounge or Sitting Room, Other Rooms                                                                                                  120
Drawing Room, Dining Room, Powder Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                             116
Drawing Room, Dining Room, Lounge or Sitting Room, Laundry Room                                                                                                                                       113
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                           103
Drawing Room, Dining Room, Study Room, Prayer Room                                                                                                                                                     93
Drawing Room, Dining Room, Powder Room, Laundry Room                                                                                                                                                   91
Drawing Room, Dining Room, Study Room, Powder Room, Lounge or Sitting Room, Laundry Room                                                                                                               90
Drawing Room, Dining Room, Other Rooms                                                                                                                                                                 80
Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                             79
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                76
Drawing Room                                                                                                                                                                                           69
Drawing Room, Lounge or Sitting Room                                                                                                                                                                   67
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Lounge or Sitting Room                                                                                                                60
Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                          60
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                          58
Drawing Room, Dining Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room                                                                                                               57
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Other Rooms                                                                                  54
Drawing Room, Powder Room, Lounge or Sitting Room                                                                                                                                                      53
Drawing Room, Dining Room, Lounge or Sitting Room, Other Rooms                                                                                                                                         48
Drawing Room, Dining Room, Prayer Room, Powder Room, Lounge or Sitting Room, Laundry Room                                                                                                              48
Drawing Room, Dining Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                                           48
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Other Rooms                                                                                                                           45
Drawing Room, Dining Room, Powder Room, Other Rooms                                                                                                                                                    43
Drawing Room, Dining Room, Study Room                                                                                                                                                                  43
Drawing Room, Powder Room, Laundry Room                                                                                                                                                                43
Drawing Room, Dining Room, Study Room, Powder Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                  42
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Store Rooms, Lounge or Sitting Room, Laundry Room, Other Rooms                                                      38
Drawing Room, Dining Room, Study Room, Powder Room, Lounge or Sitting Room                                                                                                                             36
Drawing Room, Powder Room, Lounge or Sitting Room, Laundry Room                                                                                                                                        36
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room                                                  33
Drawing Room, Dining Room, Study Room, Prayer Room, Lounge or Sitting Room, Laundry Room                                                                                                               33
Drawing Room, Dining Room, Study Room, Prayer Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                  33
Drawing Room, Dining Room, Prayer Room, Powder Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                 32
Drawing Room, Dining Room, Study Room, Prayer Room, Lounge or Sitting Room, Other Rooms                                                                                                                32
Lounge or Sitting Room                                                                                                                                                                                 32
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room                                                                                                                                        31
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Lounge or Sitting Room, Laundry Room                                                                                             30
Drawing Room, Dining Room, Prayer Room, Powder Room, Laundry Room                                                                                                                                      30
Drawing Room, Dining Room, Study Room, Other Rooms                                                                                                                                                     29
Drawing Room, Dining Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                                  29
Drawing Room, Dining Room, Powder Room, Lounge or Sitting Room, Other Rooms                                                                                                                            29
Drawing Room, Dining Room, Study Room, Lounge or Sitting Room, Laundry Room                                                                                                                            28
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room                                                                    27
Drawing Room, Dining Room, Study Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                      27
Drawing Room, Lounge or Sitting Room, Laundry Room                                                                                                                                                     26
Servant Quarters, Drawing Room, Dining Room, Kitchens, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                            26
Drawing Room, Dining Room, Prayer Room, Powder Room, Lounge or Sitting Room                                                                                                                            24
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                        23
Drawing Room, Dining Room, Study Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room                                                                                                   22
Drawing Room, Dining Room, Study Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                 21
Drawing Room, Dining Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                     21
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym                                                                                                                                   21
Drawing Room, Dining Room, Study Room, Prayer Room, Store Rooms, Other Rooms                                                                                                                           20
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                20
Drawing Room, Dining Room, Study Room, Powder Room                                                                                                                                                     20
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room                                                                                                    19
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room                                                                                               19
Dining Room                                                                                                                                                                                            18
Drawing Room, Dining Room, Study Room, Prayer Room, Steam Room, Lounge or Sitting Room, Laundry Room                                                                                                   18
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                       18
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room                                                               18
Servant Quarters, Drawing Room, Dining Room, Study Room, Prayer Room, Store Rooms, Lounge or Sitting Room, Other Rooms                                                                                 17
Drawing Room, Dining Room, Study Room, Prayer Room, Lounge or Sitting Room                                                                                                                             17
Drawing Room, Study Room                                                                                                                                                                               17
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Gym, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room                                        16
Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Laundry Room                                                                                                                          16
Drawing Room, Dining Room, Study Room, Prayer Room, Store Rooms, Lounge or Sitting Room, Other Rooms                                                                                                   16
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room                                             16
Drawing Room, Dining Room, Study Room, Prayer Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                                                      15
Servant Quarters, Other Rooms                                                                                                                                                                          15
Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Store Rooms, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                  14
Bathrooms, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                         14
Drawing Room, Dining Room, Study Room, Lounge or Sitting Room                                                                                                                                          14
Servant Quarters, Drawing Room, Dining Room, Kitchens, Study Room, Prayer Room, Powder Room, Store Rooms, Lounge or Sitting Room, Laundry Room, Other Rooms                                            14
Bedrooms, Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms                                                          14
Drawing Room, Dining Room, Powder Room, Laundry Room, Other Rooms                                                                                                                                      14
Drawing Room, Dining Room, Steam Room, Lounge or Sitting Room, Laundry Room                                                                                                                            14
Drawing Room, Powder Room                                                                                                                                                                              14
Drawing Room, Dining Room, Laundry Room                                                                                                                                                                14

In [301]:
room_map = {
    "Drawing Room": "drawing_room",
    "Dining Room": "dining_room",
    "Lounge or Sitting Room": "lounge_or_sitting_room",
    "Laundry Room": "laundry_room",
    "Study Room": "study_room",
    "Prayer Room": "prayer_room",
    "Powder Room": "powder_room",
    "Gym": "gym",
    "Steam Room": "steam_room",
    
    # 🔥 missing important ones (added)
    "Servant Quarters": "servant_quarters_flag",
    "Store Rooms": "store_rooms_flag",
    "Kitchens": "kitchens_flag",

    "Other Rooms": "other_rooms_flag",
}

def extract_set(s):
    if pd.isna(s):
        return set()
    return {p.strip().lower() for p in str(s).split(",") if p.strip()}

room_sets = df["Other Rooms"].apply(extract_set)  # make sure column name correct

for label, col in room_map.items():
    key = label.lower()
    df[col] = room_sets.apply(lambda s: key in s).astype(int)

In [302]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Floors', 'Furnished', 'Other Business and Communication Facilities',
       'Other Community Facilities', 'Lawn or Garden',
       'Other Healthcare and Recreation Facilities', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms_flag'],
      dtype='object')

In [303]:
df = df.drop(columns=["Other Rooms"], errors="ignore")
df = df.rename(columns={"other_rooms_flag": "other_rooms"})

In [304]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Link', 'Floors',
       'Furnished', 'Other Business and Communication Facilities',
       'Other Community Facilities', 'Lawn or Garden',
       'Other Healthcare and Recreation Facilities', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms'],
      dtype='object')

In [306]:
df['Society'].isnull().sum()

np.int64(0)

In [308]:
df['Society'].value_counts()

Society
DHA Defence                                   6748
Bahria Town                                   1411
Park View City                                1261
Raiwind Road                                  1012
Johar Town                                     575
Central Park Housing Scheme                    567
GT Road                                        532
Bahria Orchard                                 497
DHA 11 Rahbar                                  490
Valencia Housing Society                       428
Wapda Town                                     364
Paragon City                                   349
Allama Iqbal Town                              339
LDA Avenue                                     333
Askari                                         313
Jubilee Town                                   250
Cantt                                          245
Al Rehman Garden                               244
Model Town                                     232
Marghzar Officers Colony                       228
Gulberg                                        216
Formanites Housing Scheme                      215
Defence Road                                   181
Sabzazar Scheme                                170
Nasheman-e-Iqbal                               166
Main Canal Bank Road                           147
Township                                       145
Eden                                           141
Ferozepur Road                                 136
College Road                                   135
Lake City Meadows                              130
IEP Engineers Town                             129
Military Accounts Housing Society              126
Pak Arab Housing Society                       119
Garden Town                                    116
Bahria Nasheman                                112
Punjab Coop Housing Society                    110
Canal Garden                                   106
Khayaban-e-Amin                                103
Bankers Avenue Cooperative Housing Society      92
Samanabad                                       90
NFC 1                                           87
EME Society                                     86
Faisal Town                                     83
Cavalry Ground                                  78
New Lahore City                                 78
Al Haram Garden                                 77
Shadab Garden                                   75
Divine Gardens                                  74
Vital Homes Housing Scheme                      73
Green City                                      70
Cavalry Extension                               64
Punjab Govt Employees Society                   62
Harbanspura                                     61
Punjab University Employees Society             58
Tariq Gardens                                   55
Punjab Small Industries Colony                  55
Architects Engineers Housing Society            53
UET Housing Society                             48
Fazaia Housing Scheme                           48
Bankers Co-operative Housing Society            47
Nishtar Colony                                  42
Ghous Garden                                    41
OPF Housing Scheme                              38
PCSIR Housing Scheme                            37
PIA Housing Scheme                              36
Walton Road                                     36
Lahore - Jaranwala Road                         35
Abdalians Cooperative Housing Society           32
Chinar Bagh                                     32
Gajju Matah                                     29
Gulshan-e-Ravi                                  28
Al Noor Park Housing Society                    28
Izmir Town                                      26
Lahore Motorway City                            25
Taj Bagh Scheme                                 25
Chungi Amar Sadhu                               25
Lahore Medical Housing Society                  24
Multan Road                                     23
Sui Gas Housing Society                         22
Name: count, dtype: int64

In [309]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Link', 'Floors',
       'Furnished', 'Other Business and Communication Facilities',
       'Other Community Facilities', 'Lawn or Garden',
       'Other Healthcare and Recreation Facilities', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms'],
      dtype='object')

In [297]:
features_unique = (
    df["Features"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
    .str.split(":", n=1)
    .str[0]
    .str.strip()
    .unique()
)

features_unique

array(['Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors',
       'Other Main Features', 'Furnished', 'Broadband Internet Access',
       'Satellite or Cable TV Ready', 'Intercom',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool',
       'Community Gym', 'First Aid or Medical Centre', 'Day Care Centre',
       'Kids Play Area', 'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Lawn or Garden', 'Swimming Pool',
       'Sauna', 'Jacuzzi', 'Other Healthcare and Recreation Facilities',
       'Nearby Schools', 'Nearby Hospitals', 'Nearby Shopping Malls',
       'Nearby Restaurants', 'Distance From Airport (kms)',
       'Nearby Public Transport Service', 'Other Nearby Places',
       'Maintenance Staff', 'Security Staff', 'Facilities for Disabled',
       'Other Facilities'], dtype=object)

In [310]:
import pandas as pd

# -----------------------------
# LUXURY WEIGHTS (balanced)
# -----------------------------
luxury_weights = {
    "Parking Spaces": 3,
    "Double Glazed Windows": 2,
    "Central Air Conditioning": 4,
    "Central Heating": 3,
    "Flooring": 2,
    "Electricity Backup": 4,
    "Waste Disposal": 1,

    "Broadband Internet Access": 1,
    "Satellite or Cable TV Ready": 1,
    "Intercom": 1,

    # community
    "Community Lawn or Garden": 2,
    "Community Swimming Pool": 4,
    "Community Gym": 3,
    "Community Centre": 2,
    "Kids Play Area": 2,
    "Day Care Centre": 2,
    "Barbeque Area": 2,
    "Mosque": 1,

    # standalone (IMPORTANT - you missed)
    "Swimming Pool": 4,
    "Lawn or Garden": 2,

    # premium
    "Sauna": 4,
    "Jacuzzi": 4,

    # services
    "Maintenance Staff": 3,
    "Security Staff": 4,
    "Facilities for Disabled": 2,

    # generic buckets (low weight)
    "Other Community Facilities": 1,
    "Other Healthcare and Recreation Facilities": 1,
    "Other Business and Communication Facilities": 1,
}

# -----------------------------
# FURNISHING WEIGHTS
# -----------------------------
furnishing_weights = {
    "Furnished": 5,
    "Flooring": 3,
    "Central Air Conditioning": 4,
    "Central Heating": 3,
    "Double Glazed Windows": 2,
    "Electricity Backup": 2,
    "Intercom": 1,
}

# -----------------------------
# LOWERCASE MAPS
# -----------------------------
lux_w = {k.lower(): v for k, v in luxury_weights.items()}
fur_w = {k.lower(): v for k, v in furnishing_weights.items()}

# -----------------------------
# FEATURE PARSER
# -----------------------------
def feature_set(s):
    if pd.isna(s):
        return set()
    parts = [p.strip() for p in str(s).split("|") if p.strip()]
    return {p.split(":", 1)[0].strip().lower() for p in parts}

feat_sets = df["Features"].apply(feature_set)

# -----------------------------
# SCORES
# -----------------------------
df["luxury_score"] = feat_sets.apply(lambda s: sum(lux_w.get(x, 0) for x in s))
df["furnishing_score"] = feat_sets.apply(lambda s: sum(fur_w.get(x, 0) for x in s))

# -----------------------------
# ADD FURNISHED COLUMN IMPACT (IMPORTANT)
# -----------------------------
df["furnishing_score"] += df["Furnished"].fillna(0) * 5

In [311]:
df = df.drop(columns=["Features"])

In [312]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Built Year', 'Address', 'Description',
       'Nearby Locations and Other Facilities', 'Rooms', 'Link', 'Floors',
       'Furnished', 'Other Business and Communication Facilities',
       'Other Community Facilities', 'Lawn or Garden',
       'Other Healthcare and Recreation Facilities', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms', 'luxury_score',
       'furnishing_score'],
      dtype='object')

In [313]:
import re

df.columns = [
    re.sub(r'[^a-z0-9]+', '_', col.strip().lower()).strip('_')
    for col in df.columns
]

In [314]:
df.columns

Index(['property_id', 'society', 'society_link', 'name', 'page_title',
       'bedrooms', 'baths', 'built_year', 'address', 'description',
       'nearby_locations_and_other_facilities', 'rooms', 'link', 'floors',
       'furnished', 'other_business_and_communication_facilities',
       'other_community_facilities', 'lawn_or_garden',
       'other_healthcare_and_recreation_facilities', 'price', 'area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms', 'luxury_score',
       'furnishing_score'],
      dtype='object')

In [315]:
df = df.drop(columns=["society_link", "name", "page_title", "description", "address"], errors="ignore")

In [316]:
df.columns

Index(['property_id', 'society', 'bedrooms', 'baths', 'built_year',
       'nearby_locations_and_other_facilities', 'rooms', 'link', 'floors',
       'furnished', 'other_business_and_communication_facilities',
       'other_community_facilities', 'lawn_or_garden',
       'other_healthcare_and_recreation_facilities', 'price', 'area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'total_rooms', 'price_per_sqft', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'servant_quarters_flag',
       'store_rooms_flag', 'kitchens_flag', 'other_rooms', 'luxury_score',
       'furnishing_score'],
      dtype='object')

In [317]:
df.to_csv("lahore_house_feature_engineered.csv", index=False)