# Messy Data Issues Report  
**Dataset:** `lahore_flats_v2.csv`

---

## 1. Completeness Issues
Significant missing values were found across multiple critical fields:

- **Price / Marla / Area (sqft):** 599 missing each  ✅
- **Floor Number:** 1,503 missing  ✅
- **Total Floors:** 1,468 missing✅
- **Built Year:** 1,117 missing  ✅ But some nan remaning
- **Description:** 599 missing  
- **Features:** 652 missing  ✅
- **Nearby Locations and Other Facilities:** 789 missing  
- **Other Rooms:** 866 missing  
- **Property ID:** Not found for 599 records  
- **Name:** Appears as `#NAME?` in 155 records  

---

## 2. Validity Issues
Presence of outliers and clearly invalid values:

- **Floor Number:** Includes extreme values such as `1234` and `2018`  
- **Total Floors:** Invalid entries like `2018` and `2020`  
- **Built Year:** Contains `1`, `20242`, and boolean `TRUE` (110 rows affected)  
- **Parking Spaces:** Unrealistic values up to `500`  

---

## 3. Accuracy Issues
Type and format inconsistencies affecting data reliability:

- **Price:** Stored as text with currency symbols/units in ~2,500 rows  
- **Floor Number:** Contains boolean values (`TRUE/FALSE`) in 500 rows  
- **Total Floors:** Non-numeric entries in 278 rows  
- **Built Year:** Non-YYYY formats in 78 rows  

---

## 4. Consistency Issues
Conflicting representations and structural inconsistencies:

- **Duplicate `Link` values:** 20 duplicates identified  
- **Boolean vs numeric mixing:**  
  - Columns such as *Parking Spaces*, *Floor*, *Floors in Building*, *Elevators* mix `TRUE/FALSE` with numeric counts  
- **Area mismatch:**  
  - Area (sqft) never aligns with standard Marla-to-sqft conversion  
- **Column naming issue:**  
  - `\ufeffProperty ID` includes a BOM (Byte Order Mark)  

---

## 5. Messy Data Structure Issues

### 5.1 Multi-Valued Cells
- **Features:** Multiple items packed using `|` delimiter  
- **Nearby Locations and Other Facilities:** Comma-separated lists in one cell  
- **Other Rooms:** Comma-separated values stored in a single column  

### 5.2 Structured Data Embedded as Text
- **Rooms:** Stored as a stringified dictionary, packing multiple attributes into one cell  

### 5.3 Sparse Section Columns
- **Section - Plot Features:** Completely empty in 3,098 rows  
- **Other `Section - ...` columns:** High levels of missingness across the dataset  

---

## 6. Summary
The dataset exhibits major issues across **completeness, validity, accuracy, consistency, and structure**.  
Substantial cleaning, normalization, type enforcement, and schema redesign are required before it can be reliably used for analysis or modeling.

---

In [105]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [106]:
df=pd.read_csv("E:\Project\Data Cleaning\lahore_flats_v2.csv")

In [107]:
df.sample(10)

,Property ID,Name,Price,Marla,Area (sqft),Floor Number,Total Floors,Built Year,Address,Description,...,Park Facing,Disputed,File,Balloted,Sewerage,Electricity,Water Supply,Sui Gas,Boundary Wall,Section - Plot Features
1345,53240261,"- BHK Gulberg 3, Gulberg, Lahore, Punjab",PKR 2.85 Crore,2.0,450.0,NaN,NaN,2029,"Gulberg 3, Gulberg, Lahore, Punjab",Zameen ARX Redefining the Urban Skyline Situat...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1636,53593184,"2 BHK Al-Kabir Town - Phase 2, Al-Kabir Town, ...",PKR 1 Crore,3.6,810.0,NaN,NaN,NaN,"Al-Kabir Town - Phase 2, Al-Kabir Town, Raiwin...",800 square feet Flat prim Mall for sale in Al ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860,Not found,Not listed,NaN,NaN,NaN,NaN,NaN,NaN,Not listed,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
140,53549863,"3 BHK Askari 11, Askari, Lahore, Punjab",PKR 3.3 Crore,10.0,2250.0,NaN,NaN,NaN,"Askari 11, Askari, Lahore, Punjab","*10 Marla Apartment for Sale Askari 11, Lahore...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2088,53212238,"3 BHK Penta Square By DHA Lahore, DHA Phase 5,...",PKR 4.5 Crore,7.7,1732.5,NaN,NaN,2025,"Penta Square By DHA Lahore, DHA Phase 5, DHA D...","Al Ghani Real Estate Offers, Luxury 3-Bedroom ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1610,52740285,"1 BHK The Opus Luxury Residence, Gulberg 3, Gu...",PKR 2.3 Crore,2.8,630.0,5,8,1,"The Opus Luxury Residence, Gulberg 3, Gulberg,...",For Sale: One-Bed Apartment At The Opus Luxury...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3033,52921025,"2 BHK Fazaia Housing Scheme Phase 1, Fazaia Ho...",PKR 1.17 Crore,2.6,585.0,NaN,NaN,2007,"Fazaia Housing Scheme Phase 1, Fazaia Housing ...",apartment available for sale on installments t...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2243,53269865,"- BHK DHA Phase 3 - Block Y, DHA Phase 3, DHA ...",PKR 75 Lakh,1.7,382.5,TRUE,2,TRUE,"DHA Phase 3 - Block Y, DHA Phase 3, DHA Defenc...",Lahore Havalian Estate Offers: 375 Sq Ft Studi...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
369,53510676,"3 BHK Askari 11, Askari, Lahore, Punjab",PKR 3.15 Crore,10.0,2250.0,1,1,1,"Askari 11, Askari, Lahore, Punjab",This 10 Marla Sized Property Will Definitely S...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2835,53232406,"1 BHK Jubilee Town - Commercial Area, Jubilee ...",PKR 75 Lakh,2.2,495.0,NaN,NaN,NaN,"Jubilee Town - Commercial Area, Jubilee Town, ...",Future Tower offer 1 Bed Well Furnished Ready ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Analyze issues with data through dynamic & Programetic assessment.

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3099 entries, 0 to 3098
Data columns (total 84 columns):
 #   Column                                           Non-Null Count  Dtype
---  ------                                           --------------  -----
 0   Property ID                                      3099 non-null   object
 1   Name                                             3099 non-null   object
 2   Price                                            2500 non-null   object
 3   Marla                                            2500 non-null   float64
 4   Area (sqft)                                      2500 non-null   float64
 5   Floor Number                                     1596 non-null   object
 6   Total Floors                                     1631 non-null   object
 7   Built Year                                       1982 non-null   object
 8   Address                                          3099 non-null   object
 9   Description                                      2500 non-null   object
 10  Features                                         2447 non-null   object
 11  Nearby Locations and Other Facilities            2310 non-null   object
 12  Rooms                                            3099 non-null   object
 13  Other Rooms                                      2233 non-null   object
 14  Link                                             3099 non-null   object
 15  Parking Spaces                                   2186 non-null   object
 16  Lobby in Building                                1816 non-null   object
 17  Double Glazed Windows                            2064 non-null   object
 18  Central Air Conditioning                         1941 non-null   object
 19  Central Heating                                  1892 non-null   object
 20  Flooring                                         2232 non-null   object
 21  Electricity Backup                               2157 non-null   object
 22  Waste Disposal                                   2078 non-null   object
 23  Floor                                            1596 non-null   object
 24  Floors in Building                               1631 non-null   object
 25  Elevators                                        1697 non-null   object
 26  Service Elevators in Building                    1673 non-null   object
 27  Other Main Features                              1747 non-null   object
 28  Broadband Internet Access                        2168 non-null   object
 29  Satellite or Cable TV Ready                      2111 non-null   object
 30  Business Center or Media Room in Building        1442 non-null   object
 31  Conference Room in Building                      1438 non-null   object
 32  Intercom                                         1949 non-null   object
 33  ATM Machines                                     1508 non-null   object
 34  Other Business and Communication Facilities      1491 non-null   object
 35  Community Lawn or Garden                         2140 non-null   object
 36  Community Swimming Pool                          1917 non-null   object
 37  Community Gym                                    2094 non-null   object
 38  First Aid or Medical Centre                      2114 non-null   object
 39  Day Care Centre                                  2079 non-null   object
 40  Kids Play Area                                   2158 non-null   object
 41  Barbeque Area                                    2092 non-null   object
 42  Mosque                                           2174 non-null   object
 43  Community Centre                                 2078 non-null   object
 44  Other Community Facilities                       1490 non-null   object
 45  Sauna                                            1571 non-null   object
 46  Jacuzzi                                          1521 non-null   object
 47  Other Healthcare and Recreation Facilities       1408 non-null   object
 48  Nearby Schools                                   2293 non-null   object
 49  Nearby Hospitals                                 2293 non-null   object
 50  Nearby Shopping Malls                            2291 non-null   object
 51  Nearby Restaurants                               2292 non-null   object
 52  Distance From Airport (kms)                      2131 non-null   object
 53  Nearby Public Transport Service                  2230 non-null   object
 54  Other Nearby Places                              2144 non-null   object
 55  Maintenance Staff                                1762 non-null   object
 56  Security Staff                                   2104 non-null   object
 57  Laundry or Dry Cleaning Facility                 949 non-null    object
 58  Facilities for Disabled                          1536 non-null   object
 59  Pets Allowed                                     515 non-null    object
 60  Other Facilities                                 1693 non-null   object
 61  Section - Main Features                          2365 non-null   object
 62  Section - Rooms                                  2310 non-null   object
 63  Section - Business and Communication             2201 non-null   object
 64  Section - Community Features                     2220 non-null   object
 65  Section - Healthcare Recreational                1825 non-null   object
 66  Section - Nearby Locations and Other Facilities  2310 non-null   object
 67  Section - Other Facilities                       2112 non-null   object
 68  Furnished                                        1448 non-null   object
 69  Communal/Shared Kitchen                          631 non-null    object
 70  Built in year                                    1982 non-null   object
 71  Pets Not Allowed                                 139 non-null    object
 72  Possesion                                        1 non-null      object
 73  Corner                                           1 non-null      object
 74  Park Facing                                      1 non-null      object
 75  Disputed                                         1 non-null      object
 76  File                                             1 non-null      object
 77  Balloted                                         1 non-null      object
 78  Sewerage                                         1 non-null      object
 79  Electricity                                      1 non-null      object
 80  Water Supply                                     1 non-null      object
 81  Sui Gas                                          1 non-null      object
 82  Boundary Wall                                    1 non-null      object
 83  Section - Plot Features                          1 non-null      object
dtypes: float64(2), object(82)
memory usage: 2.0+ MB

In [109]:
df.describe()

             Marla  Area (sqft)
count  2500.000000  2500.000000
mean      6.248960  1406.016000
std       3.988644   897.444834
min       0.400000    90.000000
25%       2.400000   540.000000
50%       5.000000  1125.000000
75%      10.000000  2250.000000
max      28.500000  6412.500000

## Issues in data

In [110]:
import re
import numpy as np

def price_to_pkr(x):
    if x is None or (isinstance(x, float) and np.isnan(x)):
        return np.nan
    
    s = str(x).strip().lower()
    s = s.replace(",", "")
    
    # common cleanup
    s = re.sub(r"\s+", " ", s)          # normalize spaces
    s = s.replace("pkr", "").strip()    # remove currency label
    
    # extract number + unit
    m = re.search(r"(\d+(?:\.\d+)?)\s*(lakh|crore)", s)
    if not m:
        return np.nan
    
    val = float(m.group(1))
    unit = m.group(2)
    
    if unit == "lakh":
        return val * 100_000
    if unit == "crore":
        return val * 10_000_000
    
    return np.nan

# create numeric column
df["Price"] = df["Price"].apply(price_to_pkr)

# (optional) make it integer rupees where possible
df["Price"] = df["Price"].round().astype("Int64")

In [111]:
df['Price']

0        5400000
1        2157000
2        8000000
3        2000000
4        2500000
          ...
3094     7500000
3095    12200000
3096     6380000
3097     4500000
3098     5500000
Name: Price, Length: 3099, dtype: Int64

In [112]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features'],
      dtype='object')

In [113]:
df["Area (sqft)"] = df["Marla"] * 272.25

In [209]:
df["price_per_sqft"] = df["Price"] / df["Area (sqft)"]

In [ ]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

In [116]:
df = df[df["Property ID"].str.strip().str.lower() != "not found"]

In [117]:
df.shape

(2500, 85)

In [118]:
df.duplicated().sum()

np.int64(0)

In [119]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft'],
      dtype='object')

In [120]:
import ast

df['Rooms_dict'] = df['Rooms'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else {}
)

In [121]:
rooms_df = pd.json_normalize(df['Rooms_dict'])
rooms_df

     Bedrooms Bathrooms Kitchens Servant Quarters Store Rooms
0           1         1        1              NaN         NaN
1           1         1        1              NaN         NaN
2           1         1        1              NaN         NaN
3         NaN         1        1                1           1
4           1         1        1                1           1
...       ...       ...      ...              ...         ...
2495      NaN       NaN      NaN              NaN         NaN
2496        1         2        1              NaN         NaN
2497        1         1      NaN                2           1
2498        1         1        1                1           1
2499        3         3        1                2           1

[2500 rows x 5 columns]

In [122]:
df = pd.concat([df, rooms_df], axis=1)

In [123]:
features = df['Features'].apply(lambda x: x.split("|") if isinstance(x, str) else x)

features

0       [Parking Spaces ,  Lobby in Building ,  Double...
1       [Central Air Conditioning ,  Central Heating ,...
2       [Parking Spaces ,  Lobby in Building ,  Double...
3       [Built in year : 2023 ,  Parking Spaces : 1 , ...
4       [Built in year : 2023 ,  Parking Spaces ,  Lob...
                              ...
2491                                                  NaN
2492                                                  NaN
2494                                                  NaN
2495                                                  NaN
2496                                                  NaN
Name: Features, Length: 2991, dtype: object

In [124]:
df['Rooms'][90]

"{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}"

In [125]:
df=df.drop(columns='Rooms')

In [126]:
df['Nearby Locations and Other Facilities'].isna().sum()

np.int64(681)

In [127]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'fe', 'Rooms_dict',
       'Bedrooms', 'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'

In [128]:
df.drop(columns='Property ID')

,Name,Price,Marla,Area (sqft),Floor Number,Total Floors,Built Year,Address,Description,Features,...,Sui Gas,Boundary Wall,Section - Plot Features,price_per_sqft,Rooms_dict,Bedrooms,Bathrooms,Kitchens,Servant Quarters,Store Rooms
0,#NAME?,5400000,1.3,353.925,8,11,NaN,"Bahria Town - Johar Block, Bahria Town - Secto...","Experience luxury living at Grand 11, a presti...",Parking Spaces | Lobby in Building | Double Gl...,...,NaN,NaN,NaN,15257.469803,"{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens'...",1,1,1,NaN,NaN
1,#NAME?,2157000,1.8,490.050,NaN,13,NaN,"Bahria Town - Sector B, Bahria Town, Lahore, P...",With 25% Get Your Fully Furnished One Bed Stud...,Central Air Conditioning | Central Heating | F...,...,NaN,NaN,NaN,4401.591674,"{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens'...",1,1,1,NaN,NaN
2,"1 BHK Bahria Town - Johar Block, Bahria Town -...",8000000,2.2,598.950,6,11,NaN,"Bahria Town - Johar Block, Bahria Town - Secto...",1-Bed Luxury Apartment Pre-Launch Offer Step i...,Parking Spaces | Lobby in Building | Double Gl...,...,NaN,NaN,NaN,13356.707572,"{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens'...",1,1,1,NaN,NaN
3,"1 BHK Bahria Town - Sector B, Bahria Town, Lah...",2000000,2.2,598.950,TRUE,8,2023,"Bahria Town - Sector B, Bahria Town, Lahore, P...",Aiwa Properties Offering Investment Opportunit...,Built in year : 2023 | Parking Spaces : 1 | Lo...,...,NaN,NaN,NaN,3339.176893,"{'Bathrooms': '1', 'Servant Quarters': '1', 'K...",NaN,1,1,1,1
4,"1 BHK Bahria Town - Sector B, Bahria Town, Lah...",2500000,2.2,598.950,1,9,2023,"Bahria Town - Sector B, Bahria Town, Lahore, P...",Down Payment:25 Lac 24 Monthly Installment Per...,Built in year : 2023 | Parking Spaces | Lobby ...,...,NaN,NaN,NaN,4173.971116,"{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Q...",1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2491,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,1,1,1,NaN,NaN
2492,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,1,6,2,NaN,NaN
2494,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2495,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2496,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,1,2,1,NaN,NaN

In [129]:
df.loc[df['Built Year'] == 'TRUE', 'Built Year'] = np.nan

ltiple critical fields:

- **Price / Marla / Area (sqft):** 599 missing each  
- **Floor Number:** 1,503 missing  
- **Total Floors:** 1,468 missing  
- **Built Year:** 1,117 missing  
- **Description:** 599 missing  
- **Features:** 652 missing  
- **Nearby Locations and Other Facilities:** 789 missing  
- **Other Rooms:** 866 missing  
- **Property ID:** Not found for 599 records  
- **Name:** Appears as `#NAME?` in 155 records

## Solve

In [130]:
df.shape

(2991, 90)

In [131]:
df = df.drop_duplicates(subset=["Link"], keep="first")

In [132]:
df = df.dropna(how="all")

In [133]:
df.shape

(2501, 90)

In [134]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

In [135]:
df[df[['Price', 'Marla', 'Area (sqft)']].isna()]

,Property ID,Name,Price,Marla,Area (sqft),Floor Number,Total Floors,Built Year,Address,Description,...,Sui Gas,Boundary Wall,Section - Plot Features,price_per_sqft,Rooms_dict,Bedrooms,Bathrooms,Kitchens,Servant Quarters,Store Rooms
0,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
3096,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
3097,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
3098,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN
943,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN

In [136]:
df = df.dropna(subset=["Price", "Marla", "Area (sqft)"])

In [137]:
df[['Price', 'Marla', 'Area (sqft)']].isna().sum()

Price          0
Marla          0
Area (sqft)    0
dtype: int64

In [138]:
df['Floor Number'].isna().sum()

np.int64(904)

In [139]:
df['Total Floors'].isna().sum()

np.int64(869)

In [140]:
df.loc[df["Floor Number"].isna(), ["Floor Number", "Total Floors"]]

     Floor Number Total Floors
1             NaN           13
10            NaN         TRUE
15            NaN          NaN
16            NaN          NaN
22            NaN          NaN
...           ...          ...
3087          NaN          NaN
3089          NaN          NaN
3091          NaN          NaN
3092          NaN          NaN
3097          NaN          NaN

[904 rows x 2 columns]

In [141]:
df.shape

(2500, 90)

In [142]:
df["Total Floors"] = pd.to_numeric(df["Total Floors"], errors="coerce")
df["Floor Number"] = pd.to_numeric(df["Floor Number"], errors="coerce")

In [143]:
df["Total Floors"] = df["Total Floors"].fillna(
    df.groupby("Address")["Total Floors"].transform("median")
)

In [144]:
df["Total Floors"] = df["Total Floors"].fillna(df["Total Floors"].median())

In [145]:
df["Floor Number"] = df["Floor Number"].fillna(
    df.groupby("Address")["Floor Number"].transform("median")
)

df["Floor Number"] = df["Floor Number"].fillna(df["Floor Number"].median())

In [146]:
df.loc[df["Floor Number"].isna(), ["Floor Number", "Total Floors"]]

Empty DataFrame
Columns: [Floor Number, Total Floors]
Index: []

In [147]:
df['Built Year'].isna().sum()

np.int64(628)

In [148]:
df['Built Year'].value_counts()

Built Year
2025     611
2024     271
2023     115
2026      98
2022      94
2027      78
2018      74
2020      69
2021      67
2017      56
2029      49
2028      46
2015      31
2019      29
1         24
2016      18
2         14
2030      12
2010      11
3         10
2012       9
2000       7
4          6
1992       6
2014       5
2003       4
1998       4
5          4
2005       4
1985       3
2008       3
2011       3
2001       2
1999       2
1990       2
25         2
1986       2
12         2
2004       2
4.5        2
2.5        2
20242      2
15         2
20221      1
20001      1
2002       1
1994       1
202        1
1987       1
2056       1
10         1
1996       1
24         1
2108       1
6          1
8          1
205        1
2007       1
Name: count, dtype: int64

In [149]:
df["Built Year"] = pd.to_numeric(df["Built Year"], errors="coerce").astype("Int64")

TypeError: cannot safely cast non-equivalent float64 to int64

In [ ]:
df.loc[df["Built Year"] == 1 , "Built Year"] = 2025

In [151]:
df['Built Year'].value_counts()

Built Year
2025     611
2024     271
2023     115
2026      98
2022      94
2027      78
2018      74
2020      69
2021      67
2017      56
2029      49
2028      46
2015      31
2019      29
1         24
2016      18
2         14
2030      12
2010      11
3         10
2012       9
2000       7
4          6
1992       6
2014       5
2003       4
1998       4
5          4
2005       4
1985       3
2008       3
2011       3
2001       2
1999       2
1990       2
25         2
1986       2
12         2
2004       2
4.5        2
2.5        2
20242      2
15         2
20221      1
20001      1
2002       1
1994       1
202        1
1987       1
2056       1
10         1
1996       1
24         1
2108       1
6          1
8          1
205        1
2007       1
Name: count, dtype: int64

In [152]:
# df["Built Year"] = pd.to_numeric(df["Built Year"], errors="coerce")
# df.loc[~df["Built Year"].between(1980, 2030), "Built Year"] = np.nan

In [204]:
df['Built Year'].value_counts()

Built Year
2025    611
2024    271
2023    115
2026     98
2022     94
2027     78
2018     74
2020     69
2021     67
2017     56
2029     49
2028     46
2015     31
2019     29
2001     25
2016     18
2002     15
2030     12
2010     11
2003     10
2012      9
2000      7
2004      6
1992      6
2005      5
2014      5
2005      4
2003      4
1998      4
1985      3
2008      3
2011      3
2024      3
1999      2
1986      2
2001      2
1990      2
2015      2
2025      2
2004      2
2012      2
2021      1
1994      1
2002      1
1987      1
1996      1
2010      1
2006      1
2018      1
2008      1
2007      1
Name: count, dtype: int64

In [192]:
df.loc[df["Built Year"] == '1', "Built Year"]=2001

In [203]:
df.loc[df["Built Year"] == '2028', "Link"].iloc[4]

'https://www.zameen.com/Property/gulberg_mm_alam_road_1_bed_residential_apartment_on_main_mm_alam_road-53566621-3850-1.html'

In [206]:
df['Built Year'].isna().sum()

np.int64(633)

In [212]:
df['Features'].value_counts()

Features
Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Security Staff | Other Facilities                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           39
Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Sauna | Jacuzzi | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Communal/Shared Kitchen | Facilities for Disabled                                                                                                                                                                                                                                                                                                                                                                                                                                                                   24
Built in year : 2024 | Parking Spaces : 2 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 1 | Floors in Building : 1 | Elevators : 2 | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Facilities for Disabled | Pets Allowed | Other Facilities    16
Parking Spaces : 2 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 1 | Floors in Building : 1 | Elevators : 2 | Service Elevators in Building | Other Main Features | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Facilities for Disabled | Pets Allowed                                                                                                                                                                                                    13
Built in year : 2025 | Parking Spaces | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities                                                                                                                                                                                                                                                             8
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   ..
Built in year : 2025 | Parking Spaces : 1 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floors in Building | Elevators | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities                                                                           1
Built in year : 2023 | Parking Spaces : 8 | Lobby in Building | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 4 | Floors in Building : 6 | Elevators : 1 | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Conference Room in Building | Intercom | ATM Machines | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Sauna | Jacuzzi | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Communal/Shared Kitchen | Facilities for Disabled                                                                                                                                                                                                                               1
Built in year : 2025 | Parking Spaces | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 2 | Floors in Building : 7 | Elevators : 1 | Service Elevators in Building | Other Main Features | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities                                                                                                                                                                1
Built in year : 2027 | Parking Spaces : 50 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 06 | Floors in Building : 11 | Elevators : 04 | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Other Facilities                                                                             1
Parking Spaces : 1 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor | Floors in Building : 15 | Elevators | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Communal/Shared Kitchen | Facilities for Disabled | Pets Allowed | Other Facilities         1
Name: count, Length: 2094, dtype: int64

In [213]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

In [214]:
import re
import numpy as np
import pandas as pd

kv_map = {
    "parking spaces": "Parking Spaces",
    "floor": "Floor",
    "floors in building": "Floors in Building",
    "elevators": "Elevators",
    "built in year": "Built Year",  # change to "Built in year" if you prefer that column
}

def extract_kv_features(s):
    if pd.isna(s):
        return {}
    out = {}
    parts = [p.strip() for p in str(s).split("|")]
    for p in parts:
        if ":" not in p:
            continue
        key, val = [x.strip() for x in p.split(":", 1)]
        key_l = key.lower()
        if key_l in kv_map:
            m = re.search(r"(-?\d+(\.\d+)?)", val)
            if m:
                out[kv_map[key_l]] = float(m.group(1))
    return out

extracted = df["Features"].apply(extract_kv_features)

for col in set(kv_map.values()):
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")
        df[col] = df[col].fillna(extracted.apply(lambda d: d.get(col, np.nan)))

In [215]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

In [216]:
import re
import pandas as pd

flag_cols = [
    "Lobby in Building", "Double Glazed Windows", "Central Air Conditioning", "Central Heating",
    "Flooring", "Electricity Backup", "Waste Disposal", "Service Elevators in Building",
    "Other Main Features", "Broadband Internet Access", "Satellite or Cable TV Ready",
    "Business Center or Media Room in Building", "Conference Room in Building", "Intercom",
    "ATM Machines", "Other Business and Communication Facilities", "Community Lawn or Garden",
    "Community Swimming Pool", "Community Gym", "First Aid or Medical Centre", "Day Care Centre",
    "Kids Play Area", "Barbeque Area", "Mosque", "Community Centre", "Other Community Facilities",
    "Sauna", "Jacuzzi", "Other Healthcare and Recreation Facilities", "Nearby Schools",
    "Nearby Hospitals", "Nearby Shopping Malls", "Nearby Restaurants",
    "Distance From Airport (kms)", "Nearby Public Transport Service", "Other Nearby Places",
    "Maintenance Staff", "Security Staff", "Laundry or Dry Cleaning Facility",
    "Facilities for Disabled", "Pets Allowed", "Other Facilities", "Furnished",
    "Communal/Shared Kitchen", "Pets Not Allowed", "Possesion", "Corner", "Park Facing",
    "Disputed", "File", "Balloted", "Sewerage", "Electricity", "Water Supply", "Sui Gas",
    "Boundary Wall"
]
flag_cols = [c for c in flag_cols if c in df.columns]

def norm(s):
    return re.sub(r"\s+", " ", s.strip().lower())

def extract_flags(s):
    if pd.isna(s):
        return set()
    parts = [p.strip() for p in str(s).split("|")]
    return {norm(p) for p in parts if p and ":" not in p}

flag_sets = df["Features"].apply(extract_flags)

for col in flag_cols:
    ncol = norm(col)
    mask = df[col].isna() & df["Features"].notna()
    df.loc[mask, col] = flag_sets[mask].apply(lambda s: ncol in s)

In [217]:
df.columns

Index(['Property ID', 'Name', 'Price', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Other Rooms', 'Link',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Communal/Shared Kitchen',
       'Built in year', 'Pets Not Allowed', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall',
       'Section - Plot Features', 'price_per_sqft', 'Rooms_dict', 'Bedrooms',
       'Bathrooms', 'Kitchens', 'Servant Quarters', 'Store Rooms'],
      dtype='object')

In [218]:
df.to_csv("flats_cleaning.csv")