In [35]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [36]:
df=pd.read_csv("lahore_flats_final.csv")

## Data Cleaning

In [37]:
df.sample(10)

,Property ID,Society,Society Link,Name,Page Title,Price,Area,Bedrooms,Baths,Floor Number,...,Communal/Shared Kitchen,Unnamed: 76,Unnamed: 77,Unnamed: 78,Unnamed: 79,Unnamed: 80,Unnamed: 81,Unnamed: 82,Unnamed: 83,Unnamed: 84
563,1,Askari,https://www.zameen.com/Flats_Apartments/Lahore...,"3 BHK Flat for sale in Askari, Lahore","Askari 10 - Sector F, Askari 10, Askari, Lahor...",PKR 3.9 Crore,10 Marla,3.0,3.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,1,Bahria Town,https://www.zameen.com/Flats_Apartments/Lahore...,"1 BHK Flat for sale in Bahria Town, Lahore","Bahria Town - Sector F, Bahria Town, Lahore, P...",PKR 67.91 Lakh,2.2 Marla,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2370,1,DHA Defence,https://www.zameen.com/Flats_Apartments/Lahore...,"2 BHK Flat for sale in DHA Defence, Lahore","DHA Defence, Lahore, Punjab",PKR 3.15 Crore,5.4 Marla,2.0,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1586,1,Gulberg,https://www.zameen.com/Flats_Apartments/Lahore...,"Flat for sale in Gulberg, Lahore","CBD Punjab (PCBDDA), Main Boulevard Gulberg, G...",PKR 2.16 Crore,2 Marla,NaN,1.0,22,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2113,1,Raiwind Road,https://www.zameen.com/Flats_Apartments/Lahore...,"Flat for sale in Raiwind Road, Lahore","Al-Kabir Town - Phase 2, Al-Kabir Town, Raiwin...",PKR 37.5 Lakh,1.2 Marla,NaN,1.0,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,1,Askari,https://www.zameen.com/Flats_Apartments/Lahore...,"3 BHK Flat for sale in Askari, Lahore","Askari 11 - Sector B Apartments, Askari 11, As...",PKR 2.45 Crore,10 Marla,3.0,3.0,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
694,1,Askari,https://www.zameen.com/Flats_Apartments/Lahore...,"4 BHK Flat for sale in Askari, Lahore","Askari 10, Askari, Lahore, Punjab",PKR 4.2 Crore,12.2 Marla,4.0,5.0,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1782,1,Gulberg,https://www.zameen.com/Flats_Apartments/Lahore...,"2 BHK Flat for sale in Gulberg, Lahore","Zafar Ali Road, Gulberg, Lahore, Punjab",PKR 1.71 Crore,1.8 Marla,2.0,2.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2459,1,DHA Defence,https://www.zameen.com/Flats_Apartments/Lahore...,"1 BHK Flat for sale in DHA Defence, Lahore","DHA Phase 3 - Block XX, DHA Phase 3, DHA Defen...",PKR 97 Lakh,1.2 Marla,1.0,1.0,TRUE,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2851,1,Shanghai Road,https://www.zameen.com/Flats_Apartments/Lahore...,"2 BHK Flat for sale in Shanghai Road, Lahore","Defence View Apartments, Shanghai Road, Lahore...",PKR 1.8 Crore,6.6 Marla,2.0,2.0,NaN,...,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [38]:
df.duplicated().sum()

np.int64(0)

In [39]:
df.shape

(3139, 85)

In [40]:
pd.set_option("display.max_rows", None)
df.isna().sum().sort_values(ascending=False)

Unnamed: 80                                        3139
Unnamed: 81                                        3139
Unnamed: 82                                        3139
Unnamed: 83                                        3139
Unnamed: 76                                        3139
Unnamed: 77                                        3139
Unnamed: 78                                        3139
Unnamed: 79                                        3139
Unnamed: 84                                        3138
Pets Not Allowed                                   2977
Pets Allowed                                       2546
Communal/Shared Kitchen                            2215
Laundry or Dry Cleaning Facility                   1887
Other Healthcare and Recreation Facilities         1437
Other Business and Communication Facilities        1325
Other Community Facilities                         1319
Furnished                                          1274
Facilities for Disabled                            1194
Floor                                              1163
Floor Number                                       1163
Conference Room in Building                        1157
Business Center or Media Room in Building          1143
Service Elevators in Building                      1122
Jacuzzi                                            1101
ATM Machines                                       1097
Floors in Building                                 1091
Total Floors                                       1091
Sauna                                              1066
Other Facilities                                   1051
Elevators                                          1006
Other Main Features                                 954
Lobby in Building                                   928
Maintenance Staff                                   910
Section - Healthcare Recreational                   799
Central Heating                                     788
Central Air Conditioning                            744
Built Year                                          692
Built in year                                       692
Community Swimming Pool                             663
Intercom                                            648
Double Glazed Windows                               597
Waste Disposal                                      580
Community Centre                                    538
Day Care Centre                                     522
Security Staff                                      507
Electricity Backup                                  497
Barbeque Area                                       496
Section - Other Facilities                          495
Community Gym                                       493
Community Lawn or Garden                            473
Distance From Airport (kms)                         469
First Aid or Medical Centre                         463
Parking Spaces                                      456
Other Nearby Places                                 445
Satellite or Cable TV Ready                         443
Mosque                                              427
Other Rooms                                         427
Kids Play Area                                      425
Broadband Internet Access                           397
Flooring                                            382
Section - Business and Communication                364
Section - Community Features                        360
Bedrooms                                            358
Nearby Public Transport Service                     310
Section - Rooms                                     264
Nearby Restaurants                                  260
Nearby Schools                                      254
Nearby Shopping Malls                               254
Nearby Hospitals                                    253
Section - Nearby Locations and Other Facilities     237
Nearby Locations and Other Facilities               237
Section - Main Features                             167
Baths                                                98
Features                                             79
Price                                                21
Description                                          21
Area                                                 21
Link                                                  0
Rooms                                                 0
Address                                               0
Property ID                                           0
Society                                               0
Society Link                                          0
Name                                                  0
Page Title                                            0
dtype: int64

In [ ]:
# always drop unnamed columns
unnamed = [c for c in df.columns if c.startswith("Unnamed")]
df = df.drop(columns=unnamed)

# drop columns with >50% missing
thresh = len(df) * 0.50
drop_50 = df.columns[df.isna().sum() > thresh]
df = df.drop(columns=drop_50)

In [42]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Area', 'Bedrooms', 'Baths', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Lobby in Building',
       'Double Glazed Windows', 'Central Air Conditioning', 'Central Heating',
       'Flooring', 'Electricity Backup', 'Waste Disposal', 'Floor',
       'Floors in Building', 'Elevators', 'Service Elevators in Building',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Community Lawn or Garden', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Other Facilities', 'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Other Main Features',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Swimming Pool', 'Other Community Facilities',
       'Other Healthcare and Recreation Facilities',
       'Section - Healthcare Recreational', 'Furnished', 'Intercom', 'Sauna',
       'Jacuzzi', 'Facilities for Disabled'],
      dtype='object')

In [43]:
pd.set_option("display.max_rows", None)
df.isna().sum().sort_values(ascending=False)
# half 1251

Other Healthcare and Recreation Facilities         1437
Other Business and Communication Facilities        1325
Other Community Facilities                         1319
Furnished                                          1274
Facilities for Disabled                            1194
Floor Number                                       1163
Floor                                              1163
Conference Room in Building                        1157
Business Center or Media Room in Building          1143
Service Elevators in Building                      1122
Jacuzzi                                            1101
ATM Machines                                       1097
Floors in Building                                 1091
Total Floors                                       1091
Sauna                                              1066
Other Facilities                                   1051
Elevators                                          1006
Other Main Features                                 954
Lobby in Building                                   928
Maintenance Staff                                   910
Section - Healthcare Recreational                   799
Central Heating                                     788
Central Air Conditioning                            744
Built Year                                          692
Built in year                                       692
Community Swimming Pool                             663
Intercom                                            648
Double Glazed Windows                               597
Waste Disposal                                      580
Community Centre                                    538
Day Care Centre                                     522
Security Staff                                      507
Electricity Backup                                  497
Barbeque Area                                       496
Section - Other Facilities                          495
Community Gym                                       493
Community Lawn or Garden                            473
Distance From Airport (kms)                         469
First Aid or Medical Centre                         463
Parking Spaces                                      456
Other Nearby Places                                 445
Satellite or Cable TV Ready                         443
Other Rooms                                         427
Mosque                                              427
Kids Play Area                                      425
Broadband Internet Access                           397
Flooring                                            382
Section - Business and Communication                364
Section - Community Features                        360
Bedrooms                                            358
Nearby Public Transport Service                     310
Section - Rooms                                     264
Nearby Restaurants                                  260
Nearby Shopping Malls                               254
Nearby Schools                                      254
Nearby Hospitals                                    253
Section - Nearby Locations and Other Facilities     237
Nearby Locations and Other Facilities               237
Section - Main Features                             167
Baths                                                98
Features                                             79
Description                                          21
Price                                                21
Area                                                 21
Page Title                                            0
Society                                               0
Society Link                                          0
Name                                                  0
Property ID                                           0
Link                                                  0
Rooms                                                 0
Address                                               0
dtype: int64

In [44]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Area', 'Bedrooms', 'Baths', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Lobby in Building',
       'Double Glazed Windows', 'Central Air Conditioning', 'Central Heating',
       'Flooring', 'Electricity Backup', 'Waste Disposal', 'Floor',
       'Floors in Building', 'Elevators', 'Service Elevators in Building',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Community Lawn or Garden', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Other Facilities', 'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Other Main Features',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Swimming Pool', 'Other Community Facilities',
       'Other Healthcare and Recreation Facilities',
       'Section - Healthcare Recreational', 'Furnished', 'Intercom', 'Sauna',
       'Jacuzzi', 'Facilities for Disabled'],
      dtype='object')

In [24]:
import re
import numpy as np
import pandas as pd

def extract_floor(s):
    if pd.isna(s):
        return np.nan
    m = re.search(r"\bFloor\s*:\s*(\d+)", str(s))
    return float(m.group(1)) if m else np.nan

df["Floor_from_Features"] = df["Features"].apply(extract_floor)

# Compare with existing Floor column
df["Floor"] = pd.to_numeric(df["Floor"], errors="coerce")
(df["Floor_from_Features"] == df["Floor"]).value_counts(dropna=False)

False    1742
True     1397
Name: count, dtype: int64

In [26]:
df['Floor_from_Features'].isna().sum()

np.int64(1742)

In [32]:
df['Floor'].isna().sum()

np.int64(1742)

In [30]:
df['Floor_from_Features'].iloc[100]

np.float64(nan)

In [33]:
df = df.drop(columns=["Floor_from_Features"])

In [45]:
df.shape

(3139, 72)

In [46]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Area', 'Bedrooms', 'Baths', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Lobby in Building',
       'Double Glazed Windows', 'Central Air Conditioning', 'Central Heating',
       'Flooring', 'Electricity Backup', 'Waste Disposal', 'Floor',
       'Floors in Building', 'Elevators', 'Service Elevators in Building',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Community Lawn or Garden', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Other Facilities', 'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Other Main Features',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Swimming Pool', 'Other Community Facilities',
       'Other Healthcare and Recreation Facilities',
       'Section - Healthcare Recreational', 'Furnished', 'Intercom', 'Sauna',
       'Jacuzzi', 'Facilities for Disabled'],
      dtype='object')

In [48]:
df['Facilities for Disabled'].value_counts()

Facilities for Disabled
True    1945
Name: count, dtype: int64

In [49]:
df['Sauna'].value_counts()

Sauna
True    2073
Name: count, dtype: int64

In [51]:
df['Intercom'].value_counts()

Intercom
True    2491
Name: count, dtype: int64

In [52]:
df['Furnished'].value_counts()

Furnished
True    1865
Name: count, dtype: int64

In [55]:
drop_cols = [
    "Facilities for Disabled", "Jacuzzi", "Sauna", "Intercom", "Furnished",
    "Section - Healthcare Recreational", "Other Healthcare and Recreation Facilities",
    "Other Community Facilities", "Community Swimming Pool",
    "Other Business and Communication Facilities", "ATM Machines",
    "Conference Room in Building", "Business Center or Media Room in Building",
    "Other Main Features", "Section - Other Facilities",
    "Section - Nearby Locations and Other Facilities", "Section - Community Features",
    "Section - Business and Communication", "Nearby Locations and Other Facilities",
    "Lobby in Building", "Double Glazed Windows", "Central Air Conditioning",
    "Central Heating", "Flooring", "Electricity Backup", "Waste Disposal",
    "Elevators", "Service Elevators in Building",
    "Broadband Internet Access", "Satellite or Cable TV Ready",
    "Community Lawn or Garden", "Community Gym", "First Aid or Medical Centre",
    "Day Care Centre", "Kids Play Area", "Barbeque Area", "Mosque",
    "Community Centre", "Nearby Schools", "Nearby Hospitals",
    "Nearby Shopping Malls", "Nearby Restaurants", "Distance From Airport (kms)",
    "Nearby Public Transport Service", "Other Nearby Places",
    "Maintenance Staff", "Security Staff", "Other Facilities",
    "Section - Main Features", "Section - Rooms"
]

df = df.drop(columns=drop_cols, errors="ignore")

In [56]:
df.shape

(3139, 22)

In [57]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Area', 'Bedrooms', 'Baths', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Features', 'Rooms',
       'Other Rooms', 'Link', 'Built in year', 'Parking Spaces', 'Floor',
       'Floors in Building'],
      dtype='object')

In [66]:
df[df['Price'].isnull()]['Link'].iloc[0]

'https://www.zameen.com/new-projects/zameen_neo-2230.html'

In [65]:
df[df['Price'].isnull()].iloc[0]

Property ID                                                        2230
Society                                                         Gulberg
Society Link          https://www.zameen.com/Flats_Apartments/Lahore...
Name                                   Flat for sale in Gulberg, Lahore
Page Title                                                   Not listed
Price                                                               NaN
Area                                                                NaN
Bedrooms                                                            NaN
Baths                                                               NaN
Floor Number                                                        NaN
Total Floors                                                        NaN
Built Year                                                          NaN
Address                                                      Not listed
Description                                                         NaN
Features                                                            NaN
Rooms                                                                {}
Other Rooms                                                         NaN
Link                  https://www.zameen.com/new-projects/zameen_neo...
Built in year                                                       NaN
Parking Spaces                                                      NaN
Floor                                                               NaN
Floors in Building                                                  NaN
Name: 1526, dtype: object

In [67]:
df.shape

(3139, 22)

In [68]:
df = df[df["Price"].notna()].copy()

In [69]:
df.shape

(3118, 22)

In [70]:
df['Price'].value_counts()

Price
PKR 75 Lakh        65
PKR 65 Lakh        59
PKR 60 Lakh        57
PKR 2.85 Crore     54
PKR 80 Lakh        54
PKR 4.5 Crore      46
PKR 4.25 Crore     44
PKR 45 Lakh        42
PKR 1.25 Crore     41
PKR 70 Lakh        41
PKR 55 Lakh        39
PKR 3.5 Crore      36
PKR 1.2 Crore      35
PKR 50 Lakh        33
PKR 85 Lakh        33
PKR 1 Crore        32
PKR 95 Lakh        31
PKR 1.3 Crore      30
PKR 2.8 Crore      30
PKR 3.25 Crore     30
PKR 2.75 Crore     30
PKR 4.65 Crore     29
PKR 3.75 Crore     28
PKR 1.8 Crore      27
PKR 90 Lakh        27
PKR 4 Crore        26
PKR 4.6 Crore      25
PKR 2.5 Crore      25
PKR 1.5 Crore      25
PKR 3.85 Crore     25
PKR 1.1 Crore      25
PKR 3.8 Crore      24
PKR 4.35 Crore     24
PKR 3.4 Crore      24
PKR 1.35 Crore     24
PKR 3.1 Crore      23
PKR 3.35 Crore     23
PKR 4.75 Crore     22
PKR 3.6 Crore      22
PKR 4.4 Crore      22
PKR 3 Crore        21
PKR 3.3 Crore      21
PKR 1.4 Crore      20
PKR 4.3 Crore      20
PKR 4.45 Crore     20
PKR 2.9 Crore      20
PKR 2.65 Crore     18
PKR 2.7 Crore      18
PKR 3.65 Crore     18
PKR 4.2 Crore      18
PKR 3.2 Crore      18
PKR 2 Crore        17
PKR 68.44 Lakh     17
PKR 48 Lakh        17
PKR 1.55 Crore     16
PKR 5 Crore        16
PKR 2.6 Crore      16
PKR 1.6 Crore      16
PKR 1.15 Crore     16
PKR 1.02 Crore     16
PKR 62 Lakh        16
PKR 68 Lakh        15
PKR 2.4 Crore      15
PKR 3.7 Crore      15
PKR 3.45 Crore     14
PKR 3.9 Crore      14
PKR 4.15 Crore     14
PKR 5.5 Crore      14
PKR 1.45 Crore     14
PKR 3.15 Crore     13
PKR 1.21 Crore     13
PKR 2.95 Crore     13
PKR 2.25 Crore     13
PKR 4.55 Crore     12
PKR 1.05 Crore     12
PKR 52 Lakh        12
PKR 2.15 Crore     11
PKR 88 Lakh        11
PKR 4.8 Crore      11
PKR 49 Lakh        11
PKR 4.7 Crore      11
PKR 1.23 Crore     10
PKR 35 Lakh        10
PKR 4.1 Crore      10
PKR 99 Lakh        10
PKR 1.79 Crore     10
PKR 3.55 Crore     10
PKR 1.7 Crore       9
PKR 2.2 Crore       9
PKR 66 Lakh         9
PKR 2.55 Crore      9
PKR 4.9 Crore       9
PKR 2.45 Crore      9
PKR 67.91 Lakh      9
PKR 1.65 Crore      9
PKR 42 Lakh         9
PKR 1.47 Crore      9
PKR 2.3 Crore       9
PKR 40 Lakh         9
PKR 38 Lakh         9
PKR 3.58 Crore      8
PKR 1.48 Crore      8
PKR 1.28 Crore      8
PKR 53 Lakh         8
PKR 72 Lakh         8
PKR 97.5 Lakh       8
PKR 2.1 Crore       7
PKR 5.3 Crore       7
PKR 2.88 Crore      7
PKR 1.27 Crore      7
PKR 54 Lakh         7
PKR 79 Lakh         7
PKR 2.83 Crore      7
PKR 51 Lakh         7
PKR 94.5 Lakh       7
PKR 1.85 Crore      7
PKR 1.95 Crore      7
PKR 1.89 Crore      7
PKR 76.5 Lakh       6
PKR 58 Lakh         6
PKR 76 Lakh         6
PKR 2.78 Crore      6
PKR 67.69 Lakh      6
PKR 47 Lakh         6
PKR 3.95 Crore      6
PKR 78 Lakh         6
PKR 1.9 Crore       6
PKR 30 Lakh         6
PKR 82 Lakh         6
PKR 2.49 Crore      6
PKR 90.75 Lakh      6
PKR 2.35 Crore      6
PKR 4.05 Crore      6
PKR 1.34 Crore      6
PKR 2.89 Crore      5
PKR 68.04 Lakh      5
PKR 69 Lakh         5
PKR 5.1 Crore       5
PKR 3.83 Crore      5
PKR 98 Lakh         5
PKR 79.05 Lakh      5
PKR 64 Lakh         5
PKR 4.28 Crore      5
PKR 1.33 Crore      5
PKR 56 Lakh         5
PKR 4.85 Crore      5
PKR 1.75 Crore      5
PKR 2.16 Crore      5
PKR 44.69 Lakh      5
PKR 98.25 Lakh      5
PKR 60.82 Lakh      5
PKR 86 Lakh         5
PKR 4.95 Crore      5
PKR 5.25 Crore      5
PKR 6 Crore         5
PKR 85.7 Lakh       5
PKR 67 Lakh         5
PKR 3.05 Crore      5
PKR 57 Lakh         4
PKR 32 Lakh         4
PKR 34 Lakh         4
PKR 85.57 Lakh      4
PKR 1.26 Crore      4
PKR 1.57 Crore      4
PKR 84 Lakh         4
PKR 1.52 Crore      4
PKR 3.03 Crore      4
PKR 9.5 Crore       4
PKR 3.78 Crore      4
PKR 31 Lakh         4
PKR 7 Crore         4
PKR 2.19 Crore      4
PKR 80.73 Lakh      4
PKR 80.11 Lakh      4
PKR 63 Lakh         4
PKR 6.5 Crore       4
PKR 1.59 Crore      4
PKR 3.88 Crore      4
PKR 65.98 Lakh      4
PKR 46 Lakh         4
PKR 1.29 Crore      4
PKR 1.96 Crore      4
PKR 83.21 Lakh      4
PKR 79.18 Lakh      4
PKR 42.12 Lakh      4
PKR 1.49 Crore      4
PKR 70.2 Lakh       4
PKR 37 Lakh         4
PKR 4.23 Crore      4
PKR 2.77 Crore      4
PKR 1.87 Crore      4
PKR 36 Lakh         3
PKR 2.79 Crore      3
PKR 1.18 Crore      3
PKR 7.15 Crore      3
PKR 2.41 Crore      3
PKR 2.69 Crore      3
PKR 1.38 Crore      3
PKR 39 Lakh         3
PKR 87 Lakh         3
PKR 37.95 Lakh      3
PKR 1.03 Crore      3
PKR 59 Lakh         3
PKR 93 Lakh         3
PKR 3.69 Crore      3
PKR 2.44 Crore      3
PKR 1.01 Crore      3
PKR 1.81 Crore      3
PKR 2.42 Crore      3
PKR 1.43 Crore      3
PKR 91.7 Lakh       3
PKR 9 Crore         3
PKR 37.5 Lakh       3
PKR 27 Lakh         3
PKR 1.42 Crore      3
PKR 1.94 Crore      3
PKR 9.8 Crore       3
PKR 1.97 Crore      3
PKR 52.2 Lakh       3
PKR 1.32 Crore      3
PKR 61 Lakh         3
PKR 72.5 Lakh       3
PKR 40.88 Lakh      3
PKR 81 Lakh         3
PKR 4.52 Crore      3
PKR 30.51 Lakh      3
PKR 3.67 Crore      2
PKR 82.61 Lakh      2
PKR 64.5 Lakh       2
PKR 1.17 Crore      2
PKR 65.5 Lakh       2
PKR 71.5 Lakh       2
PKR 5.45 Crore      2
PKR 3.98 Crore      2
PKR 53.12 Lakh      2
PKR 1.78 Crore      2
PKR 56.5 Lakh       2
PKR 74 Lakh         2
PKR 1.22 Crore      2
PKR 7.4 Crore       2
PKR 1.39 Crore      2
PKR 42.26 Lakh      2
PKR 79.5 Lakh       2
PKR 90.65 Lakh      2
PKR 1.36 Crore      2
PKR 3.62 Crore      2
PKR 42.3 Lakh       2
PKR 29 Lakh         2
PKR 63.33 Lakh      2
PKR 59.17 Lakh      2
PKR 73 Lakh         2
PKR 63.75 Lakh      2
PKR 70.65 Lakh      2
PKR 67.62 Lakh      2
PKR 3.09 Crore      2
PKR 3.97 Crore      2
PKR 2.73 Crore      2
PKR 2.99 Crore      2
PKR 4.17 Crore      2
PKR 59.5 Lakh       2
PKR 56.4 Lakh       2
PKR 3.12 Crore      2
PKR 5.05 Crore      2
PKR 5.15 Crore      2
PKR 5.65 Crore      2
PKR 83 Lakh         2
PKR 1.62 Crore      2
PKR 2.12 Crore      2
PKR 93.77 Lakh      2
PKR 3.06 Crore      2
PKR 85.69 Lakh      2
PKR 1.98 Crore      2
PKR 1.41 Crore      2
PKR 1.63 Crore      2
PKR 71 Lakh         2
PKR 1.19 Crore      2
PKR 5.7 Crore       2
PKR 45.23 Lakh      2
PKR 41.17 Lakh      2
PKR 52.92 Lakh      2
PKR 3.43 Crore      2
PKR 1.64 Crore      2
PKR 1.13 Crore      2
PKR 7.25 Crore      2
PKR 4.07 Crore      2
PKR 4.08 Crore      2
PKR 5.6 Crore       2
PKR 4.41 Crore      2
PKR 2.82 Crore      2
PKR 4.48 Crore      2
PKR 60.8 Lakh       2
PKR 86.78 Lakh      2
PKR 2.03 Crore      2
PKR 8 Crore         2
PKR 7.74 Crore      2
PKR 2.56 Crore      2
PKR 1.11 Crore      2
PKR 2.04 Crore      2
PKR 87.5 Lakh       2
PKR 44 Lakh         2
PKR 2.86 Crore      2
PKR 5.4 Crore       2
PKR 48.5 Lakh       2
PKR 3.48 Crore      2
PKR 68.4 Lakh       1
PKR 2.11 Crore      1
PKR 95.35 Lakh      1
PKR 50.95 Lakh      1
PKR 39.45 Lakh      1
PKR 93.12 Lakh      1
PKR 90.08 Lakh      1
PKR 1.06 Crore      1
PKR 37.44 Lakh      1
PKR 41.4 Lakh       1
PKR 1.24 Crore      1
PKR 1.88 Crore      1
PKR 94 Lakh         1
PKR 88.44 Lakh      1
PKR 26 Lakh         1
PKR 4.06 Crore      1
PKR 1.53 Crore      1
PKR 1.04 Crore      1
PKR 3.99 Crore      1
PKR 76.12 Lakh      1
PKR 56.21 Lakh      1
PKR 1.58 Crore      1
PKR 98.5 Lakh       1
PKR 29.5 Lakh       1
PKR 51.62 Lakh      1
PKR 26.5 Lakh       1
PKR 27.5 Lakh       1
PKR 2.39 Crore      1
PKR 2.47 Crore      1
PKR 1.08 Crore      1
PKR 4.57 Crore      1
PKR 5.92 Crore      1
PKR 3.33 Crore      1
PKR 5.21 Crore      1
PKR 4.92 Crore      1
PKR 82.8 Lakh       1
PKR 94.06 Lakh      1
PKR 70.25 Lakh      1
PKR 4.37 Crore      1
PKR 4.61 Crore      1
PKR 85.88 Lakh      1
PKR 5.28 Crore      1
PKR 2.97 Crore      1
PKR 1.83 Crore      1
PKR 8.14 Crore      1
PKR 1.69 Crore      1
PKR 8.05 Crore      1
PKR 79.74 Lakh      1
PKR 85.35 Lakh      1
PKR 74.89 Lakh      1
PKR 3.28 Crore      1
PKR 6.25 Crore      1
PKR 11.95 Crore     1
PKR 2.08 Crore      1
PKR 4.99 Crore      1
PKR 4.67 Crore      1
PKR 5.86 Crore      1
PKR 3.89 Crore      1
PKR 4.78 Crore      1
PKR 3.79 Crore      1
PKR 5.33 Crore      1
PKR 6.9 Crore       1
PKR 2.05 Crore      1
PKR 4.16 Crore      1
PKR 4.72 Crore      1
PKR 2.68 Crore      1
PKR 4.12 Crore      1
PKR 1.71 Crore      1
PKR 3.81 Crore      1
PKR 2.06 Crore      1
PKR 89.45 Lakh      1
PKR 98.54 Lakh      1
PKR 4.74 Crore      1
PKR 3.49 Crore      1
PKR 2.34 Crore      1
PKR 6.1 Crore       1
PKR 11 Crore        1
PKR 4.19 Crore      1
PKR 77.45 Lakh      1
PKR 94.85 Lakh      1
PKR 30.01 Lakh      1
PKR 3.18 Crore      1
PKR 44.73 Lakh      1
PKR 5.18 Crore      1
PKR 1.54 Crore      1
PKR 1.61 Crore      1
PKR 3.13 Crore      1
PKR 6.86 Crore      1
PKR 4.46 Crore      1
PKR 4.71 Crore      1
PKR 2.61 Crore      1
PKR 1.09 Crore      1
PKR 2.14 Crore      1
PKR 5.39 Crore      1
PKR 1.99 Crore      1
PKR 77.24 Lakh      1
PKR 50.85 Lakh      1
PKR 74.25 Lakh      1
PKR 2.13 Crore      1
PKR 1.86 Crore      1
PKR 5.03 Crore      1
PKR 2.91 Crore      1
PKR 77.51 Lakh      1
PKR 2.66 Crore      1
PKR 76.66 Lakh      1
PKR 95.22 Lakh      1
PKR 49.68 Lakh      1
PKR 62.25 Lakh      1
PKR 74.24 Lakh      1
PKR 91.58 Lakh      1
PKR 46.34 Lakh      1
PKR 44.1 Lakh       1
PKR 56.7 Lakh       1
PKR 45.62 Lakh      1
PKR 4.47 Crore      1
PKR 5.22 Crore      1
PKR 4.79 Crore      1
PKR 5.97 Crore      1
PKR 64.65 Lakh      1
PKR 32.5 Lakh       1
PKR 90.09 Lakh      1
PKR 90.5 Lakh       1
PKR 2.38 Crore      1
PKR 61.8 Lakh       1
PKR 2.71 Crore      1
PKR 3.27 Crore      1
PKR 3.19 Crore      1
PKR 3.22 Crore      1
PKR 4.44 Crore      1
PKR 2.09 Crore      1
PKR 2.51 Crore      1
PKR 3.51 Crore      1
PKR 3.21 Crore      1
PKR 34.25 Lakh      1
PKR 74.5 Lakh       1
PKR 71.48 Lakh      1
PKR 89.75 Lakh      1
PKR 80.55 Lakh      1
PKR 85.4 Lakh       1
PKR 86.4 Lakh       1
PKR 57.92 Lakh      1
PKR 42.5 Lakh       1
PKR 76.7 Lakh       1
PKR 48.64 Lakh      1
PKR 51.63 Lakh      1
PKR 45.88 Lakh      1
PKR 43 Lakh         1
PKR 76.75 Lakh      1
PKR 65.55 Lakh      1
PKR 79.54 Lakh      1
PKR 71.4 Lakh       1
PKR 72.44 Lakh      1
PKR 43.2 Lakh       1
PKR 44.88 Lakh      1
PKR 69.9 Lakh       1
PKR 66.6 Lakh       1
PKR 62.05 Lakh      1
PKR 80.07 Lakh      1
PKR 42.64 Lakh      1
PKR 93.28 Lakh      1
PKR 57.5 Lakh       1
PKR 2.87 Crore      1
PKR 3.17 Crore      1
PKR 2.59 Crore      1
PKR 57.6 Lakh       1
PKR 64.64 Lakh      1
PKR 32.2 Lakh       1
PKR 34.85 Lakh      1
PKR 1.16 Crore      1
PKR 1.92 Crore      1
PKR 46.8 Lakh       1
PKR 5.85 Crore      1
PKR 7.1 Crore       1
PKR 7.05 Crore      1
PKR 8.95 Crore      1
PKR 10 Crore        1
PKR 3.08 Crore      1
PKR 9.25 Crore      1
PKR 5.2 Crore       1
PKR 62.75 Lakh      1
PKR 58.5 Lakh       1
PKR 95.4 Lakh       1
PKR 85.86 Lakh      1
PKR 53.3 Lakh       1
PKR 90.44 Lakh      1
PKR 91 Lakh         1
PKR 37.96 Lakh      1
PKR 38.92 Lakh      1
PKR 97 Lakh         1
PKR 2.24 Crore      1
PKR 2.01 Crore      1
PKR 6.4 Crore       1
PKR 3.52 Crore      1
PKR 7.2 Crore       1
PKR 1.51 Crore      1
PKR 5.99 Crore      1
PKR 9.1 Crore       1
PKR 8.59 Crore      1
PKR 1.77 Crore      1
PKR 2.84 Crore      1
PKR 97.44 Lakh      1
PKR 54.5 Lakh       1
PKR 42.52 Lakh      1
PKR 49.5 Lakh       1
PKR 1.14 Crore      1
PKR 93.8 Lakh       1
PKR 27.72 Lakh      1
PKR 32.19 Lakh      1
PKR 27.9 Lakh       1
PKR 28 Lakh         1
PKR 2.72 Crore      1
PKR 31.54 Lakh      1
PKR 46.52 Lakh      1
PKR 25 Lakh         1
PKR 38.5 Lakh       1
PKR 78.6 Lakh       1
PKR 31.4 Lakh       1
PKR 38.25 Lakh      1
PKR 35.16 Lakh      1
PKR 87.9 Lakh       1
PKR 44.5 Lakh       1
PKR 3.32 Crore      1
PKR 2.98 Crore      1
PKR 3.68 Crore      1
PKR 5.29 Crore      1
PKR 3.73 Crore      1
PKR 66.9 Lakh       1
PKR 67.64 Lakh      1
PKR 73.75 Lakh      1
PKR 99.6 Lakh       1
PKR 60.92 Lakh      1
PKR 78.35 Lakh      1
PKR 54.75 Lakh      1
PKR 29.25 Lakh      1
PKR 44.99 Lakh      1
Name: count, dtype: int64

In [71]:
import re
import numpy as np

def price_to_crore(x):
    if pd.isna(x):
        return np.nan
    s = str(x).lower().replace(",", "").replace("pkr", "").strip()
    m = re.search(r"(\d+(?:\.\d+)?)\s*(crore|lakh)", s)
    if not m:
        return np.nan
    val = float(m.group(1))
    unit = m.group(2)
    return val if unit == "crore" else val / 100  # 100 lakh = 1 crore

df["price_crore"] = df["Price"].apply(price_to_crore)

In [74]:
print(df['price_crore'].iloc[900])
print(df['Price'].iloc[900])

4.25
PKR 4.25 Crore

In [75]:
df = df.drop(columns=["Price"])
df = df.rename(columns={"price_crore": "Price"})

In [76]:
df['Price'].value_counts()

Price
0.7500     65
0.6500     59
0.6000     57
2.8500     54
0.8000     54
4.5000     46
4.2500     44
0.4500     42
1.2500     41
0.7000     41
0.5500     39
3.5000     36
1.2000     35
0.5000     33
0.8500     33
1.0000     32
0.9500     31
1.3000     30
2.8000     30
3.2500     30
2.7500     30
4.6500     29
3.7500     28
1.8000     27
0.9000     27
4.0000     26
4.6000     25
2.5000     25
1.5000     25
3.8500     25
1.1000     25
3.8000     24
4.3500     24
3.4000     24
1.3500     24
3.1000     23
3.3500     23
4.7500     22
3.6000     22
4.4000     22
3.0000     21
3.3000     21
1.4000     20
4.3000     20
4.4500     20
2.9000     20
2.6500     18
2.7000     18
3.6500     18
4.2000     18
3.2000     18
2.0000     17
0.6844     17
0.4800     17
1.5500     16
5.0000     16
2.6000     16
1.6000     16
1.1500     16
1.0200     16
0.6200     16
0.6800     15
2.4000     15
3.7000     15
3.4500     14
3.9000     14
4.1500     14
5.5000     14
1.4500     14
3.1500     13
1.2100     13
2.9500     13
2.2500     13
4.5500     12
1.0500     12
0.5200     12
2.1500     11
0.8800     11
4.8000     11
0.4900     11
4.7000     11
1.2300     10
0.3500     10
4.1000     10
0.9900     10
1.7900     10
3.5500     10
1.7000      9
2.2000      9
0.6600      9
2.5500      9
4.9000      9
2.4500      9
0.6791      9
1.6500      9
0.4200      9
1.4700      9
2.3000      9
0.4000      9
0.3800      9
3.5800      8
1.4800      8
1.2800      8
0.5300      8
0.7200      8
0.9750      8
2.1000      7
5.3000      7
2.8800      7
1.2700      7
0.5400      7
0.7900      7
2.8300      7
0.5100      7
0.9450      7
1.8500      7
1.9500      7
1.8900      7
0.7650      6
0.5800      6
0.7600      6
2.7800      6
0.6769      6
0.4700      6
3.9500      6
0.7800      6
1.9000      6
0.3000      6
0.8200      6
2.4900      6
0.9075      6
2.3500      6
4.0500      6
1.3400      6
2.8900      5
0.6804      5
0.6900      5
5.1000      5
3.8300      5
0.9800      5
0.7905      5
0.6400      5
4.2800      5
1.3300      5
0.5600      5
4.8500      5
1.7500      5
2.1600      5
0.4469      5
0.9825      5
0.6082      5
0.8600      5
4.9500      5
5.2500      5
6.0000      5
0.8570      5
0.6700      5
3.0500      5
0.5700      4
0.3200      4
0.3400      4
0.8557      4
1.2600      4
1.5700      4
0.8400      4
1.5200      4
3.0300      4
9.5000      4
3.7800      4
0.3100      4
7.0000      4
2.1900      4
0.8073      4
0.8011      4
0.6300      4
6.5000      4
1.5900      4
3.8800      4
0.6598      4
0.4600      4
1.2900      4
1.9600      4
0.8321      4
0.7918      4
0.4212      4
1.4900      4
0.7020      4
0.3700      4
4.2300      4
2.7700      4
1.8700      4
0.3600      3
2.7900      3
1.1800      3
7.1500      3
2.4100      3
2.6900      3
1.3800      3
0.3900      3
0.8700      3
0.3795      3
1.0300      3
0.5900      3
0.9300      3
3.6900      3
2.4400      3
1.0100      3
1.8100      3
2.4200      3
1.4300      3
0.9170      3
9.0000      3
0.3750      3
0.2700      3
1.4200      3
1.9400      3
9.8000      3
1.9700      3
0.5220      3
1.3200      3
0.6100      3
0.7250      3
0.4088      3
0.8100      3
4.5200      3
0.3051      3
3.6700      2
0.8261      2
0.6450      2
1.1700      2
0.6550      2
0.7150      2
5.4500      2
3.9800      2
0.5312      2
1.7800      2
0.5650      2
0.7400      2
1.2200      2
7.4000      2
1.3900      2
0.4226      2
0.7950      2
0.9065      2
1.3600      2
3.6200      2
0.4230      2
0.2900      2
0.6333      2
0.5917      2
0.7300      2
0.6375      2
0.7065      2
0.6762      2
3.0900      2
3.9700      2
2.7300      2
2.9900      2
4.1700      2
0.5950      2
0.5640      2
3.1200      2
5.0500      2
5.1500      2
5.6500      2
0.8300      2
1.6200      2
2.1200      2
0.9377      2
3.0600      2
0.8569      2
1.9800      2
1.4100      2
1.6300      2
0.7100      2
1.1900      2
5.7000      2
0.4523      2
0.4117      2
0.5292      2
3.4300      2
1.6400      2
1.1300      2
7.2500      2
4.0700      2
4.0800      2
5.6000      2
4.4100      2
2.8200      2
4.4800      2
0.6080      2
0.8678      2
2.0300      2
8.0000      2
7.7400      2
2.5600      2
1.1100      2
2.0400      2
0.8750      2
0.4400      2
2.8600      2
5.4000      2
0.4850      2
3.4800      2
0.6840      1
2.1100      1
0.9535      1
0.5095      1
0.3945      1
0.9312      1
0.9008      1
1.0600      1
0.3744      1
0.4140      1
1.2400      1
1.8800      1
0.9400      1
0.8844      1
0.2600      1
4.0600      1
1.5300      1
1.0400      1
3.9900      1
0.7612      1
0.5621      1
1.5800      1
0.9850      1
0.2950      1
0.5162      1
0.2650      1
0.2750      1
2.3900      1
2.4700      1
1.0800      1
4.5700      1
5.9200      1
3.3300      1
5.2100      1
4.9200      1
0.8280      1
0.9406      1
0.7025      1
4.3700      1
4.6100      1
0.8588      1
5.2800      1
2.9700      1
1.8300      1
8.1400      1
1.6900      1
8.0500      1
0.7974      1
0.8535      1
0.7489      1
3.2800      1
6.2500      1
11.9500     1
2.0800      1
4.9900      1
4.6700      1
5.8600      1
3.8900      1
4.7800      1
3.7900      1
5.3300      1
6.9000      1
2.0500      1
4.1600      1
4.7200      1
2.6800      1
4.1200      1
1.7100      1
3.8100      1
2.0600      1
0.8945      1
0.9854      1
4.7400      1
3.4900      1
2.3400      1
6.1000      1
11.0000     1
4.1900      1
0.7745      1
0.9485      1
0.3001      1
3.1800      1
0.4473      1
5.1800      1
1.5400      1
1.6100      1
3.1300      1
6.8600      1
4.4600      1
4.7100      1
2.6100      1
1.0900      1
2.1400      1
5.3900      1
1.9900      1
0.7724      1
0.5085      1
0.7425      1
2.1300      1
1.8600      1
5.0300      1
2.9100      1
0.7751      1
2.6600      1
0.7666      1
0.9522      1
0.4968      1
0.6225      1
0.7424      1
0.9158      1
0.4634      1
0.4410      1
0.5670      1
0.4562      1
4.4700      1
5.2200      1
4.7900      1
5.9700      1
0.6465      1
0.3250      1
0.9009      1
0.9050      1
2.3800      1
0.6180      1
2.7100      1
3.2700      1
3.1900      1
3.2200      1
4.4400      1
2.0900      1
2.5100      1
3.5100      1
3.2100      1
0.3425      1
0.7450      1
0.7148      1
0.8975      1
0.8055      1
0.8540      1
0.8640      1
0.5792      1
0.4250      1
0.7670      1
0.4864      1
0.5163      1
0.4588      1
0.4300      1
0.7675      1
0.6555      1
0.7954      1
0.7140      1
0.7244      1
0.4320      1
0.4488      1
0.6990      1
0.6660      1
0.6205      1
0.8007      1
0.4264      1
0.9328      1
0.5750      1
2.8700      1
3.1700      1
2.5900      1
0.5760      1
0.6464      1
0.3220      1
0.3485      1
1.1600      1
1.9200      1
0.4680      1
5.8500      1
7.1000      1
7.0500      1
8.9500      1
10.0000     1
3.0800      1
9.2500      1
5.2000      1
0.6275      1
0.5850      1
0.9540      1
0.8586      1
0.5330      1
0.9044      1
0.9100      1
0.3796      1
0.3892      1
0.9700      1
2.2400      1
2.0100      1
6.4000      1
3.5200      1
7.2000      1
1.5100      1
5.9900      1
9.1000      1
8.5900      1
1.7700      1
2.8400      1
0.9744      1
0.5450      1
0.4252      1
0.4950      1
1.1400      1
0.9380      1
0.2772      1
0.3219      1
0.2790      1
0.2800      1
2.7200      1
0.3154      1
0.4652      1
0.2500      1
0.3850      1
0.7860      1
0.3140      1
0.3825      1
0.3516      1
0.8790      1
0.4450      1
3.3200      1
2.9800      1
3.6800      1
5.2900      1
3.7300      1
0.6690      1
0.6764      1
0.7375      1
0.9960      1
0.6092      1
0.7835      1
0.5475      1
0.2925      1
0.4499      1
Name: count, dtype: int64

In [77]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Area',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Floor', 'Floors in Building',
       'Price'],
      dtype='object')

In [79]:
df['Area'].value_counts()

Area
10 Marla      533
12 Marla      196
2.2 Marla     196
2 Marla       128
5 Marla       124
1.8 Marla     103
2.3 Marla     101
3.6 Marla      85
2.4 Marla      81
12.2 Marla     78
4 Marla        68
4.4 Marla      65
13 Marla       55
2.7 Marla      54
2.1 Marla      53
1.6 Marla      49
4.1 Marla      48
2.8 Marla      45
2.5 Marla      43
3 Marla        42
1.5 Marla      40
3.3 Marla      40
4.5 Marla      39
1.3 Marla      39
11 Marla       39
1.7 Marla      36
1.4 Marla      33
3.1 Marla      33
1.9 Marla      29
1.2 Marla      28
1.1 Marla      28
3.4 Marla      26
2.6 Marla      22
3.8 Marla      22
4.6 Marla      22
4.2 Marla      21
5.3 Marla      21
3.2 Marla      20
2.9 Marla      18
6.4 Marla      16
4.7 Marla      16
11.2 Marla     15
4.3 Marla      14
9.8 Marla      13
3.9 Marla      13
4.9 Marla      12
8.9 Marla      12
0.6 Marla      12
0.9 Marla      10
3.5 Marla       9
6 Marla         9
10.9 Marla      9
5.5 Marla       9
5.2 Marla       9
0.7 Marla       9
7.9 Marla       9
9 Marla         9
5.4 Marla       9
12.9 Marla      8
5.6 Marla       8
1 Marla         8
5.1 Marla       7
6.7 Marla       7
11.1 Marla      6
7.3 Marla       6
8.2 Marla       6
7.2 Marla       6
3.7 Marla       6
0.8 Marla       6
7.5 Marla       6
7.7 Marla       6
8.1 Marla       5
0.4 Marla       5
6.2 Marla       5
7.6 Marla       5
6.3 Marla       5
5.8 Marla       5
6.8 Marla       4
8 Marla         4
6.9 Marla       4
10.5 Marla      3
7.1 Marla       3
11.3 Marla      3
13.1 Marla      3
10.1 Marla      3
11.7 Marla      3
13.5 Marla      3
5.7 Marla       3
0.5 Marla       3
8.7 Marla       3
6.6 Marla       2
8.3 Marla       2
6.1 Marla       2
7.4 Marla       2
10.2 Marla      2
10.6 Marla      2
8.4 Marla       2
11.9 Marla      2
5.9 Marla       2
8.5 Marla       2
14.4 Marla      2
50 Kanal        2
14 Marla        1
16.1 Marla      1
12.5 Marla      1
15 Marla        1
11.4 Marla      1
1 Kanal         1
9.4 Marla       1
9.5 Marla       1
6.5 Marla       1
60 Kanal        1
9.3 Marla       1
7.8 Marla       1
4.8 Marla       1
10.4 Marla      1
14.2 Marla      1
5.6 Kanal       1
28.5 Kanal      1
7 Marla         1
11.6 Marla      1
Name: count, dtype: int64

In [80]:
import re
import numpy as np

def area_to_marla(x):
    if pd.isna(x):
        return np.nan
    s = str(x).strip().lower()
    m = re.search(r"(\d+(?:\.\d+)?)\s*(marla|kanal)", s)
    if not m:
        return np.nan
    val = float(m.group(1))
    unit = m.group(2)
    return val if unit == "marla" else val * 20

df["Area_marla"] = df["Area"].apply(area_to_marla)

In [88]:
df[df['Area']=='28.5 Kanal']

,Property ID,Society,Society Link,Name,Page Title,Area,Bedrooms,Baths,Floor Number,Total Floors,...,Features,Rooms,Other Rooms,Link,Built in year,Parking Spaces,Floor,Floors in Building,Price,Area_marla
3052,1,Lake City Meadows,https://www.zameen.com/Flats_Apartments/Lahore...,"1 BHK Flat for sale in Lake City Meadows, Lahore","Lake City Meadows, Lahore, Punjab",28.5 Kanal,1.0,1.0,1,3,...,Built in year : 2025 | Parking Spaces | Lobby ...,"{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens'...","Servant Quarters, Drawing Room, Dining Room, S...",https://www.zameen.com/Property/lahore_lake_ci...,2025,TRUE,1,3,0.75,570.0

In [89]:
print(df['Area'].iloc[3050])
print(df['Area_marla'].iloc[3050])

4.7 Marla
4.7

In [91]:
df = df.drop(columns=["Area"]).rename(columns={"Area_marla": "Area"})

In [92]:
print(df['Area'].iloc[3050])

4.7

In [94]:
df["area_sqft"] = df["Area"] * 272

In [96]:
df['Area'].isnull().sum()

np.int64(0)

In [95]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Floor', 'Floors in Building',
       'Price', 'Area', 'area_sqft'],
      dtype='object')

## bedrooms

In [98]:
df['Bedrooms'].isnull().sum()

np.int64(337)

In [101]:
df['Rooms'].value_counts()

Rooms
{}                                                                                                        456
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         362
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1'}                                                      270
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         154
{'Bedrooms': '2', 'Bathrooms': '2', 'Kitchens': '1'}                                                      142
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         140
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         138
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         134
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}          58
{'Bedrooms': '1', 'Bathrooms': '1'}                                                                        58
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}          57
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1', 'Store Rooms': '1'}                                   39
{'Bedrooms': '2', 'Bathrooms': '2', 'Kitchens': '1', 'Store Rooms': '1'}                                   39
{'Bedrooms': '2', 'Bathrooms': '2'}                                                                        31
{'Bedrooms': '2', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}          28
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '1'}                                                       25
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1'}                              24
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}          19
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}          19
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1'}                              19
{'Bedrooms': '1'}                                                                                          17
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}          15
{'Bedrooms': '03', 'Bathrooms': '03', 'Servant Quarters': '01', 'Kitchens': '01', 'Store Rooms': '01'}     15
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '1', 'Store Rooms': '1'}                                   15
{'Bedrooms': '1', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}          14
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}          14
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1'}                              13
{'Bedrooms': '2', 'Bathrooms': '3', 'Kitchens': '1'}                                                       13
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}          12
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}          12
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}          12
{'Kitchens': '1'}                                                                                          11
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}          11
{'Bedrooms': '1', 'Bathrooms': '2', 'Kitchens': '1'}                                                       11
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '1'}                                                       10
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Store Rooms': '1'}                           10
{'Bathrooms': '1', 'Kitchens': '1'}                                                                        10
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}          10
{'Bedrooms': '2'}                                                                                          10
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}           9
{'Bedrooms': '5', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           9
{'Bedrooms': '2', 'Bathrooms': '3', 'Kitchens': '1', 'Store Rooms': '1'}                                    9
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1'}                               9
{'Bedrooms': '2', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           9
{'Bedrooms': '2', 'Bathrooms': '1', 'Kitchens': '1'}                                                        9
{'Servant Quarters': '1'}                                                                                   8
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '2'}                                                        8
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           8
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           8
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}           8
{'Bedrooms': '3', 'Bathrooms': '4', 'Kitchens': '1', 'Store Rooms': '1'}                                    8
{'Bedrooms': '04', 'Bathrooms': '05', 'Servant Quarters': '01', 'Kitchens': '01', 'Store Rooms': '01'}      7
{'Bedrooms': '3', 'Bathrooms': '3'}                                                                         7
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '2'}           7
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '2'}                                                        7
{'Bedrooms': '5', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '1'}           7
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '1', 'Store Rooms': '1'}                                    7
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           7
{'Bathrooms': '1'}                                                                                          7
{'Bedrooms': '5', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           7
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '2'}                                                        7
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '2'}                                                        7
{'Bedrooms': '3', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           6
{'Store Rooms': '1'}                                                                                        6
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Store Rooms': '1'}                            6
{'Bedrooms': '04', 'Bathrooms': '04', 'Servant Quarters': '01', 'Kitchens': '01', 'Store Rooms': '01'}      6
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}           6
{'Bedrooms': '5', 'Bathrooms': '5'}                                                                         6
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '1'}                               6
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1'}                                                6
{'Bedrooms': '1', 'Servant Quarters': '1'}                                                                  6
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}           6
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}           5
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           5
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '2'}           5
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2'}                               5
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2'}                               5
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}           5
{'Bedrooms': '4', 'Bathrooms': '4'}                                                                         5
{'Servant Quarters': '1', 'Store Rooms': '1'}                                                               5
{'Bedrooms': '3', 'Bathrooms': '4'}                                                                         5
{'Bedrooms': '1', 'Bathrooms': '1', 'Store Rooms': '1'}                                                     5
{'Bedrooms': '1', 'Servant Quarters': '1', 'Store Rooms': '1'}                                              4
{'Bedrooms': '3', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           4
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           4
{'Bedrooms': '2', 'Bathrooms': '2', 'Store Rooms': '1'}                                                     4
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '2', 'Store Rooms': '1'}                                    4
{'Bedrooms': '4', 'Bathrooms': '5'}                                                                         3
{'Bedrooms': '3', 'Bathrooms': '3', 'Kitchens': '2', 'Store Rooms': '1'}                                    3
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}           3
{'Bedrooms': '5', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '3', 'Store Rooms': '1'}           3
{'Bedrooms': '9', 'Bathrooms': '9', 'Servant Quarters': '1', 'Kitchens': '2'}                               3
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}           3
{'Bedrooms': '5', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           3
{'Bedrooms': '1', 'Bathrooms': '2', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           3
{'Bedrooms': '2', 'Bathrooms': '2', 'Kitchens': '2'}                                                        3
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '1'}                                                        3
{'Bedrooms': '1', 'Bathrooms': '2'}                                                                         3
{'Bedrooms': '2', 'Bathrooms': '3'}                                                                         3
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '2', 'Store Rooms': '1'}                                    3
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1'}                               3
{'Bedrooms': '1', 'Bathrooms': '2', 'Kitchens': '1', 'Store Rooms': '1'}                                    3
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           3
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '2'}                                                        3
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1', 'Store Rooms': '2'}                                    3
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '01', 'Kitchens': '1', 'Store Rooms': '01'}         3
{'Bedrooms': '2', 'Bathrooms': '1', 'Kitchens': '1', 'Store Rooms': '1'}                                    3
{'Bedrooms': '3', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           3
{'Servant Quarters': '1', 'Kitchens': '1'}                                                                  3
{'Bedrooms': '6', 'Bathrooms': '8', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}           3
{'Bedrooms': '1', 'Store Rooms': '1'}                                                                       3
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2'}                               3
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '2', 'Store Rooms': '1'}                                    3
{'Bedrooms': '8', 'Bathrooms': '8', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           3
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           3
{'Bedrooms': '4', 'Bathrooms': '4', 'Kitchens': '1'}                                                        3
{'Bedrooms': '4', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           3
{'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                            3
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           3
{'Bedrooms': '2', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           3
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}           2
{'Bedrooms': '6', 'Bathrooms': '7'}                                                                         2
{'Bedrooms': '3', 'Bathrooms': '2', 'Kitchens': '1', 'Store Rooms': '1'}                                    2
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Store Rooms': '2'}                            2
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '1', 'Store Rooms': '2'}                            2
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '1'}                                                2
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1'}                                                2
{'Bedrooms': '01', 'Bathrooms': '01', 'Kitchens': '01'}                                                     2
{'Bedrooms': '1', 'Bathrooms': '1', 'Kitchens': '1', 'Store Rooms': '01'}                                   2
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '3', 'Store Rooms': '1'}           2
{'Bedrooms': '3', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '2'}           2
{'Servant Quarters': '2', 'Store Rooms': '2'}                                                               2
{'Bedrooms': '13', 'Bathrooms': '16', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '3'}         2
{'Bedrooms': '5', 'Bathrooms': '5', 'Kitchens': '2', 'Store Rooms': '1'}                                    2
{'Bedrooms': '4', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           2
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '1', 'Kitchens': '2'}                               2
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1'}                               2
{'Bedrooms': '6', 'Bathrooms': '6', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '2'}           2
{'Bedrooms': '6', 'Bathrooms': '6'}                                                                         2
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Store Rooms': '1'}                            2
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '02', 'Kitchens': '1', 'Store Rooms': '01'}         2
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Store Rooms': '2'}                            2
{'Bedrooms': '8', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}           2
{'Bedrooms': '5', 'Bathrooms': '6', 'Kitchens': '2', 'Store Rooms': '1'}                                    2
{'Bedrooms': '4', 'Bathrooms': '4', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           2
{'Bedrooms': '4', 'Bathrooms': '2', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '2'}           2
{'Bedrooms': '3', 'Bathrooms': '5', 'Kitchens': '2'}                                                        2
{'Bedrooms': '2', 'Bathrooms': '4', 'Servant Quarters': '1', 'Kitchens': '1'}                               2
{'Bedrooms': '2', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}           2
{'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                                              2
{'Bedrooms': '4'}                                                                                           2
{'Bedrooms': '1', 'Servant Quarters': '2'}                                                                  2
{'Bedrooms': '2', 'Servant Quarters': '1', 'Store Rooms': '1'}                                              2
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '2', 'Store Rooms': '2'}                            2
{'Bedrooms': '4', 'Bathrooms': '5', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}           2
{'Bedrooms': '1', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1'}                               2
{'Bathrooms': '2', 'Kitchens': '1'}                                                                         2
{'Bathrooms': '3'}                                                                                          2
{'Bedrooms': '2', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '1', 'Store Rooms': '1'}           2
{'Bedrooms': '3', 'Bathrooms': '3', 'Store Rooms': '1'}                                                     2
{'Bedrooms': '3'}                                                                                           2
{'Bedrooms': '2', 'Bathrooms': '1', 'Servant Quarters': '1', 'Kitchens': '1'}                               2
{'Bedrooms': '1', 'Servant Quarters': '2', 'Store Rooms': '2'}                                              2
{'Bedrooms': '04', 'Bathrooms': '03', 'Servant Quarters': '01', 'Kitchens': '01', 'Store Rooms': '01'}      2
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Store Rooms': '1'}                            1
{'Bedrooms': '4', 'Servant Quarters': '1', 'Kitchens': '2'}                                                 1
{'Bedrooms': '6', 'Bathrooms': '7', 'Servant Quarters': '3', 'Kitchens': '3', 'Store Rooms': '3'}           1
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '01'}          1
{'Bedrooms': '1', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '1'}                             1
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '1', 'Kitchens': '2', 'Store Rooms': '2'}           1
{'Bedrooms': '4', 'Bathrooms': '5', 'Kitchens': '1', 'Store Rooms': '1'}                                    1
{'Bedrooms': '3', 'Bathrooms': '3', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '01'}          1
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '02', 'Kitchens': '1', 'Store Rooms': '02'}         1
{'Bedrooms': '3', 'Bathrooms': '2', 'Kitchens': '2', 'Store Rooms': '1'}                                    1
{'Bedrooms': '1', 'Bathrooms': '4', 'Kitchens': '1'}                                                        1
{'Bathrooms': '1', 'Servant Quarters': '3'}                                                                 1
{'Bedrooms': '2', 'Bathrooms': '2', 'Servant Quarters': '01', 'Kitchens': '01', 'Store Rooms': '01'}        1
{'Bedrooms': '1', 'Bathrooms': '1', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '1'}           1
{'Bedrooms': '1', 'Servant Quarters': '1', 'Store Rooms': '2'}                                              1
{'Bedrooms': '7', 'Bathrooms': '6', 'Servant Quarters': '2', 'Kitchens': '2', 'Store Rooms': '2'}           1
{'Bedrooms': '03', 'Bathrooms': '03', 'Servant Quarters': '1', 'Kitchens': '1', 'Store Rooms': '1'}         1

In [102]:
import ast
import re
import pandas as pd
import numpy as np

def to_dict(x):
    if pd.isna(x):
        return {}
    if isinstance(x, dict):
        return x
    s = str(x).strip()
    if s in ("", "{}"):
        return {}
    try:
        return ast.literal_eval(s)
    except Exception:
        return {}

rooms_dicts = df["Rooms"].apply(to_dict)

rooms_df = pd.json_normalize(rooms_dicts)

# lowercase + underscore
rooms_df.columns = [
    re.sub(r"[^a-z0-9]+", "_", c.strip().lower()).strip("_")
    for c in rooms_df.columns
]

# numeric values
for c in rooms_df.columns:
    rooms_df[c] = pd.to_numeric(rooms_df[c], errors="coerce")

# add to df
for c in rooms_df.columns:
    df[c] = rooms_df[c]

In [103]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Floor', 'Floors in Building',
       'Price', 'Area', 'area_sqft', 'bedrooms', 'bathrooms',
       'servant_quarters', 'kitchens', 'store_rooms'],
      dtype='object')

In [ ]:
df[df['Bedrooms'].isnull()]

805    NaN
955    NaN
956    NaN
959    NaN
964    NaN
967    NaN
968    NaN
980    NaN
981    NaN
995    NaN
1002   NaN
1014   NaN
1023   NaN
1043   NaN
1048   NaN
1049   NaN
1053   NaN
1072   NaN
1082   NaN
1083   NaN
1086   NaN
1093   NaN
1103   NaN
1181   NaN
1189   NaN
1191   NaN
1208   NaN
1213   NaN
1223   NaN
1224   NaN
1225   NaN
1231   NaN
1244   NaN
1272   NaN
1275   NaN
1280   NaN
1292   NaN
1296   NaN
1315   NaN
1321   NaN
1325   NaN
1330   NaN
1338   NaN
1345   NaN
1364   NaN
1379   NaN
1393   NaN
1403   NaN
1438   NaN
1441   NaN
1468   NaN
1471   NaN
1477   NaN
1478   NaN
1483   NaN
1484   NaN
1486   NaN
1513   NaN
1519   NaN
1532   NaN
1552   NaN
1580   NaN
1581   NaN
1586   NaN
1602   NaN
1603   NaN
1613   NaN
1630   NaN
1633   NaN
1648   NaN
1651   NaN
1652   NaN
1653   NaN
1654   NaN
1655   NaN
1660   NaN
1667   NaN
1670   NaN
1675   NaN
1678   NaN
1680   NaN
1688   NaN
1706   NaN
1708   NaN
1716   NaN
1717   NaN
1718   NaN
1720   NaN
1722   NaN
1728   NaN
1730   NaN
1731   NaN
1746   NaN
1749   NaN
1760   NaN
1767   NaN
1776   NaN
1778   NaN
1779   NaN
1781   NaN
1797   NaN
1800   NaN
1809   NaN
1811   NaN
1814   NaN
1818   NaN
1819   NaN
1820   NaN
1831   NaN
1834   NaN
1852   NaN
1863   NaN
1867   NaN
1868   NaN
1885   NaN
1892   NaN
1900   NaN
1908   NaN
1909   NaN
1910   NaN
1911   NaN
1912   NaN
1913   NaN
1917   NaN
1918   NaN
1944   NaN
1952   NaN
1955   NaN
1967   NaN
1980   NaN
1981   NaN
1985   NaN
1986   NaN
1990   NaN
1993   NaN
1997   NaN
2022   NaN
2024   NaN
2035   NaN
2040   NaN
2042   NaN
2057   NaN
2063   NaN
2071   NaN
2077   NaN
2089   NaN
2091   NaN
2093   NaN
2094   NaN
2100   NaN
2104   NaN
2113   NaN
2121   NaN
2124   NaN
2125   NaN
2130   NaN
2131   NaN
2141   NaN
2142   NaN
2149   NaN
2150   NaN
2160   NaN
2171   NaN
2172   NaN
2173   NaN
2174   NaN
2175   NaN
2191   NaN
2192   NaN
2195   NaN
2196   NaN
2206   NaN
2207   NaN
2208   NaN
2210   NaN
2215   NaN
2219   NaN
2222   NaN
2227   NaN
2235   NaN
2242   NaN
2266   NaN
2271   NaN
2273   NaN
2283   NaN
2285   NaN
2288   NaN
2291   NaN
2308   NaN
2310   NaN
2311   NaN
2327   NaN
2334   NaN
2336   NaN
2359   NaN
2374   NaN
2378   NaN
2396   NaN
2406   NaN
2407   NaN
2410   NaN
2411   NaN
2412   NaN
2413   NaN
2418   NaN
2435   NaN
2450   NaN
2462   NaN
2463   NaN
2465   NaN
2469   NaN
2481   NaN
2496   NaN
2501   NaN
2511   NaN
2512   NaN
2514   NaN
2525   NaN
2526   NaN
2528   NaN
2536   NaN
2553   NaN
2565   NaN
2572   NaN
2573   NaN
2588   NaN
2601   NaN
2629   NaN
2633   NaN
2634   NaN
2640   NaN
2651   NaN
2659   NaN
2661   NaN
2662   NaN
2663   NaN
2677   NaN
2679   NaN
2683   NaN
2684   NaN
2685   NaN
2695   NaN
2702   NaN
2706   NaN
2717   NaN
2733   NaN
2738   NaN
2742   NaN
2750   NaN
2751   NaN
2755   NaN
2757   NaN
2758   NaN
2759   NaN
2760   NaN
2761   NaN
2762   NaN
2773   NaN
2774   NaN
2776   NaN
2777   NaN
2781   NaN
2786   NaN
2787   NaN
2793   NaN
2803   NaN
2812   NaN
2813   NaN
2814   NaN
2815   NaN
2816   NaN
2817   NaN
2818   NaN
2820   NaN
2822   NaN
2824   NaN
2826   NaN
2827   NaN
2828   NaN
2831   NaN
2832   NaN
2833   NaN
2845   NaN
2849   NaN
2865   NaN
2888   NaN
2889   NaN
2892   NaN
2896   NaN
2898   NaN
2899   NaN
2902   NaN
2903   NaN
2904   NaN
2905   NaN
2907   NaN
2911   NaN
2912   NaN
2913   NaN
2915   NaN
2916   NaN
2917   NaN
2918   NaN
2925   NaN
2926   NaN
2927   NaN
2936   NaN
2939   NaN
2950   NaN
2951   NaN
2952   NaN
2955   NaN
2960   NaN
2966   NaN
2967   NaN
2970   NaN
2972   NaN
2973   NaN
2976   NaN
2981   NaN
2989   NaN
2995   NaN
3000   NaN
3022   NaN
3032   NaN
3042   NaN
3043   NaN
3044   NaN
3075   NaN
3089   NaN
3090   NaN
3091   NaN
3098   NaN
3099   NaN
3101   NaN
3102   NaN
3112   NaN
Name: Bedrooms, dtype: float64

In [118]:
df['bedrooms'].iloc[804]

np.float64(3.0)

In [119]:
df['Bedrooms'].isnull().sum()

np.int64(337)

In [122]:
df["Bedrooms"] = df["Bedrooms"].fillna(df["bedrooms"])

In [123]:
df["Bedrooms"].isnull().sum()

np.int64(97)

In [125]:
df['Baths'].isnull().sum()

np.int64(77)

In [127]:
df["Baths"] = df["Baths"].fillna(df["bathrooms"])

In [128]:
df['Baths'].isnull().sum()

np.int64(29)

In [129]:
df = df.drop(columns=["bedrooms", "bathrooms"], errors="ignore")

In [130]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Floor', 'Floors in Building',
       'Price', 'Area', 'area_sqft', 'servant_quarters', 'kitchens',
       'store_rooms'],
      dtype='object')

In [131]:
df.isna().sum().sort_values(ascending=False)

servant_quarters      1386
store_rooms           1358
Floor Number          1142
Floor                 1142
Floors in Building    1070
Total Floors          1070
kitchens               748
Built Year             671
Built in year          671
Parking Spaces         435
Other Rooms            406
Bedrooms                97
Features                58
Baths                   29
Property ID              0
Society Link             0
Page Title               0
Society                  0
Name                     0
Address                  0
Description              0
Rooms                    0
Link                     0
Price                    0
Area                     0
area_sqft                0
dtype: int64

In [132]:
df.shape

(3118, 26)

In [133]:
df['Price'].iloc[900]

np.float64(4.25)

In [134]:
import numpy as np

df["price_per_sqft"] = np.where(
    df["area_sqft"] > 0,
    (df["Price"] * 1e7) / df["area_sqft"],  # Price in crore -> PKR
    np.nan
)

In [135]:
df['Price'].iloc[0]

np.float64(4.55)

In [139]:
df['Area'].iloc[0]

np.float64(12.0)

In [137]:
df['price_per_sqft'].iloc[0]

np.float64(13939.950980392157)

In [140]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Floor', 'Floors in Building',
       'Price', 'Area', 'area_sqft', 'servant_quarters', 'kitchens',
       'store_rooms', 'price_per_sqft'],
      dtype='object')

In [142]:
df['Built Year'].isnull().sum()

np.int64(671)

In [144]:
df['Features'].iloc[0]

'Built in year : 2026 | Parking Spaces : 2 | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 3 | Floors in Building : 9 | Elevators : 3 | Service Elevators in Building | Broadband Internet Access | Satellite or Cable TV Ready | Community Lawn or Garden | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Other Facilities'

In [145]:
import re
import numpy as np

df["builtyear"] = (
    df["Features"]
      .str.extract(r"Built in year\s*:\s*([0-9]+(?:\.[0-9]+)?)", expand=False)
      .astype(float)
)

In [148]:
df['builtyear'].isnull().sum()

np.int64(843)

In [149]:
df['Built Year'].isnull().sum()

np.int64(671)

In [147]:
df['builtyear'].iloc[0]
df['Built Year'].iloc[0]

'2026'

In [141]:
df['Built Year'].value_counts()

Built Year
2025     689
2024     297
2026     251
TRUE     172
2023     162
2022     115
2027      89
2018      80
2020      79
2028      66
2029      65
2021      60
2015      41
2017      38
2019      33
2016      27
1         25
2010      17
2         14
2030      13
3         11
2000      10
4          9
2005       6
5          5
2014       4
1990       4
1992       4
2011       3
2009       3
1985       3
1986       3
0          3
2002       3
2004       3
2012       3
20001      2
4.5        2
1994       2
1999       2
20242      2
2003       2
2007       2
15         2
2.5        2
1993       1
204        1
324        1
1987       1
2013       1
202        1
25         1
1982       1
20285      1
2008       1
18         1
10         1
1996       1
1998       1
20205      1
24         1
8          1
2001       1
6          1
Name: count, dtype: int64

In [150]:
df['builtyear'].value_counts()

builtyear
2025.0     689
2024.0     297
2026.0     251
2023.0     162
2022.0     115
2027.0      89
2018.0      80
2020.0      79
2028.0      66
2029.0      65
2021.0      60
2015.0      41
2017.0      38
2019.0      33
2016.0      27
1.0         25
2010.0      17
2.0         14
2030.0      13
3.0         11
2000.0      10
4.0          9
2005.0       6
5.0          5
2014.0       4
1990.0       4
1992.0       4
2011.0       3
2009.0       3
1985.0       3
1986.0       3
0.0          3
2002.0       3
2004.0       3
2012.0       3
20001.0      2
4.5          2
1994.0       2
1999.0       2
20242.0      2
2003.0       2
2007.0       2
15.0         2
2.5          2
1993.0       1
204.0        1
324.0        1
1987.0       1
2013.0       1
202.0        1
25.0         1
1982.0       1
20285.0      1
2008.0       1
18.0         1
10.0         1
1996.0       1
1998.0       1
20205.0      1
24.0         1
8.0          1
2001.0       1
6.0          1
Name: count, dtype: int64

In [151]:
df["Built Year"] = df["Built Year"].fillna(df["builtyear"])

In [152]:
df["Built Year"].isnull().sum()

np.int64(671)

In [153]:
df = df.drop(columns=["builtyear"], errors="ignore")

In [154]:
print(df['Built Year'].isnull().sum())
print(df['Built in year'].isnull().sum())

671
671

In [157]:
print(df['Built Year'].iloc[800])
print(df['Built in year'].iloc[800])

2018
2018

In [158]:
df = df.drop(columns=["Built in year"], errors="ignore")

In [159]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Floor', 'Floors in Building', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'price_per_sqft'],
      dtype='object')

In [160]:
df['Built Year'].value_counts()

Built Year
2025     689
2024     297
2026     251
TRUE     172
2023     162
2022     115
2027      89
2018      80
2020      79
2028      66
2029      65
2021      60
2015      41
2017      38
2019      33
2016      27
1         25
2010      17
2         14
2030      13
3         11
2000      10
4          9
2005       6
5          5
2014       4
1990       4
1992       4
2011       3
2009       3
1985       3
1986       3
0          3
2002       3
2004       3
2012       3
20001      2
4.5        2
1994       2
1999       2
20242      2
2003       2
2007       2
15         2
2.5        2
1993       1
204        1
324        1
1987       1
2013       1
202        1
25         1
1982       1
20285      1
2008       1
18         1
10         1
1996       1
1998       1
20205      1
24         1
8          1
2001       1
6          1
Name: count, dtype: int64

In [163]:
df["Built Year_num"] = pd.to_numeric(df["Built Year"], errors="coerce")

In [261]:
df['Built Year'].value_counts()

Built Year
2025      689
2024      297
2026      251
2023      162
2022      115
2027       89
2018       80
2020       79
2028       66
2029       65
2021       60
2015       41
2017       38
2019       33
2025.0     30
2016       27
2024.0     18
2010       17
2030       13
2023.0     11
2000       10
2022.0      9
2021.0      7
2005        6
1990        4
1992        4
2014        4
1985        3
2012        3
1986        3
2009        3
2011        3
2004        3
2002        3
2003        2
1994        2
2001        2
2018        2
2007        2
1999        2
2020        2
2013        1
1993        1
1982        1
2008        1
1987        1
2016        1
1996        1
1998        1
2011        1
2015        1
2001        1
Name: count, dtype: int64

In [260]:
df["Built Year"] = df["Built Year"].replace({"TRUE": np.nan, "true": np.nan, True: np.nan})

In [258]:
ref_year = 2026
mask = df["Built Year_num"].isin([1, 2, 3, 4, 5])
df.loc[mask, "Built Year"] = ref_year - df.loc[mask, "Built Year_num"]

In [ ]:
idx = 2197 
ref_year = 2026
df.loc[idx, "Built Year"] = ref_year - 18  # 2016

In [249]:
pd.set_option("display.max_colwidth", None)
df.loc[df["Built Year_num"] == 15          , "Link"].to_string()

'2745    https://www.zameen.com/Property/johar_town_phase_2_johar_town_phase_2_-_block_h3_luxuries_fully_furnished_brand_new_apartment_opposite_emporium_mall_near_canal_road_with_35k_rental_income-53861856-3968-1.html\n2749                                                                                            https://www.zameen.com/Property/johar_town_phase_2_johar_town_phase_2_-_block_h3_apartment_for_sale-53861858-3968-1.html'

In [205]:
df.loc[3080, "Built Year_num"]
df.loc[3080, "Built Year"]
df.loc[2446        , "Built Year"]

2025

In [ ]:
idx=3080    
ref_year = 2026  # or pd.Timestamp.today().year
df.loc[idx, "Built Year"] = ref_year - 6  # 2018

In [191]:
df.iloc[2750]['Built Year_num']

np.float64(2023.0)

In [243]:
pd.set_option("display.max_colwidth", None)
df.loc[df["Built Year_num"] == 0  , "Link"].to_string()

'921                                                            https://www.zameen.com/Property/askari_askari_5_book_a_10_marla_flat_in_askari_5-53724942-3559-1.html\n1175    https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_c_flat_spread_over_500_square_feet_in_bahria_town_-_sector_c_available-53965077-1784-1.html\n1467    https://www.zameen.com/Property/bahria_town_bahria_town_-_sector_c_flat_spread_over_500_square_feet_in_bahria_town_-_sector_c_available-53835231-1784-1.html'

In [204]:
mask = df["Link"].str.contains("53440485", na=False)
df.loc[mask, "Built Year"] = 2025

In [256]:
df.loc[df["Built Year"] == 2021.5 , "Built Year"] = 2021

In [91]:
df.loc[df["Built Year"] < 1000, "Built Year"] = np.nan

In [262]:
df["Built Year"] = pd.to_numeric(df["Built Year"], errors="coerce")
df = df.drop(columns=["Built Year_num"], errors="ignore")

In [263]:
df['Built Year'].value_counts()

Built Year
2025.0    719
2024.0    315
2026.0    251
2023.0    173
2022.0    124
2027.0     89
2018.0     82
2020.0     81
2021.0     67
2028.0     66
2029.0     65
2015.0     42
2017.0     38
2019.0     33
2016.0     28
2010.0     17
2030.0     13
2000.0     10
2005.0      6
2011.0      4
1992.0      4
2014.0      4
1990.0      4
2009.0      3
1985.0      3
2001.0      3
2004.0      3
1986.0      3
2012.0      3
2002.0      3
1994.0      2
2003.0      2
1999.0      2
2007.0      2
1993.0      1
2013.0      1
1982.0      1
2008.0      1
1987.0      1
1996.0      1
1998.0      1
Name: count, dtype: int64

In [264]:
df.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title',
       'Bedrooms', 'Baths', 'Floor Number', 'Total Floors', 'Built Year',
       'Address', 'Description', 'Features', 'Rooms', 'Other Rooms', 'Link',
       'Parking Spaces', 'Floor', 'Floors in Building', 'Price', 'Area',
       'area_sqft', 'servant_quarters', 'kitchens', 'store_rooms',
       'price_per_sqft'],
      dtype='object')

In [265]:
df['Built Year'].isnull().sum()

np.int64(847)

In [112]:
df['Floor Number'].isna().sum()

np.int64(1404)

In [116]:
df = df.drop(columns=["Nearby Locations and Other Facilities"])

In [117]:
df.columns

Index(['Name', 'Marla', 'Area (sqft)', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Other Rooms', 'Parking Spaces',
       'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'Rooms_Bedrooms',
       'Rooms_Bathrooms', 'Rooms_Kitchens', 'Rooms_Servant Quarters',
       'Rooms_Store Rooms', 'Price'],
      dtype='object')

In [120]:
df = df.rename(columns={
    "Rooms_Bedrooms": "bedrooms",
    "Rooms_Bathrooms": "bathrooms",
    "Rooms_Kitchens": "kitchens",
    "Rooms_Servant Quarters": "servant_quarters",
    "Rooms_Store Rooms": "store_rooms",
})

In [121]:
df.columns

Index(['Name', 'Marla', 'Area (sqft)', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Other Rooms', 'Parking Spaces',
       'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price'],
      dtype='object')

In [123]:
df.shape

(2499, 67)

In [122]:
df.to_csv("1st_video_done_flats_cleaning.csv")

## 2nd Video Starting

In [101]:
df = pd.read_csv(r"E:\Project\Data Cleaning\1st_video_done_flats_cleaning.csv")

In [102]:
pd.set_option("display.max_columns", None)

In [103]:
df.sample(1)

,Unnamed: 0,Name,Marla,Area (sqft),Floor Number,Total Floors,Built Year,Address,Description,Other Rooms,Parking Spaces,Lobby in Building,Double Glazed Windows,Central Air Conditioning,Central Heating,Flooring,Electricity Backup,Waste Disposal,Floor,Floors in Building,Elevators,Service Elevators in Building,Other Main Features,Broadband Internet Access,Satellite or Cable TV Ready,Business Center or Media Room in Building,Conference Room in Building,Intercom,ATM Machines,Other Business and Communication Facilities,Community Lawn or Garden,Community Swimming Pool,Community Gym,First Aid or Medical Centre,Day Care Centre,Kids Play Area,Barbeque Area,Mosque,Community Centre,Other Community Facilities,Sauna,Jacuzzi,Other Healthcare and Recreation Facilities,Nearby Schools,Nearby Hospitals,Nearby Shopping Malls,Nearby Restaurants,Distance From Airport (kms),Nearby Public Transport Service,Other Nearby Places,Maintenance Staff,Security Staff,Facilities for Disabled,Other Facilities,Section - Main Features,Section - Rooms,Section - Business and Communication,Section - Community Features,Section - Healthcare Recreational,Section - Nearby Locations and Other Facilities,Section - Other Facilities,Furnished,bedrooms,bathrooms,kitchens,servant_quarters,store_rooms,Price
690,690,"3 BHK Askari 10 - Sector F, Askari 10, Askari, Lahore, Punjab",10.0,2722.5,5.0,8.0,2022.0,"Askari 10 - Sector F, Askari 10, Askari, Lahore, Punjab",IMAGES ASSOCIATE OFFER FLAT FOR SALE OPEN VIEW 3 BEDROOM KITCHEN DINNING ROOM DRAWING ROOM TV LOUNGE SERVANT QUARTER LIFT SERVICE AIRPORT VIEW,"Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms",1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,5.0,8.0,2.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,"Built in year : 2022, Parking Spaces : 1, Lobby in Building, Double Glazed Windows, Central Air Conditioning, Central Heating, Flooring, Electricity Backup, Waste Disposal, Floor : 5, Floors in Building : 8, Elevators : 2, Service Elevators in Building, Other Main Features, Furnished","Bedrooms : 5, Bathrooms : 6, Servant Quarters : 1, Drawing Room, Dining Room, Kitchens : 2, Study Room, Prayer Room, Powder Room, Gym, Store Rooms : 1, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms","Broadband Internet Access, Satellite or Cable TV Ready, Business Center or Media Room in Building, Intercom, Other Business and Communication Facilities","Community Lawn or Garden, Community Swimming Pool, Community Gym, First Aid or Medical Centre, Day Care Centre, Kids Play Area, Barbeque Area, Mosque, Community Centre, Other Community Facilities","Sauna, Jacuzzi, Other Healthcare and Recreation Facilities","Nearby Schools, Nearby Hospitals, Nearby Shopping Malls, Nearby Restaurants, Distance From Airport (kms), Nearby Public Transport Service, Other Nearby Places","Maintenance Staff, Security Staff, Facilities for Disabled, Other Facilities",1.0,5.0,6.0,2.0,1.0,1.0,37500000

In [ ]:
import pandas as pd

def clean_item(x):
    x = x.strip()
    return x.split(":", 1)[0].strip()  # keep only name before ":"

features_unique = (
    df1["Features"]
    .dropna()
    .str.split("|")
    .explode()
    .map(clean_item)
    .dropna()
    .unique()
)

features_unique

array(['Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor',
       'Floors in Building', 'Elevators', 'Service Elevators in Building',
       'Other Main Features', 'Broadband Internet Access',
       'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool',
       'Community Gym', 'First Aid or Medical Centre', 'Day Care Centre',
       'Kids Play Area', 'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Furnished',
       'Communal/Shared Kitchen', 'Built in year', 'Pets Not Allowed',
       'Possesion', 'Corner', 'Park Facing', 'Disputed', 'File',
       'Balloted', 'Sewerage', 'Electricity', 'Water Supply', 'Sui Gas',
       'Boundary Wall'], dtype=object)

In [104]:
df.columns

Index(['Unnamed: 0', 'Name', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Other Rooms',
       'Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor', 'Floors in Building',
       'Elevators', 'Service Elevators in Building', 'Other Main Features',
       'Broadband Internet Access', 'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Facilities for Disabled', 'Other Facilities',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price'],
      dtype='object')

In [ ]:
drop_cols = [
    "Parking Spaces", "Lobby in Building", "Double Glazed Windows",
    "Central Air Conditioning", "Central Heating", "Flooring",
    "Electricity Backup", "Waste Disposal", "Floor",
    "Floors in Building", "Elevators", "Service Elevators in Building",
    "Other Main Features", "Broadband Internet Access",
    "Satellite or Cable TV Ready",
    "Business Center or Media Room in Building",
    "Conference Room in Building", "Intercom", "ATM Machines",
    "Other Business and Communication Facilities",
    "Community Lawn or Garden", "Community Swimming Pool",
    "Community Gym", "First Aid or Medical Centre", "Day Care Centre",
    "Kids Play Area", "Barbeque Area", "Mosque", "Community Centre",
    "Other Community Facilities", "Sauna", "Jacuzzi",
    "Other Healthcare and Recreation Facilities", "Nearby Schools",
    "Nearby Hospitals", "Nearby Shopping Malls", "Nearby Restaurants",
    "Distance From Airport (kms)", "Nearby Public Transport Service",
    "Other Nearby Places", "Maintenance Staff", "Security Staff",
    "Laundry or Dry Cleaning Facility", "Facilities for Disabled",
    "Pets Allowed", "Other Facilities", "Furnished",
    "Communal/Shared Kitchen", "Built in year", "Pets Not Allowed",
    "Possesion", "Corner", "Park Facing", "Disputed", "File",
    "Balloted", "Sewerage", "Electricity", "Water Supply", "Sui Gas",
    "Boundary Wall",
]

keep = {"Floor", "Floors in Building", "Built in year"}
drop_cols = [c for c in drop_cols if c not in keep]

df = df.drop(columns=drop_cols, errors="ignore")

In [106]:
df.columns

Index(['Unnamed: 0', 'Name', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Other Rooms',
       'Floor', 'Floors in Building', 'Section - Main Features',
       'Section - Rooms', 'Section - Business and Communication',
       'Section - Community Features', 'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'bedrooms', 'bathrooms', 'kitchens',
       'servant_quarters', 'store_rooms', 'Price'],
      dtype='object')

In [107]:
df = df.drop(columns=[
    "Section - Rooms",
    "Section - Main Features",
    "Section - Business and Communication",
    "Section - Community Features",
    "Section - Healthcare Recreational",
    "Section - Nearby Locations and Other Facilities",
    "Section - Other Facilities",
], errors="ignore")

In [115]:
df.sample(1)

,Unnamed: 0,Name,Marla,Area (sqft),Floor Number,Total Floors,Built Year,Address,Description,Other Rooms,Floor,Floors in Building,bedrooms,bathrooms,kitchens,servant_quarters,store_rooms,Price
1506,1511,#NAME?,2.2,598.95,NaN,NaN,2025.0,"Amanah Residential Towers, Raiwind Road, Lahore, Punjab","Amanah Residential Tower Hot Location Near Adda Plot Near Ring Road Near Beacon House University Studio, 1 Bed , 2 Bed Luxury Apartments 490 Sq. Ft. To 1259 Sq. Ft 5 Year Instalment Plan Possession In 3.5 Year 10% Rental Yield+ Merging Available Contact For Booking","Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms",NaN,NaN,3.0,4.0,2.0,1.0,1.0,6762000

In [116]:
df.columns

Index(['Unnamed: 0', 'Name', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Other Rooms',
       'Floor', 'Floors in Building', 'bedrooms', 'bathrooms', 'kitchens',
       'servant_quarters', 'store_rooms', 'Price'],
      dtype='object')

In [117]:
df.shape

(2499, 18)

In [118]:
df1.shape

(2499, 72)

In [124]:
df1.iloc[900]['Name']

'4 BHK Askari 10 - Sector S, Askari 10, Askari, Lahore, Punjab'

In [125]:
df.iloc[900]['Name']

'4 BHK Askari 10 - Sector S, Askari 10, Askari, Lahore, Punjab'

In [126]:
df["Features"] = df1["Features"].values

In [127]:
df.columns

Index(['Unnamed: 0', 'Name', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Other Rooms',
       'Floor', 'Floors in Building', 'bedrooms', 'bathrooms', 'kitchens',
       'servant_quarters', 'store_rooms', 'Price', 'Features'],
      dtype='object')

In [129]:
df['Features'][0]

'Parking Spaces | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor : 8 | Floors in Building : 11 | Elevators | Service Elevators in Building | Other Main Features | Broadband Internet Access | Satellite or Cable TV Ready | Business Center or Media Room in Building | Conference Room in Building | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Other Healthcare and Recreation Facilities | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Laundry or Dry Cleaning Facility | Facilities for Disabled | Pets Allowed | Other Facilities'

In [130]:
df['Features'].isna().sum()

np.int64(53)

In [131]:
socity_df=pd.read_csv("E:/Project/Data Cleaning/socities_df.csv")

In [134]:
socity_df['Society Name'].unique()

array(['Aabpara Coop Housing Society',
       'Abdalians Cooperative Housing Society', 'Abdullah Town',
       'Abid City', 'Abuzar Housing Scheme', 'Adams Housing Scheme',
       'Aftab Garden', 'Agrics Town', 'Ahmad Avenue',
       'Ahmad Housing Society', 'AIMC Residential Colony',
       'Airline Housing Society', 'Aitchison Society', 'Akram Abad',
       'Al Hafeez Gardens', 'Al Hamra Town', 'Al Haram City',
       'Al Haram Garden', 'Al Jalil Garden', 'Al Jannat Homes',
       'Al Jannat Housing Scheme', 'Al Kareem Garden', 'Al Madina Avenue',
       'Al Noor Park Housing Society', 'Al Rahim Homes',
       'Al Raziq Garden', 'Al-Ahmad Garden Housing Scheme',
       'Al-Amin Housing Society', 'Al-Ghani Garden', 'Al-Hadi Garden',
       'Al-Hamd Gardens', 'Al-Kareem Premier Housing Scheme',
       'Al-Mava Housing Scheme', 'Al-Noor Orchard', 'Al-Qayyum Garden',
       'Al-Rehmat Housing', 'Al-Wahab Garden - Phase 1', 'Ali Park',
       'Ali Town', 'Ali View Garden', 'Alia Town', 'Allama Iqbal Town',
       'Alpha Society', 'Aman Town', 'Amina Park',
       'Angoori Bagh Scheme 1', 'Angoori Bagh Scheme 1 - Block A',
       'Anwar Town', 'Architects Engineers Housing Society', 'Arya Nagar',
       'Ashiana-e-Quaid Housing Scheme', 'Ashrafi Town', 'Askari 10',
       'Askari 11', 'Askari 9', 'Atomic Energy Society - PAEC',
       'Avicenna City', 'Awami Colony', 'Awan Town',
       'Awasia Housing Society', 'Azam Gardens', 'Azizia Town', 'Badduke',
       'Bagh Gul Begum', 'Bagh-e-Iram Housing Society', 'Bahar Colony',
       'Bahria Education & Medical City', 'Bahria Nasheman',
       'Bahria Nasheman - Iris', 'Bahria Nasheman - Sunflower',
       'Bahria Nasheman - Zinia', 'Bahria Orchard', 'Bahria Town',
       'Bahria Town - Overseas Enclave', 'Bandian Wala',
       'Bankers Avenue Cooperative Housing Society',
       'Bankers Co-operative Housing Society', 'Barkat Market',
       'Bata Officer Colony', 'Beacon House Society', 'Bhatti Colony',
       'Bilal Gunj', 'Bismillah Housing Scheme',
       'BOR - Board of Revenue Housing Society', 'Canal Burg',
       'Canal Fort II', 'Canal Garden', 'Canal Park', 'Canal Valley',
       'Canal View', 'Cavalry Ground', 'Central Park Housing Scheme',
       'Chahal Homes', 'Chauburji Quarters', 'Chaudhary Colony',
       'China Scheme', 'Chinar Bagh', 'Chinar Court', 'Christian Colony',
       'Civil Defence', 'CMA Colony', 'Combo Colony', 'Cricketer Villas',
       'Dawood Residency Housing Scheme', 'DHA 9 Town', 'DHA Defence',
       'Dilkusha Gardens', 'Divine Gardens', 'Divine Homes',
       'Doctors Housing Society', 'Dream Avenue Lahore', 'Dream Gardens',
       'Dream Housing Society', 'Dream Villas', 'Eden Avenue',
       'Eden Avenue Extension', 'Eden Canal Villas', 'Eden City',
       'Eden Cottage 1', 'Eden Cottages 2', 'Eden Defence Villas',
       'Eden Gardens', 'Eden Gardens Extension', 'Eden Lane Villas 1',
       'Eden Lane Villas 2', 'Eden Palace Villas', 'Eden Park',
       'Eden Residencia', 'Eden Value Homes', 'Eden Villas',
       'Edenabad Extension', 'Edenabad Extension 1', 'Education Town',
       'Elite Town', 'EME Society', 'Etihad Town',
       'Evergreen Housing Scheme', 'Excise & Taxation Housing Scheme',
       'Faisal Town', 'Farid Kot House', 'Farooq Avenue',
       'Fazaia Housing Scheme', 'Fazlia Colony', 'Firdous Colony',
       'Formanites Housing Scheme', 'Fort Villas', 'Garden Town',
       'GCP Housing Scheme', 'Ghalib Colony', 'Ghaus Farm Housing Scheme',
       'Ghausia Colony Cantt', 'Ghosia Colony', 'Golf View Lane',
       'Golf View Residencia', 'GOR 2', 'GOR 3', 'GOR 4', 'GOR 5',
       'Gosha-e-Ahbab', 'Government Superior Services',
       'Government Transport Headquarters Cooperative Housing Society',
       'Govt Officers Cooperative Housing Society',
       'Grand Avenues Housing Scheme', 'Green Acres Housing Society',
       'Green Avenue Housing Society', 'Green Cap Housing Society',
       'Green City', 'Green Forts 1', 'Green Forts 2', 'Green Forts 4',
       'Green Park Society', 'Green Town Sector D2', 'Gujjar Colony',
       'Gujjarpura', 'Gul Afshan Society', 'Gul-e-Damin',
       'Gulbahar Colony', 'Gulberg', 'Gulberg 1', 'Gulberg 2',
       'Gulberg 3', 'Gulberg 4', 'Gulberg 5', 'Guldasht Town',
       'Gulfishan Colony', 'Gulfishan Town', 'Gulistan Colony',
       'Gulshan Ali Colony', 'Gulshan Colony',
       'Gulshan View Residence Society', 'Gulshan-e-Ahbab',
       'Gulshan-e-Aiwan Housing Society', 'Gulshan-e-Jinnah',
       'Gulshan-e-Lahore', 'Gulshan-E-Madina',
       'Gulshan-E-Mustafa Housing Society', 'Gulshan-e-Ravi',
       'Gulshan-e-Ravi - Civic Centre', 'Gulshan-e-Sardar Housing Scheme',
       'Gulzaib Colony', 'Habib Homes', 'Haji Park Housing Scheme',
       'Hajveri Town', 'Hamdan Life Society', 'Hamza Town', 'Hanjarwal',
       'HBFC Housing Society', 'Husnainabad', 'Ichhra', 'Icon Homes',
       'Ideal Homes', 'Immad Garden Housing Scheme',
       'Imperial Garden Homes', 'Inmol Society',
       'International City Country Homes', 'Iqbal Colony', 'Iqbal Garden',
       'Iqbal Park', 'Irrigation Colony', 'Irum Garden Housing Society',
       'Islam Nagar', 'Islamabad Colony', 'Ittehad Colony',
       'Ittifaq Town', 'Izmir Town', 'Izmir Town Extension',
       'Jaffar Town', 'Jaffaria Colony', 'Jamil Town', 'Jewa Town',
       'Jewan Mal', 'Jinnah Colony', 'Jinnah Park', 'Johar Town',
       'Jubilee Town', 'Jubilee Town - Commercial Area',
       'Judicial Colony', 'Kakezai Housing Society', 'Karamabad',
       'Kausar Colony', 'KEMC Housing Society', 'Khayaban-e-Amin',
       'Khayaban-e-Quaid', 'Khuda Buksh Colony', 'Kings Town',
       'Labor Colony', 'Lahore Avenue', 'Lahore Greenz',
       'Lahore Motorway City', 'Lahore Smart City', 'Lake City',
       'Lalazaar Garden', 'Land Breeze Housing Society', 'Larechs Colony',
       'LDA Avenue', 'LDA City', 'LDA Colony', 'LDA Quarters',
       'Madina Colony', 'Madni Gardens Housing Scheme', 'Main Market',
       'Makkah Colony', 'Mansoora Homes', 'Mansoorah',
       'Marghzar Officers Colony', 'Maryam Town', 'Mateen Avenue',
       'Mateen Garden', 'Mehal Avenue', 'Mehrabad', 'MET 1', 'MET 2',
       'Mian Amiruddin Park', 'Mian Mir Colony', 'Midcity',
       'Military Accounts Housing Society', 'Millat Colony',
       'Millat Tractors Employees Housing Society',
       'Model City Housing Scheme', 'Model Colony', 'Model Town',
       'Mohlanwal Scheme', 'Moon Villas', 'Muhammadpura', 'Muqaddas Park',
       'Mushtaq Park - Phase 3', 'Muslim Gunj',
       'Muslim Nagar Housing Scheme', 'Muslim Town',
       'Mustafa Garden Phase 3', 'Mustafa Town', 'Nagina Homes',
       'National Homes', 'Nawab Town', 'Nawaz Sharif Colony',
       'Nayyab Villas', 'Naz Town', 'Nazir Garden Society', 'NB Villas',
       'Nespak Housing Scheme', 'New Chauburji Park', 'New Green City',
       'New Iqbal Park Cantt', 'New Kashmir Park Housing Scheme',
       'New Khan Colony', 'New Lahore City', 'New Muslim Town',
       'New Samanabad', 'New Shah Kamal Colony', 'New Super Town',
       'NFC 1', 'NFC 2', 'NFC 2 - Commercial Area', 'Nishat Colony',
       'Officer Colony', 'Olympians Cooperative Housing Society',
       'Omega Residencia', 'OPF Housing Scheme', 'P & D Housing Society',
       'P&T Colony', 'PAF Colony', 'PAF Falcon Complex',
       'Pak Arab Enclave', 'Pak Arab Housing Society',
       'Pakistan Medical Housing Society', 'Pakki Thatti', 'Palm City',
       'Palm Villas', 'Paradise Apartment', 'Paradise Homes Super Town',
       'Paragon City', 'Park Avenue Housing Scheme', 'Park View City',
       'PASSCO Housing Society', 'PCSIR Staff Colony',
       'PIA Housing Scheme', 'Pine Villas', 'Platinum Homes',
       'Prime Homes 1', 'Prime Homes 2', 'Public Health Society',
       'Punjab Coop Housing Society',
       'Punjab Government Servant Housing Foundation',
       'Punjab Small Industries Colony',
       'Punjab University Employees Society', 'Qadri Colony', 'Qasimpura',
       'Qazi Town', 'Quaid-e-Azam Industrial Estate',
       'Rail Town (Canal City)', 'Railway Colony', 'Railway Golf Avenue',
       'Railway Shalimar Larechs Scheme', 'Railway Wireless Colony',
       'Rajpoot Town', 'Rasool Park', 'Real Cottages',
       'Rehman City - Phase 4', 'Rehman City Phase 6', 'Rehman Gardens',
       'Rehman Housing Society', 'Rehman Park', 'Rehman Villas',
       'Rewaz Garden', 'River Edge Housing Scheme',
       'River View Coop Housing Society', 'Rizwan Garden Scheme',
       'Rose Garden', 'Royal Residencia', 'Rustam Park', 'SA Gardens',
       'Saadat Avenue', 'Saadi Park', 'Sabzazar Scheme',
       'Sadat Cooperative Housing Society (College Town)',
       'Safari Garden Housing Scheme', 'Safiya Homes', 'Sahafi Colony',
       'Saiden Shah Colony', 'Saidpur', 'Salli Town', 'Sally Town South',
       'Saman Berg', 'Samanabad', 'Samanabad Main Boulevard',
       'Satellite Town', 'Schazoo Housing Colony', 'Scheme No 1',
       'Shabbir Town - Executive Apartments', 'Shadbagh', 'Shadman 1',
       'Shadman 2', 'Shadman Enclave', 'Shah Farid', 'Shah Jamal',
       'Shahtaj Colony', 'Shalimar Housing Scheme', 'Sheraz Town',
       'Sikanderabad', 'SJ Garden', 'Sodiwal', 'State Bank Colony',
       'Subedar Colony', 'Sukh Chayn Gardens', 'Sultan Park',
       'Sultan Town', 'Sun City Housing Scheme',
       'Sundar Industrial Estate', 'Sundar Small Industrial Estate 2',
       'Sunflower Housing Society', 'Sunfort Gardens', 'Sunny Park',
       'Super Town', 'T & T Aabpara Housing Society', 'Taj Bagh Scheme',
       'Tajpura', 'Takbeer Villas', 'Tariq Gardens', 'TECH Society',
       'Theme Park View Society', 'Timber Market Scheme',
       'TIP Housing Society', 'Toheed Park', 'Township',
       'Township - Civic Center', 'Tricon Village', 'UET Housing Society',
       'Umer Colony', 'Upper Mall', 'Urban Villas',
       'Valencia -  Commercial Zone A1', 'Valencia -  Commercial Zone A2',
       'Valencia -  Commercial Zone A3', 'Valencia -  Commercial Zone A4',
       'Valencia -  Commercial Zone A5', 'Valencia -  Commercial Zone A6',
       'Valencia -  Commercial Zone A7', 'Valencia -  Commercial Zone A8',
       'Valencia -  Commercial Zone B', 'Valencia -  Commercial Zone C',
       'Valencia -  Commercial Zone D', 'Valencia - Commercial Zone A',
       'Valencia Housing Society', 'Venus Housing Scheme',
       'Wafaqi Colony', 'Wahdat Colony', 'Walton Railway Officers Colony',
       'Wapda Finance Officers Cooperative Housing Society',
       'Wapda Finance Officers Subsistence Farm Homes Cooperative Society',
       'Wapda Officers Colony', 'Wapda Town', 'Wapda Town Extension',
       'Waris Colony', 'West Wood Housing Society',
       'Women Housing Society', 'Wyeth Employees Coop Housing',
       'Yasrab Colony', 'Zaamin Fazaia Villas', 'Zafar Colony',
       'Zaheer Villas', 'Zain Residencia', 'Zam Zam City', 'Zaman Colony',
       'Zubaida Park'], dtype=object)

In [135]:
df.columns

Index(['Unnamed: 0', 'Name', 'Marla', 'Area (sqft)', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Other Rooms',
       'Floor', 'Floors in Building', 'bedrooms', 'bathrooms', 'kitchens',
       'servant_quarters', 'store_rooms', 'Price', 'Features'],
      dtype='object')

In [354]:
socities = [
'Aabpara Coop Housing Society',
'Abdalians Cooperative Housing Society', 'Abdullah Town',
'Abid City', 'Abuzar Housing Scheme', 'Adams Housing Scheme',
'Aftab Garden', 'Agrics Town', 'Ahmad Avenue',
'Ahmad Housing Society', 'AIMC Residential Colony',
'Airline Housing Society', 'Aitchison Society', 'Akram Abad',
'Al Hafeez Gardens', 'Al Hamra Town', 'Al Haram City',
'Al Haram Garden', 'Al Jalil Garden', 'Al Jannat Homes',
'Al Jannat Housing Scheme', 'Al Kareem Garden', 'Al Madina Avenue',
'Al Noor Park Housing Society', 'Al Rahim Homes',
'Al Raziq Garden', 'Al-Ahmad Garden Housing Scheme',
'Al-Amin Housing Society', 'Al-Ghani Garden', 'Al-Hadi Garden',
'Al-Hamd Gardens', 'Al-Kareem Premier Housing Scheme',
'Al-Mava Housing Scheme', 'Al-Noor Orchard', 'Al-Qayyum Garden',
'Al-Rehmat Housing', 'Al-Wahab Garden - Phase 1', 'Ali Park',
'Ali Town', 'Ali View Garden', 'Alia Town', 'Allama Iqbal Town',
'Alpha Society', 'Aman Town', 'Amina Park',
'Angoori Bagh Scheme 1', 'Angoori Bagh Scheme 1 - Block A',
'Anwar Town', 'Architects Engineers Housing Society', 'Arya Nagar',
'Ashiana-e-Quaid Housing Scheme', 'Ashrafi Town', 'Askari 10',
'Askari 11', 'Askari 9', 'Atomic Energy Society - PAEC','Askari 5'
'Avicenna City', 'Awami Colony', 'Awan Town',
'Awasia Housing Society', 'Azam Gardens', 'Azizia Town', 'Badduke',
'Bagh Gul Begum', 'Bagh-e-Iram Housing Society', 'Bahar Colony',
'Bahria Education & Medical City', 'Bahria Nasheman',
'Bahria Nasheman - Iris', 'Bahria Nasheman - Sunflower',
'Bahria Nasheman - Zinia', 'Bahria Orchard', 'Bahria Town',
'Bahria Town - Overseas Enclave', 'Bandian Wala',
'Bankers Avenue Cooperative Housing Society',
'Bankers Co-operative Housing Society', 'Barkat Market',
'Bata Officer Colony', 'Beacon House Society', 'Bhatti Colony',
'Bilal Gunj', 'Bismillah Housing Scheme',
'BOR - Board of Revenue Housing Society', 'Canal Burg',
'Canal Fort II', 'Canal Garden', 'Canal Park', 'Canal Valley',
'Canal View', 'Cavalry Ground', 'Central Park Housing Scheme',
'Chahal Homes', 'Chauburji Quarters', 'Chaudhary Colony',
'China Scheme', 'Chinar Bagh', 'Chinar Court', 'Christian Colony',
'Civil Defence', 'CMA Colony', 'Combo Colony', 'Cricketer Villas',
'Dawood Residency Housing Scheme', 'DHA 9 Town', 'DHA Defence',
'Dilkusha Gardens', 'Divine Gardens', 'Divine Homes',
'Doctors Housing Society', 'Dream Avenue Lahore', 'Dream Gardens',
'Dream Housing Society', 'Dream Villas', 'Eden Avenue',
'Eden Avenue Extension', 'Eden Canal Villas', 'Eden City',
'Eden Cottage 1', 'Eden Cottages 2', 'Eden Defence Villas',
'Eden Gardens', 'Eden Gardens Extension', 'Eden Lane Villas 1',
'Eden Lane Villas 2', 'Eden Palace Villas', 'Eden Park',
'Eden Residencia', 'Eden Value Homes', 'Eden Villas',
'Edenabad Extension', 'Edenabad Extension 1', 'Education Town',
'Elite Town', 'EME Society', 'Etihad Town',
'Evergreen Housing Scheme', 'Excise & Taxation Housing Scheme',
'Faisal Town', 'Farid Kot House', 'Farooq Avenue',
'Fazaia Housing Scheme', 'Fazlia Colony', 'Firdous Colony',
'Formanites Housing Scheme', 'Fort Villas', 'Garden Town',
'GCP Housing Scheme', 'Ghalib Colony', 'Ghaus Farm Housing Scheme',
'Ghausia Colony Cantt', 'Ghosia Colony', 'Golf View Lane',
'Golf View Residencia', 'GOR 2', 'GOR 3', 'GOR 4', 'GOR 5',
'Gosha-e-Ahbab', 'Government Superior Services',
'Government Transport Headquarters Cooperative Housing Society',
'Govt Officers Cooperative Housing Society',
'Grand Avenues Housing Scheme', 'Green Acres Housing Society',
'Green Avenue Housing Society', 'Green Cap Housing Society',
'Green City', 'Green Forts 1', 'Green Forts 2', 'Green Forts 4',
'Green Park Society', 'Green Town Sector D2', 'Gujjar Colony',
'Gujjarpura', 'Gul Afshan Society', 'Gul-e-Damin',
'Gulbahar Colony', 'Gulberg', 'Gulberg 1', 'Gulberg 2',
'Gulberg 3', 'Gulberg 4', 'Gulberg 5', 'Guldasht Town',
'Gulfishan Colony', 'Gulfishan Town', 'Gulistan Colony',
'Gulshan Ali Colony', 'Gulshan Colony',
'Gulshan View Residence Society', 'Gulshan-e-Ahbab',
'Gulshan-e-Aiwan Housing Society', 'Gulshan-e-Jinnah',
'Gulshan-e-Lahore', 'Gulshan-E-Madina',
'Gulshan-E-Mustafa Housing Society', 'Gulshan-e-Ravi',
'Gulshan-e-Ravi - Civic Centre', 'Gulshan-e-Sardar Housing Scheme',
'Gulzaib Colony', 'Habib Homes', 'Haji Park Housing Scheme',
'Hajveri Town', 'Hamdan Life Society', 'Hamza Town', 'Hanjarwal',
'HBFC Housing Society', 'Husnainabad', 'Ichhra', 'Icon Homes',
'Ideal Homes', 'Immad Garden Housing Scheme',
'Imperial Garden Homes', 'Inmol Society',
'International City Country Homes', 'Iqbal Colony', 'Iqbal Garden',
'Iqbal Park', 'Irrigation Colony', 'Irum Garden Housing Society',
'Islam Nagar', 'Islamabad Colony', 'Ittehad Colony',
'Ittifaq Town', 'Izmir Town', 'Izmir Town Extension',
'Jaffar Town', 'Jaffaria Colony', 'Jamil Town', 'Jewa Town',
'Jewan Mal', 'Jinnah Colony', 'Jinnah Park', 'Johar Town',
'Jubilee Town', 'Jubilee Town - Commercial Area',
'Judicial Colony', 'Kakezai Housing Society', 'Karamabad',
'Kausar Colony', 'KEMC Housing Society', 'Khayaban-e-Amin',
'Khayaban-e-Quaid', 'Khuda Buksh Colony', 'Kings Town',
'Labor Colony', 'Lahore Avenue', 'Lahore Greenz',
'Lahore Motorway City', 'Lahore Smart City', 'Lake City',
'Lalazaar Garden', 'Land Breeze Housing Society', 'Larechs Colony',
'LDA Avenue', 'LDA City', 'LDA Colony', 'LDA Quarters',
'Madina Colony', 'Madni Gardens Housing Scheme', 'Main Market',
'Makkah Colony', 'Mansoora Homes', 'Mansoorah',
'Marghzar Officers Colony', 'Maryam Town', 'Mateen Avenue',
'Mateen Garden', 'Mehal Avenue', 'Mehrabad', 'MET 1', 'MET 2',
'Mian Amiruddin Park', 'Mian Mir Colony', 'Midcity',
'Military Accounts Housing Society', 'Millat Colony',
'Millat Tractors Employees Housing Society',
'Model City Housing Scheme', 'Model Colony', 'Model Town',
'Mohlanwal Scheme', 'Moon Villas', 'Muhammadpura', 'Muqaddas Park',
'Mushtaq Park - Phase 3', 'Muslim Gunj',
'Muslim Nagar Housing Scheme', 'Muslim Town',
'Mustafa Garden Phase 3', 'Mustafa Town', 'Nagina Homes',
'National Homes', 'Nawab Town', 'Nawaz Sharif Colony',
'Nayyab Villas', 'Naz Town', 'Nazir Garden Society', 'NB Villas',
'Nespak Housing Scheme', 'New Chauburji Park', 'New Green City',
'New Iqbal Park Cantt', 'New Kashmir Park Housing Scheme',
'New Khan Colony', 'New Lahore City', 'New Muslim Town',
'New Samanabad', 'New Shah Kamal Colony', 'New Super Town',
'NFC 1', 'NFC 2', 'NFC 2 - Commercial Area', 'Nishat Colony',
'Officer Colony', 'Olympians Cooperative Housing Society',
'Omega Residencia', 'OPF Housing Scheme', 'P & D Housing Society',
'P&T Colony', 'PAF Colony', 'PAF Falcon Complex',
'Pak Arab Enclave', 'Pak Arab Housing Society',
'Pakistan Medical Housing Society', 'Pakki Thatti', 'Palm City',
'Palm Villas', 'Paradise Apartment', 'Paradise Homes Super Town',
'Paragon City', 'Park Avenue Housing Scheme', 'Park View City',
'PASSCO Housing Society', 'PCSIR Staff Colony',
'PIA Housing Scheme', 'Pine Villas', 'Platinum Homes',
'Prime Homes 1', 'Prime Homes 2', 'Public Health Society',
'Punjab Coop Housing Society',
'Punjab Government Servant Housing Foundation',
'Punjab Small Industries Colony',
'Punjab University Employees Society', 'Qadri Colony', 'Qasimpura',
'Qazi Town', 'Quaid-e-Azam Industrial Estate',
'Rail Town (Canal City)', 'Railway Colony', 'Railway Golf Avenue',
'Railway Shalimar Larechs Scheme', 'Railway Wireless Colony',
'Rajpoot Town', 'Rasool Park', 'Real Cottages',
'Rehman City - Phase 4', 'Rehman City Phase 6', 'Rehman Gardens',
'Rehman Housing Society', 'Rehman Park', 'Rehman Villas',
'Rewaz Garden', 'River Edge Housing Scheme',
'River View Coop Housing Society', 'Rizwan Garden Scheme',
'Rose Garden', 'Royal Residencia', 'Rustam Park', 'SA Gardens',
'Saadat Avenue', 'Saadi Park', 'Sabzazar Scheme',
'Sadat Cooperative Housing Society (College Town)',
'Safari Garden Housing Scheme', 'Safiya Homes', 'Sahafi Colony',
'Saiden Shah Colony', 'Saidpur', 'Salli Town', 'Sally Town South',
'Saman Berg', 'Samanabad', 'Samanabad Main Boulevard',
'Satellite Town', 'Schazoo Housing Colony', 'Scheme No 1',
'Shabbir Town - Executive Apartments', 'Shadbagh', 'Shadman 1',
'Shadman 2', 'Shadman Enclave', 'Shah Farid', 'Shah Jamal',
'Shahtaj Colony', 'Shalimar Housing Scheme', 'Sheraz Town',
'Sikanderabad', 'SJ Garden', 'Sodiwal', 'State Bank Colony',
'Subedar Colony', 'Sukh Chayn Gardens', 'Sultan Park',
'Sultan Town', 'Sun City Housing Scheme',
'Sundar Industrial Estate', 'Sundar Small Industrial Estate 2',
'Sunflower Housing Society', 'Sunfort Gardens', 'Sunny Park',
'Super Town', 'T & T Aabpara Housing Society', 'Taj Bagh Scheme',
'Tajpura', 'Takbeer Villas', 'Tariq Gardens', 'TECH Society',
'Theme Park View Society', 'Timber Market Scheme',
'TIP Housing Society', 'Toheed Park', 'Township',
'Township - Civic Center', 'Tricon Village', 'UET Housing Society',
'Umer Colony', 'Upper Mall', 'Urban Villas',
'Valencia -  Commercial Zone A1', 'Valencia -  Commercial Zone A2',
'Valencia -  Commercial Zone A3', 'Valencia -  Commercial Zone A4',
'Valencia -  Commercial Zone A5', 'Valencia -  Commercial Zone A6',
'Valencia -  Commercial Zone A7', 'Valencia -  Commercial Zone A8',
'Valencia -  Commercial Zone B', 'Valencia -  Commercial Zone C',
'Valencia -  Commercial Zone D', 'Valencia - Commercial Zone A',
'Valencia Housing Society', 'Venus Housing Scheme',
'Wafaqi Colony', 'Wahdat Colony', 'Walton Railway Officers Colony',
'Wapda Finance Officers Cooperative Housing Society',
'Wapda Finance Officers Subsistence Farm Homes Cooperative Society',
'Wapda Officers Colony', 'Wapda Town', 'Wapda Town Extension',
'Waris Colony', 'West Wood Housing Society',
'Women Housing Society', 'Wyeth Employees Coop Housing',
'Yasrab Colony', 'Zaamin Fazaia Villas', 'Zafar Colony',
'Zaheer Villas', 'Zain Residencia', 'Zam Zam City', 'Zaman Colony',
'Zubaida Park','DHA phase 4','Icon Valley','Askari','Raiwind Road','Main Canal Bank Road','Multan Road','Cooper Road','Band Road','Islampura',
'Ferozepur Road','Abdul Sattar Edhi Road','Iqbal Avenue','Sant Nagar','Revenue Society','Davis Road',
'Khayaban-e-Jinnah','Pine Avenue','Shanghai Road','Lawrence Road','Saddar, Cantt','Jail Road','GT Road','Aziz Bhatti Road',
'Engineers Town','Ring Road','Maulana Shaukat Ali Road','Shadman','Mozang','Ferozpur Road'
]

In [355]:
import re
import numpy as np

# if your array is a numpy array
societies = socities

# prefer longer names first
societies = sorted(societies, key=len, reverse=True)
soc_l = [s.lower() for s in societies]

def find_society(text):
    if not isinstance(text, str):
        return np.nan
    t = text.lower()
    for s, s_l in zip(societies, soc_l):
        if s_l in t:
            return s
    return np.nan

# df["society"] = df["Name"].apply(find_society)

# fallback to Link
# mask = df["society"].isna()
# df.loc[mask, "society"] = df.loc[mask, "Link"].apply(
#     lambda x: find_society(re.sub(r"[-_]", " ", str(x)))
# )

In [356]:
def find_from_name_address_desc(row):
    s = find_society(row.get("Name", ""))
    if pd.isna(s):
        s = find_society(row.get("Address", ""))
    if pd.isna(s):
        s = find_society(row.get("Description", ""))
    return s

df["society"] = df.apply(find_from_name_address_desc, axis=1)

In [357]:
df['society'].isna().sum()

np.int64(0)

In [359]:
df[df['society'].isna()].sample(0)

Empty DataFrame
Columns: [Unnamed: 0, Name, Marla, Area (sqft), Floor Number, Total Floors, Built Year, Address, Description, Other Rooms, Floor, Floors in Building, bedrooms, bathrooms, kitchens, servant_quarters, store_rooms, Price, Features, society]
Index: []

In [360]:
df.to_csv("2nd_video_hald.csv")

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [58]:
df=pd.read_csv("2nd_video_hald.csv")

In [59]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Name', 'Marla', 'Area (sqft)',
       'Floor Number', 'Total Floors', 'Built Year', 'Address', 'Description',
       'Other Rooms', 'Floor', 'Floors in Building', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price', 'Features',
       'society'],
      dtype='object')

In [60]:
df['Features'].isna().sum()

np.int64(53)

In [61]:
df1=pd.read_csv("E:\Project\Data Cleaning\lahore_house_properties_final.csv")

In [62]:
df1.columns

Index(['Property ID', 'Society', 'Society Link', 'Name', 'Page Title', 'Price',
       'Marla', 'Area (sqft)', 'Bedrooms', 'Baths', 'Floor Number',
       'Total Floors', 'Built Year', 'Address', 'Description', 'Features',
       'Nearby Locations and Other Facilities', 'Rooms', 'Other Rooms', 'Link',
       'Built in year', 'Parking Spaces', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floors', 'Other Main Features',
       'Broadband Internet Access', 'Intercom', 'Community Lawn or Garden',
       'Community Swimming Pool', 'Community Gym',
       'First Aid or Medical Centre', 'Day Care Centre', 'Kids Play Area',
       'Barbeque Area', 'Mosque', 'Community Centre', 'Lawn or Garden',
       'Jacuzzi', 'Nearby Schools', 'Nearby Hospitals',
       'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Section - Main Features', 'Section - Rooms',
       'Section - Business and Communication', 'Section - Community Features',
       'Section - Healthcare Recreational',
       'Section - Nearby Locations and Other Facilities',
       'Section - Other Facilities', 'Furnished',
       'Satellite or Cable TV Ready', 'Swimming Pool', 'Sauna',
       'Facilities for Disabled', 'Other Facilities',
       'Other Business and Communication Facilities',
       'Other Community Facilities',
       'Other Healthcare and Recreation Facilities'],
      dtype='object')

In [63]:
# build one Features value per society (most common)
feature_map = (
    df1.dropna(subset=["Features"])
       .groupby("Society")["Features"]
       .agg(lambda x: x.mode().iat[0] if not x.mode().empty else x.iloc[0])
)

df["Features"] = df["Features"].fillna(df["society"].map(feature_map))

In [64]:
features_unique = (
    df["Features"]
    .dropna()
    .str.split("|")
    .explode()
    .str.strip()
    .str.split(":", n=1)
    .str[0]
    .str.strip()
    .unique()
)

features_unique

array(['Parking Spaces', 'Lobby in Building', 'Double Glazed Windows',
       'Central Air Conditioning', 'Central Heating', 'Flooring',
       'Electricity Backup', 'Waste Disposal', 'Floor',
       'Floors in Building', 'Elevators', 'Service Elevators in Building',
       'Other Main Features', 'Broadband Internet Access',
       'Satellite or Cable TV Ready',
       'Business Center or Media Room in Building',
       'Conference Room in Building', 'Intercom', 'ATM Machines',
       'Other Business and Communication Facilities',
       'Community Lawn or Garden', 'Community Swimming Pool',
       'Community Gym', 'First Aid or Medical Centre', 'Day Care Centre',
       'Kids Play Area', 'Barbeque Area', 'Mosque', 'Community Centre',
       'Other Community Facilities', 'Sauna', 'Jacuzzi',
       'Other Healthcare and Recreation Facilities', 'Nearby Schools',
       'Nearby Hospitals', 'Nearby Shopping Malls', 'Nearby Restaurants',
       'Distance From Airport (kms)', 'Nearby Public Transport Service',
       'Other Nearby Places', 'Maintenance Staff', 'Security Staff',
       'Laundry or Dry Cleaning Facility', 'Facilities for Disabled',
       'Pets Allowed', 'Other Facilities', 'Furnished',
       'Communal/Shared Kitchen', 'Built in year', 'Pets Not Allowed',
       'Floors', 'Lawn or Garden', 'Swimming Pool', 'Possesion', 'Corner',
       'Park Facing', 'Disputed', 'File', 'Balloted', 'Sewerage',
       'Electricity', 'Water Supply', 'Sui Gas', 'Boundary Wall'],
      dtype=object)

In [65]:
weights = {
    "Parking Spaces": 4,
    "Lobby in Building": 4,
    "Double Glazed Windows": 3,
    "Central Air Conditioning": 5,
    "Central Heating": 4,
    "Flooring": 4,
    "Electricity Backup": 4,
    "Waste Disposal": 2,
    "Floors in Building": 2,
    "Elevators": 3,
    "Service Elevators in Building": 4,
    "Broadband Internet Access": 2,
    "Satellite or Cable TV Ready": 1,
    "Business Center or Media Room in Building": 4,
    "Conference Room in Building": 4,
    "Intercom": 3,
    "ATM Machines": 2,
    "Community Lawn or Garden": 4,
    "Community Swimming Pool": 5,
    "Community Gym": 5,
    "First Aid or Medical Centre": 3,
    "Day Care Centre": 3,
    "Kids Play Area": 3,
    "Barbeque Area": 3,
    "Mosque": 2,
    "Community Centre": 3,
    "Sauna": 5,
    "Jacuzzi": 5,
    "Nearby Schools": 3,
    "Nearby Hospitals": 3,
    "Nearby Shopping Malls": 4,
    "Nearby Restaurants": 3,
    "Distance From Airport (kms)": 2,
    "Nearby Public Transport Service": 3,
    "Maintenance Staff": 4,
    "Security Staff": 5,
    "Laundry or Dry Cleaning Facility": 3,
    "Facilities for Disabled": 3,
    "Pets Allowed": 3,
    "Furnished": 5,
    "Communal/Shared Kitchen": 1,
    "Built in year": 2,
    "Corner": 4,
    "Park Facing": 5,
    "Sewerage": 2,
    "Electricity": 2,
    "Water Supply": 2,
    "Sui Gas": 2,
    "Boundary Wall": 4
}

In [66]:
w = {k.lower(): v for k, v in weights.items()}

def luxury_from_features(s):
    if pd.isna(s):
        return 0
    parts = [p.strip() for p in str(s).split("|") if p.strip()]
    names = {p.split(":", 1)[0].strip().lower() for p in parts}  # use set to avoid double count
    return sum(w.get(name, 0) for name in names)

df["luxury_score"] = df["Features"].apply(luxury_from_features)

In [67]:
import pandas as pd
pd.set_option("display.max_rows", None)
pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [68]:
df[['luxury_score','Features']].sample(1)

,luxury_score,Features
1281,125,Built in year : 2019 | Parking Spaces | Lobby in Building | Double Glazed Windows | Central Air Conditioning | Central Heating | Flooring | Electricity Backup | Waste Disposal | Floor | Floors in Building : 19 | Elevators : 3 | Service Elevators in Building | Other Main Features | Furnished | Broadband Internet Access | Satellite or Cable TV Ready | Intercom | ATM Machines | Other Business and Communication Facilities | Community Lawn or Garden | Community Swimming Pool | Community Gym | First Aid or Medical Centre | Day Care Centre | Kids Play Area | Barbeque Area | Mosque | Community Centre | Other Community Facilities | Sauna | Jacuzzi | Nearby Schools | Nearby Hospitals | Nearby Shopping Malls | Nearby Restaurants | Distance From Airport (kms) | Nearby Public Transport Service | Other Nearby Places | Maintenance Staff | Security Staff | Facilities for Disabled | Other Facilities

In [69]:
df = df.drop(columns=["Features"])

In [70]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Name', 'Marla', 'Area (sqft)',
       'Floor Number', 'Total Floors', 'Built Year', 'Address', 'Description',
       'Other Rooms', 'Floor', 'Floors in Building', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price', 'society',
       'luxury_score'],
      dtype='object')

In [71]:
df = df.rename(columns={"Other Rooms": "other_rooms"})

In [72]:
df['other_rooms'].iloc[0]

'Servant Quarters, Drawing Room, Dining Room, Store Rooms, Lounge or Sitting Room, Laundry Room'

In [73]:
unique_rooms = (
    df["other_rooms"]
    .dropna()
    .str.split(",")
    .explode()
    .str.strip()
    .unique()
)
unique_rooms

array(['Servant Quarters', 'Drawing Room', 'Dining Room', 'Store Rooms',
       'Lounge or Sitting Room', 'Laundry Room', 'Study Room',
       'Prayer Room', 'Powder Room', 'Gym', 'Steam Room', 'Other Rooms',
       'Bedrooms', 'Kitchens', 'Bathrooms'], dtype=object)

In [74]:
import pandas as pd

all_rooms = [
    "Servant Quarters", "Drawing Room", "Dining Room", "Store Rooms",
    "Lounge or Sitting Room", "Laundry Room", "Study Room",
    "Prayer Room", "Powder Room", "Gym", "Steam Room", "Other Rooms",
    "Bedrooms", "Kitchens", "Bathrooms"
]

skip = {"Bedrooms", "Bathrooms", "Kitchens", "Servant Quarters", "Store Rooms"}
rooms_to_add = [r for r in all_rooms if r not in skip and r not in df.columns]

def split_rooms(s):
    if pd.isna(s):
        return []
    return [x.strip() for x in str(s).split(",") if x.strip()]

rooms_list = df["other_rooms"].apply(split_rooms)

for room in rooms_to_add:
    df[room] = rooms_list.apply(lambda lst: 1 if room in lst else 0)

In [75]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Name', 'Marla', 'Area (sqft)',
       'Floor Number', 'Total Floors', 'Built Year', 'Address', 'Description',
       'other_rooms', 'Floor', 'Floors in Building', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price', 'society',
       'luxury_score', 'Drawing Room', 'Dining Room', 'Lounge or Sitting Room',
       'Laundry Room', 'Study Room', 'Prayer Room', 'Powder Room', 'Gym',
       'Steam Room', 'Other Rooms'],
      dtype='object')

In [85]:
df[['bedrooms','other_rooms']].sample(1)

,bedrooms,other_rooms
375,4.0,"Drawing Room, Dining Room, Study Room, Prayer Room, Powder Room, Gym, Steam Room, Lounge or Sitting Room, Laundry Room, Other Rooms"

In [89]:
df['bedrooms'].isna().sum()

np.int64(354)

In [88]:
mask = df["bedrooms"].isna() & df["other_rooms"].str.contains(r"\bBedrooms\b", case=False, na=False)
df.loc[mask, "bedrooms"] = 1

In [90]:
mapping = {
    "bathrooms": "Bathrooms",
    "kitchens": "Kitchens",
    "servant_quarters": "Servant Quarters",
    "store_rooms": "Store Rooms",
}

for col, label in mapping.items():
    mask = df[col].isna() & df["other_rooms"].str.contains(rf"\b{label}\b", case=False, na=False)
    df.loc[mask, col] = 1

In [91]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'Name', 'Marla', 'Area (sqft)',
       'Floor Number', 'Total Floors', 'Built Year', 'Address', 'Description',
       'other_rooms', 'Floor', 'Floors in Building', 'bedrooms', 'bathrooms',
       'kitchens', 'servant_quarters', 'store_rooms', 'Price', 'society',
       'luxury_score', 'Drawing Room', 'Dining Room', 'Lounge or Sitting Room',
       'Laundry Room', 'Study Room', 'Prayer Room', 'Powder Room', 'Gym',
       'Steam Room', 'Other Rooms'],
      dtype='object')

In [93]:
drop_cols = [
    "Unnamed: 0", "Unnamed: 0.1",
    "other_rooms"
]
df = df.drop(columns=drop_cols, errors="ignore")

In [96]:
df.columns

Index(['Name', 'Marla', 'Area (sqft)', 'Floor Number', 'Total Floors',
       'Built Year', 'Address', 'Description', 'Floor', 'Floors in Building',
       'bedrooms', 'bathrooms', 'kitchens', 'servant_quarters', 'store_rooms',
       'Price', 'society', 'luxury_score', 'Drawing Room', 'Dining Room',
       'Lounge or Sitting Room', 'Laundry Room', 'Study Room', 'Prayer Room',
       'Powder Room', 'Gym', 'Steam Room', 'Other Rooms'],
      dtype='object')

In [97]:
df.shape

(2499, 28)

In [98]:
df = df.rename(columns={
    "Name": "name",
    "Marla": "marla",
    "Area (sqft)": "area_sqft",
    "Floor Number": "floor_number",
    "Total Floors": "total_floors",
    "Built Year": "built_year",
    "Address": "address",
    "Description": "description",
    "Floor": "floor",
    "Floors in Building": "floors_in_building",
    "Price": "price",
    "Drawing Room": "drawing_room",
    "Dining Room": "dining_room",
    "Lounge or Sitting Room": "lounge_or_sitting_room",
    "Laundry Room": "laundry_room",
    "Study Room": "study_room",
    "Prayer Room": "prayer_room",
    "Powder Room": "powder_room",
    "Gym": "gym",
    "Steam Room": "steam_room",
    "Other Rooms": "other_rooms",
})

In [99]:
df.columns

Index(['name', 'marla', 'area_sqft', 'floor_number', 'total_floors',
       'built_year', 'address', 'description', 'floor', 'floors_in_building',
       'bedrooms', 'bathrooms', 'kitchens', 'servant_quarters', 'store_rooms',
       'price', 'society', 'luxury_score', 'drawing_room', 'dining_room',
       'lounge_or_sitting_room', 'laundry_room', 'study_room', 'prayer_room',
       'powder_room', 'gym', 'steam_room', 'other_rooms'],
      dtype='object')

In [100]:
df.shape

(2499, 28)

In [101]:
df.to_csv("lahore_flats_feature_engineered.csv", index=False)